import type { FandomConfig } from "../../types/fandom.ts";

export const ANIME_FANDOMS: FandomConfig[] = [
  {
    id: "my-hero-academia",
    name: "My Hero Academia",
    category: "anime",
    canonRules:
      "Respect the Quirk system — each person has at most one Quirk, and Quirks have defined limits. Follow UA High Academy structure (Class 1-A, 1-B, Support, Business, General Studies). Maintain the hero ranking system and provisional license requirements. Do not give characters Quirks they don't have. Use hero names correctly (e.g., Deku, Shoto, Red Riot). Blend school life with hero action.",
    locations:
      "UA High Academy, Heights Alliance dorms, Ground Beta, Tartarus prison, Deika City, Jaku Hospital, Hero agencies, The PLF base",
    characters: [
      "Izuku Midoriya",
      "Katsuki Bakugou",
      "Shoto Todoroki",
      "Ochaco Uraraka",
      "All Might / Toshinori Yagi",
      "Eijiro Kirishima",
      "Denki Kaminari",
      "Hitoshi Shinsou",
      "Dabi / Toya Todoroki",
      "Tomura Shigaraki",
      "Hawks / Keigo Takami",
      "Momo Yaoyorozu",
      "Fumikage Tokoyami",
      "Tenya Iida",
      "Aizawa Shouta / Eraserhead",
      "Tsuyu Asui",
      "Mina Ashido",
      "Kyouka Jirou",
      "Hanta Sero",
      "Mezo Shouji",
      "Present Mic / Hizashi Yamada",
      "Endeavor / Enji Todoroki",
      "Mirko / Rumi Usagiyama",
      "Toga Himiko",
      "Twice / Jin Bubaigawara",
      "Kurogiri",
      "Overhaul / Kai Chisaki",
      "Eri",
      "Nejire Hadou",
      "Tamaki Amajiki",
      "Mirio Togata",
    ],
    settingPlaceholder: "e.g., Heights Alliance common room after a grueling hero exercise",
  },
  {
    id: "naruto",
    name: "Naruto",
    category: "anime",
    canonRules:
      "Use chakra-based abilities and established jutsu. Respect ninja ranks (Genin, Chunin, Jonin, Kage) and village structure. Follow jutsu naming conventions and hand seal requirements. Use Japanese honorifics correctly (-kun, -chan, -sensei, -sama). Kekkei Genkai are bloodline-specific — do not give them to the wrong clans. Maintain the themes of bonds, perseverance, and the cycle of hatred.",
    locations:
      "Konohagakure, The Forest of Death, Ichiraku Ramen, Hokage Tower, Valley of the End, Akatsuki hideouts, The Chunin Exam Arena, Mount Myoboku",
    era: "Can be set in Naruto, Shippuden, Boruto, or pre-series eras",
    characters: [
      "Naruto Uzumaki",
      "Sasuke Uchiha",
      "Sakura Haruno",
      "Kakashi Hatake",
      "Itachi Uchiha",
      "Hinata Hyuuga",
      "Shikamaru Nara",
      "Gaara",
      "Minato Namikaze",
      "Jiraiya",
      "Obito Uchiha",
      "Madara Uchiha",
      "Tsunade",
      "Rock Lee",
      "Neji Hyuuga",
      "Ino Yamanaka",
      "Chouji Akimichi",
      "Tenten",
      "Temari",
      "Kankurou",
      "Orochimaru",
      "Kabuto Yakushi",
      "Yamato / Tenzou",
      "Sai",
      "Killer Bee",
      "Nagato / Pain",
      "Konan",
      "Deidara",
      "Sasori",
      "Kisame Hoshigaki",
      "Might Guy",
      "Kushina Uzumaki",
      "Hashirama Senju",
      "Tobirama Senju",
    ],
    settingPlaceholder: "e.g., Ichiraku Ramen at dusk, Team 7 celebrating after a mission",
  },
  {
    id: "attack-on-titan",
    name: "Attack on Titan",
    category: "anime",
    canonRules:
      "Respect the Titan mythology and its reveals — do not spoil casually but write consistently with the world's truths. Follow the military structure (Survey Corps, Garrison, Military Police). Use ODM gear correctly — it requires gas and anchoring surfaces. Titan Shifters have strict rules (13-year curse, inheritance). Maintain the dark, suspenseful, morally grey tone. Do not simplify the Marley-Paradis conflict.",
    locations:
      "Paradis Island, Wall Maria, Wall Rose, Wall Sina, Shiganshina, Trost, Marley, Liberio, The Paths",
    characters: [
      "Eren Yeager",
      "Mikasa Ackerman",
      "Armin Arlert",
      "Levi Ackerman",
      "Erwin Smith",
      "Hange Zoe",
      "Reiner Braun",
      "Annie Leonhart",
      "Jean Kirstein",
      "Sasha Blouse",
      "Connie Springer",
      "Historia Reiss",
      "Zeke Yeager",
      "Ymir",
      "Bertholdt Hoover",
      "Marco Bodt",
      "Pieck Finger",
      "Porco Galliard",
      "Falco Grice",
      "Gabi Braun",
      "Floch Forster",
      "Kenny Ackerman",
      "Petra Ral",
      "Mike Zacharias",
      "Moblit Berner",
      "Grisha Yeager",
      "Frieda Reiss",
      "Niccolo",
      "Yelena",
    ],
    settingPlaceholder: "e.g., Atop Wall Rose at dawn, the fog lifting over Titan territory",
  },
  {
    id: "haikyuu",
    name: "Haikyuu!!",
    category: "anime",
    canonRules:
      "Respect volleyball rules and terminology (sets, spikes, receives, libero, etc.). Follow the school tournament structure (Interhigh, Spring Tournament). Each team has distinct playstyles and strategies. Do not give characters superhuman abilities — their skills are grounded in training. Maintain the high-energy sports drama tone. Team dynamics and rivalries are central.",
    locations:
      "Karasuno High gym, Tokyo Metropolitan Gymnasium, Sendai City Gymnasium, Nekoma High, Aoba Johsai, Shiratorizawa, Training camps",
    characters: [
      "Hinata Shouyou",
      "Kageyama Tobio",
      "Tsukishima Kei",
      "Yamaguchi Tadashi",
      "Sugawara Koushi",
      "Oikawa Tooru",
      "Iwaizumi Hajime",
      "Kozume Kenma",
      "Kuroo Tetsurou",
      "Bokuto Koutarou",
      "Akaashi Keiji",
      "Ushijima Wakatoshi",
      "Miya Atsumu",
      "Sakusa Kiyoomi",
      "Sawamura Daichi",
      "Nishinoya Yuu",
      "Tanaka Ryuunosuke",
      "Shimizu Kiyoko",
      "Yachi Hitoka",
      "Asahi Azumane",
      "Ennoshita Chikara",
      "Miya Osamu",
      "Tendou Satori",
      "Semi Eita",
      "Hanamaki Takahiro",
      "Matsukawa Issei",
      "Kindaichi Yuutarou",
      "Kunimi Akira",
      "Kita Shinsuke",
      "Suna Rintarou",
      "Terushima Yuuji",
      "Hoshiumi Kourai",
    ],
    settingPlaceholder: "e.g., Karasuno gym during evening practice, the squeak of shoes on the court",
  },
  {
    id: "jujutsu-kaisen",
    name: "Jujutsu Kaisen",
    category: "anime",
    canonRules:
      "Respect cursed energy mechanics — cursed techniques are innate and unique per sorcerer. Domain Expansions have specific rules (sure-hit, binding vows). Follow the jujutsu sorcerer grading system (Special Grade, Grade 1-4). Cursed spirits are born from human fear. Do not ignore the consequences of using Reverse Cursed Technique. Maintain the intense, high-stakes action tone with dark humor.",
    locations:
      "Tokyo Jujutsu High, Kyoto Jujutsu High, Shibuya, The Prison Realm, Hidden Inventory locations, Culling Game colonies",
    characters: [
      "Itadori Yuuji",
      "Fushiguro Megumi",
      "Kugisaki Nobara",
      "Gojou Satoru",
      "Ryoumen Sukuna",
      "Nanami Kento",
      "Todou Aoi",
      "Inumaki Toge",
      "Zenin Maki",
      "Getou Suguru",
      "Okkotsu Yuuta",
      "Fushiguro Toji",
      "Choso",
      "Kamo Noritoshi",
      "Panda",
      "Miwa Kasumi",
      "Mechamaru / Kokichi Muta",
      "Zenin Mai",
      "Ieiri Shoko",
      "Yoshino Junpei",
      "Mahito",
      "Jougo",
      "Hanami",
      "Kenjaku",
      "Higuruma Hiromi",
      "Kashimo Hajime",
      "Yorozu",
      "Tsukumo Yuki",
      "Hakari Kinji",
    ],
    settingPlaceholder: "e.g., Tokyo Jujutsu High at midnight, cursed energy crackling in the air",
  },
  {
    id: "one-piece",
    name: "One Piece",
    category: "anime",
    canonRules:
      "Respect Devil Fruit rules — one fruit per person, seawater and Seastone nullify powers, no two people can have the same fruit simultaneously. Follow the Grand Line geography and pirate crew structure. Haki has three types (Observation, Armament, Conqueror's). Bounties reflect threat level, not strength alone. Maintain the adventurous, emotional tone that mixes comedy with deep drama.",
    locations:
      "Thousand Sunny, East Blue, Grand Line, New World, Wano, Marineford, Impel Down, Enies Lobby, Dressrosa, Whole Cake Island",
    era: "Can be set in any arc or timeline",
    characters: [
      "Monkey D. Luffy",
      "Roronoa Zoro",
      "Nami",
      "Sanji",
      "Tony Tony Chopper",
      "Nico Robin",
      "Trafalgar Law",
      "Portgas D. Ace",
      "Shanks",
      "Boa Hancock",
      "Sabo",
      "Yamato",
      "Jinbe",
      "Usopp",
      "Franky",
      "Brook",
      "Nefertari Vivi",
      "Crocodile",
      "Donquixote Doflamingo",
      "Katakuri",
      "Whitebeard / Edward Newgate",
      "Kaido",
      "Big Mom / Charlotte Linlin",
      "Buggy",
      "Dracule Mihawk",
      "Koby",
      "Smoker",
      "Eustass Kid",
      "Monkey D. Dragon",
      "Bartholomew Kuma",
    ],
    settingPlaceholder: "e.g., The Thousand Sunny's deck under a Grand Line sunset, land in sight",
  },
  {
    id: "demon-slayer",
    name: "Demon Slayer",
    category: "anime",
    canonRules:
      "Follow Breathing Styles and their specific forms — do not invent forms for existing styles without justification. Respect the Demon Slayer Corps hierarchy and the Hashira ranking system. Demons use Blood Demon Arts tied to their specific abilities. Nichirin blades change color based on the wielder. Maintain the Taisho-era Japanese setting (early 1900s). Blend intense action with emotional storytelling and family bonds.",
    locations:
      "Demon Slayer Corps HQ, Mt. Natagumo, Mugen Train, Entertainment District, Swordsmith Village, Infinity Castle, Butterfly Mansion",
    characters: [
      "Kamado Tanjirou",
      "Kamado Nezuko",
      "Agatsuma Zenitsu",
      "Hashibira Inosuke",
      "Tomioka Giyuu",
      "Kochou Shinobu",
      "Rengoku Kyoujurou",
      "Kibutsuji Muzan",
      "Uzui Tengen",
      "Kanroji Mitsuri",
      "Tokitou Muichirou",
      "Iguro Obanai",
      "Akaza",
      "Douma",
      "Shinazugawa Sanemi",
      "Himejima Gyoumei",
      "Kokushibou",
      "Tamayo",
      "Yushirou",
      "Kanao Tsuyuri",
      "Genya Shinazugawa",
      "Kochou Kanae",
      "Rui",
      "Gyuutarou",
      "Daki",
      "Hantengu",
      "Gyokko",
      "Nakime",
      "Enmu",
      "Ubuyashiki Kagaya",
    ],
    settingPlaceholder: "e.g., Butterfly Mansion garden at twilight, wisteria in bloom",
  },
  {
    id: "bungou-stray-dogs",
    name: "Bungou Stray Dogs",
    category: "anime",
    canonRules:
      "Each character's ability is named after a work by the real-world author they're based on — respect these connections. The Armed Detective Agency, Port Mafia, and Guild are distinct factions with different goals. Do not confuse ability names or attribute them to the wrong characters. Maintain the noir-action-comedy tone that shifts between dark drama and slapstick humor.",
    locations:
      "Armed Detective Agency office, Port Mafia headquarters, Yokohama, Café Uzumaki, The Guild's airship, Decay of Angels hideout, Meursault prison",
    characters: [
      "Dazai Osamu",
      "Nakahara Chuuya",
      "Nakajima Atsushi",
      "Akutagawa Ryuunosuke",
      "Fyodor Dostoevsky",
      "Edogawa Ranpo",
      "Kunikida Doppo",
      "Yosano Akiko",
      "Nikolai Gogol",
      "Sigma",
      "Lucy Maud Montgomery",
      "Mori Ougai",
      "Ozaki Kouyou",
      "Izumi Kyouka",
      "Tanizaki Junichirou",
      "Tanizaki Naomi",
      "Miyazawa Kenji",
      "Fukuzawa Yukichi",
      "Kajii Motojirou",
      "Hirotsu Ryuurou",
      "Tachihara Michizou",
      "Francis Scott Key Fitzgerald",
      "Nathaniel Hawthorne",
      "Margaret Mitchell",
      "Howard Phillips Lovecraft",
      "Oda Sakunosuke",
      "Ango Sakaguchi",
      "Bram Stoker",
    ],
    settingPlaceholder: "e.g., The Armed Detective Agency rooftop, Yokohama glittering below",
  },
  {
    id: "jojos-bizarre-adventure",
    name: "JoJo's Bizarre Adventure",
    category: "anime",
    canonRules:
      "Respect the Stand system — each Stand has specific abilities, stats (Power, Speed, Range, Persistence, Precision, Development), and limitations. Stands are visible only to other Stand users. Follow the rules of whichever Part you're writing (Hamon for Parts 1-2, Stands for Parts 3+). Maintain the dramatic, over-the-top, flamboyant tone. Battle strategy matters more than raw power.",
    locations:
      "Morioh, Cairo, Italy, Florida, Joestar Mansion, DIO's Mansion, Passione headquarters, Naples",
    era: "Specify which Part (1-8) and its era",
    characters: [
      "Jotaro Kujo",
      "Dio Brando / DIO",
      "Josuke Higashikata",
      "Giorno Giovanna",
      "Bruno Bucciarati",
      "Joseph Joestar",
      "Jolyne Cujoh",
      "Rohan Kishibe",
      "Kakyoin Noriaki",
      "Guido Mista",
      "Narancia Ghirga",
      "Yoshikage Kira",
      "Johnny Joestar",
      "Gyro Zeppeli",
      "Jonathan Joestar",
      "Caesar Anthonio Zeppeli",
      "Jean Pierre Polnareff",
      "Muhammad Avdol",
      "Leone Abbacchio",
      "Pannacotta Fugo",
      "Trish Una",
      "Ermes Costello",
      "Foo Fighters",
      "Weather Report",
      "Diavolo",
      "Doppio",
      "Iggy",
      "Koichi Hirose",
      "Okuyasu Nijimura",
    ],
    settingPlaceholder: "e.g., The streets of Morioh at dusk, a Stand user lurking nearby",
  },
  {
    id: "hetalia",
    name: "Hetalia",
    category: "anime",
    canonRules:
      "Characters are personifications of nations — their personalities reflect national stereotypes played for comedy. Respect the historical events being referenced (World Wars, alliances, cultural exchanges). Characters are immortal and age with their nation's history. Do not ignore the comedy — Hetalia is a satire. Use both human and nation names correctly.",
    locations:
      "World Meeting Hall, Various European capitals, America's house, England's house, Japan's house, Italy, Germany",
    characters: [
      "America / Alfred F. Jones",
      "England / Arthur Kirkland",
      "France / Francis Bonnefoy",
      "Russia / Ivan Braginsky",
      "China / Yao Wang",
      "Germany / Ludwig",
      "Italy Veneziano / Feliciano Vargas",
      "Japan / Kiku Honda",
      "Prussia / Gilbert Beilschmidt",
      "Canada / Matthew Williams",
      "Spain / Antonio Fernandez Carriedo",
      "Romano / Lovino Vargas",
      "Austria / Roderich Edelstein",
      "Hungary / Elizabeta Héderváry",
      "Switzerland / Basch Zwingli",
      "Liechtenstein / Erika",
      "Denmark / Mathias Køhler",
      "Norway / Lukas Bondevik",
      "Iceland / Emil Steilsson",
      "Sweden / Berwald Oxenstierna",
      "Finland / Tino Väinämöinen",
      "Poland / Feliks Łukasiewicz",
      "Lithuania / Toris Laurinaitis",
      "Greece / Heracles Karpusi",
      "Turkey / Sadik Adnan",
      "Belarus / Natalia Arlovskaya",
      "Ukraine / Katyusha",
      "Hong Kong / Leon",
      "Taiwan / Mei",
      "South Korea / Yong Soo Im",
    ],
    settingPlaceholder: "e.g., A chaotic World Meeting, papers flying and alliances shifting",
  },
  {
    id: "yuri-on-ice",
    name: "Yuri!!! on Ice",
    category: "anime",
    canonRules:
      "Respect figure skating terminology and competition structure (Grand Prix Series, Grand Prix Final, Worlds). Programs have technical elements (jumps, spins, step sequences) with specific names. Do not confuse the two Yuris (Katsuki Yuuri and Yuri Plisetsky). The relationship between Yuuri and Victor is central and canon. Maintain the warm, passionate tone about pursuing excellence in sport and love.",
    locations:
      "Hasetsu Ice Castle, St. Petersburg, Barcelona (Grand Prix Final), Various competition venues, Yu-topia (onsen), The ice rink",
    characters: [
      "Katsuki Yuuri",
      "Victor Nikiforov",
      "Yuri Plisetsky",
      "Phichit Chulanont",
      "Christophe Giacometti",
      "Otabek Altin",
      "Minami Kenjirou",
      "Mila Babicheva",
      "Yakov Feltsman",
      "Mari Katsuki",
      "Georgi Popovich",
      "Jean-Jacques Leroy",
      "Isabella Yang",
      "Hiroko Katsuki",
      "Toshiya Katsuki",
      "Lilia Baranovskaya",
      "Leo de la Iglesia",
      "Guang-Hong Ji",
      "Seung-Gil Lee",
      "Michele Crispino",
      "Sara Crispino",
      "Emil Nekola",
      "Celestino Cialdini",
    ],
    settingPlaceholder: "e.g., The Hasetsu Ice Castle, early morning practice before dawn",
  },
  {
    id: "fullmetal-alchemist",
    name: "Fullmetal Alchemist",
    category: "anime",
    canonRules:
      "Alchemy follows the law of Equivalent Exchange — you cannot create something from nothing. Human transmutation is the ultimate taboo with devastating consequences (Truth takes a toll). Respect the military hierarchy of Amestris. The Homunculi are named after the Seven Deadly Sins. Do not confuse the 2003 anime and Brotherhood/manga continuities. Maintain the blend of action, political intrigue, and philosophical themes.",
    locations:
      "Central City, Resembool, Briggs Fortress, Ishval, Xerxes ruins, Laboratory 5, Rush Valley, The Gate of Truth",
    characters: [
      "Edward Elric",
      "Alphonse Elric",
      "Roy Mustang",
      "Riza Hawkeye",
      "Winry Rockbell",
      "Ling Yao / Greed",
      "Scar",
      "Olivier Mira Armstrong",
      "Maes Hughes",
      "Envy",
      "Lust",
      "King Bradley / Wrath",
      "Van Hohenheim",
      "Alex Louis Armstrong",
      "Jean Havoc",
      "Kain Fuery",
      "Vato Falman",
      "Heymans Breda",
      "Izumi Curtis",
      "Lan Fan",
      "May Chang",
      "Gluttony",
      "Sloth",
      "Pride / Selim Bradley",
      "Father",
      "Gracia Hughes",
      "Maria Ross",
      "Tim Marcoh",
      "Trisha Elric",
      "Rose Thomas",
    ],
    settingPlaceholder: "e.g., Roy Mustang's office in Central Command, rain on the windows",
  },
  {
    id: "mob-psycho-100",
    name: "Mob Psycho 100",
    category: "anime",
    canonRules:
      "Mob (Shigeo Kageyama) suppresses his emotions to control his immense psychic powers — when his emotional meter hits 100%, he explodes. Reigen is a con artist, not a real psychic. Do not make psychic powers a substitute for personal growth — the show's core message is that powers don't make you special. Maintain the blend of comedy, action, and surprisingly deep emotional themes.",
    locations:
      "Seasoning City, Salt Middle School, Spirits and Such Consultation Office, The Awakening Lab, Claw's headquarters",
    characters: [
      "Mob / Kageyama Shigeo",
      "Reigen Arataka",
      "Kageyama Ritsu",
      "Dimple / Ekubo",
      "Hanazawa Teruki",
      "Suzuki Shou",
      "Kurata Tome",
      "Serizawa Katsuya",
      "Suzuki Touichirou",
      "Mezato Ichi",
      "Kageyama Touichirou",
      "Shimazaki Ryou",
      "Minegishi",
      "Shibata",
      "Ishiguro",
      "Mogami Keiji",
      "Musashi Gouda",
      "Onigawara Tenga",
      "Tsubomi Takane",
      "Tokugawa",
    ],
    settingPlaceholder: "e.g., Spirits and Such office, Reigen assigning another dubious case",
  },
  {
    id: "hunter-x-hunter",
    name: "Hunter x Hunter",
    category: "anime",
    canonRules:
      "Nen has strict rules — the six categories (Enhancement, Emission, Transmutation, Conjuration, Manipulation, Specialization) determine abilities. Nen conditions and vows power up abilities at a cost. The Hunter License grants extraordinary privileges. Do not make Nen abilities without clear conditions and limitations. Maintain the tonal range from adventure to extremely dark psychological thriller.",
    locations:
      "Whale Island, Heavens Arena, Yorknew City, Greed Island, NGL / East Gorteau, The Dark Continent, Zoldyck Estate, Hunter Association HQ",
    characters: [
      "Gon Freecss",
      "Killua Zoldyck",
      "Kurapika",
      "Leorio Paradinight",
      "Hisoka Morow",
      "Chrollo Lucilfer",
      "Illumi Zoldyck",
      "Meruem",
      "Neferpitou",
      "Komugi",
      "Kite",
      "Bisky / Biscuit Krueger",
      "Ging Freecss",
      "Feitan Portor",
      "Machi Komacine",
      "Shalnark",
      "Pakunoda",
      "Nobunaga Hazama",
      "Phinks Magcub",
      "Shaiapouf",
      "Menthuthuyoupi",
      "Palm Siberia",
      "Knuckle Bine",
      "Shoot McMahon",
      "Alluka Zoldyck",
      "Zeno Zoldyck",
      "Silva Zoldyck",
      "Kalluto Zoldyck",
      "Netero Isaac",
      "Knov",
      "Morel Mackernasey",
    ],
    settingPlaceholder: "e.g., Heavens Arena, the tension before a Nen battle on the 200th floor",
  },
  {
    id: "bleach",
    name: "Bleach",
    category: "anime",
    canonRules:
      "Respect the Soul Reaper power system — Zanpakuto have Shikai and Bankai releases with unique abilities per wielder. Hollows, Arrancars, and Quincy each have distinct power systems. Follow the Gotei 13 squad structure and captain hierarchy. Spiritual pressure (Reiatsu) determines combat capability. Do not mix up the abilities of different Zanpakuto. Maintain the stylish, high-powered action tone.",
    locations:
      "Karakura Town, Soul Society / Seireitei, Hueco Mundo, Las Noches, Wandenreich, The Royal Palace, Urahara's Shop",
    characters: [
      "Kurosaki Ichigo",
      "Kuchiki Rukia",
      "Abarai Renji",
      "Kuchiki Byakuya",
      "Hitsugaya Toushirou",
      "Grimmjow Jaegerjaquez",
      "Ulquiorra Cifer",
      "Inoue Orihime",
      "Urahara Kisuke",
      "Aizen Sousuke",
      "Ishida Uryuu",
      "Zaraki Kenpachi",
      "Shihouin Yoruichi",
      "Yasutora Sado / Chad",
      "Matsumoto Rangiku",
      "Hinamori Momo",
      "Kyouraku Shunsui",
      "Ukitake Juushirou",
      "Gin Ichimaru",
      "Kaname Tousen",
      "Soi Fon",
      "Unohana Retsu",
      "Kurotsuchi Mayuri",
      "Nelliel Tu Odelschwanck",
      "Szayel Aporro Granz",
      "Tier Harribel",
      "Coyote Starrk",
      "Kurosaki Isshin",
      "Haschwalth Jugram",
      "Yhwach",
    ],
    settingPlaceholder: "e.g., The rooftops of Seireitei, Zanpakuto drawn under a crescent moon",
  },
  {
    id: "death-note",
    name: "Death Note",
    category: "anime",
    canonRules:
      "The Death Note's rules are absolute — write a name while picturing the face, and that person dies. Eyes of a Shinigami halve your remaining lifespan. Respect the cat-and-mouse intellectual dynamic between Light and L. Do not simplify the moral complexity — Light is both protagonist and villain. Maintain the tense, psychological thriller tone.",
    locations:
      "Light's bedroom, L's investigation headquarters, To-Oh University, Kira Task Force HQ, The Shinigami Realm, Wammy's House",
    characters: [
      "Yagami Light",
      "L Lawliet",
      "Amane Misa",
      "Ryuk",
      "Near / Nate River",
      "Mello / Mihael Keehl",
      "Rem",
      "Yagami Souichirou",
      "Matsuda Touta",
      "Mikami Teru",
      "Watari / Quillsh Wammy",
      "Takada Kiyomi",
      "Naomi Misora",
      "Raye Penber",
      "Mogi Kanzo",
      "Aizawa Shuuichi",
      "Sayu Yagami",
      "Yagami Sachiko",
      "Matt / Mail Jeevas",
      "Sidoh",
    ],
    settingPlaceholder: "e.g., L's darkened investigation room, screens glowing, the game of wits intensifying",
  },
  {
    id: "blue-lock",
    name: "Blue Lock",
    category: "anime",
    canonRules:
      "Blue Lock is a ruthless striker training program designed to create Japan's best striker through elimination. Respect the ego-driven philosophy — selfishness is strength here, not a flaw. Each player has a unique weapon or play style. Follow soccer/football rules and terminology. Do not make it a team-bonding story — Blue Lock is about individual brilliance clashing. Maintain the intense, almost battle-manga approach to sports.",
    locations:
      "Blue Lock facility, The various stages/fields, The Blue Lock dormitory, The stadium, Training grounds",
    characters: [
      "Isagi Yoichi",
      "Bachira Meguru",
      "Itoshi Rin",
      "Nagi Seishirou",
      "Chigiri Hyouma",
      "Mikage Reo",
      "Itoshi Sae",
      "Shidou Ryuusei",
      "Michael Kaiser",
      "Kunigami Rensuke",
      "Barou Shouei",
      "Ego Jinpachi",
      "Gagamaru Gin",
      "Raichi Jingo",
      "Tokimitsu Aoshi",
      "Otoya Eita",
      "Karasu Tabito",
      "Yukimiya Kenyu",
      "Hiori Yo",
      "Nanase Rensuke",
      "Kurona",
      "Aryu Jyubei",
      "Alexis Ness",
      "Anri Teieri",
    ],
    settingPlaceholder: "e.g., The Blue Lock pitch, floodlights blazing over a sudden-death match",
  },
  {
    id: "tokyo-revengers",
    name: "Tokyo Revengers",
    category: "anime",
    canonRules:
      "Time travel operates through specific handshake triggers and can only go back 12 years. Respect the gang hierarchy and structure of Tokyo Manji Gang (Toman) and rival gangs. Delinquent culture is central — fights are fists, not weapons (mostly). Do not ignore the butterfly effect of timeline changes. Maintain the blend of delinquent drama, tragedy, and desperate hope.",
    locations:
      "Shibuya, Musashi Shrine, Toman meeting spots, Various Tokyo streets, Valhalla, Tenjiku territory, Schools",
    characters: [
      "Hanagaki Takemichi",
      "Sano Manjirou / Mikey",
      "Ryuuguji Ken / Draken",
      "Baji Keisuke",
      "Matsuno Chifuyu",
      "Hanemiya Kazutora",
      "Tachibana Hinata",
      "Tachibana Naoto",
      "Kisaki Tetta",
      "Mitsuya Takashi",
      "Kurokawa Izana",
      "Kawaragi Senju",
      "Hanma Shuuji",
      "Shiba Hakkai",
      "Kawata Souya (Angry)",
      "Kawata Nahoya (Smiley)",
      "Sanzu Haruchiyo",
      "Kokonoi Hajime (Koko)",
      "Inui Seishu",
      "Haitani Ran",
      "Haitani Rindou",
      "Kakuchou",
      "Sano Shinichiro",
      "Sano Emma",
      "Wakasa Imaushi",
      "Takeomi Akashi",
    ],
    settingPlaceholder: "e.g., Musashi Shrine at night, Toman assembled under the summer stars",
  },
  {
    id: "fairy-tail",
    name: "Fairy Tail",
    category: "anime",
    canonRules:
      "Respect the magic system — each mage specializes in a specific type of magic. Guild structure and rankings (S-Class, regular, etc.) matter. Fairy Tail is about nakama (bonds/friendship) as a literal power source. Do not ignore that Dragon Slayers get motion sickness. Maintain the fun, adventurous tone with emotional guild-family moments. Exceed is a specific race — not just cats.",
    locations:
      "Fairy Tail Guild Hall, Magnolia, The Grand Magic Games arena, Tenrou Island, Tower of Heaven, Alvarez Empire, Edolas",
    characters: [
      "Natsu Dragneel",
      "Lucy Heartfilia",
      "Gray Fullbuster",
      "Erza Scarlet",
      "Happy",
      "Wendy Marvell",
      "Gajeel Redfox",
      "Juvia Lockser",
      "Laxus Dreyar",
      "Jellal Fernandes",
      "Levy McGarden",
      "Mirajane Strauss",
      "Makarov Dreyar",
      "Cana Alberona",
      "Lisanna Strauss",
      "Elfman Strauss",
      "Freed Justine",
      "Bickslow",
      "Evergreen",
      "Carla / Charle",
      "Pantherlily",
      "Zeref Dragneel",
      "Mavis Vermillion",
      "Sting Eucliffe",
      "Rogue Cheney",
      "Minerva Orland",
      "Ultear Milkovich",
      "Meredy",
      "Kagura Mikazuchi",
    ],
    settingPlaceholder: "e.g., The Fairy Tail guild hall, a brawl breaking out over drinks",
  },
  {
    id: "detective-conan",
    name: "Detective Conan",
    category: "anime",
    canonRules:
      "Shinichi Kudo was shrunk to a child's body by APTX 4869 and lives as Conan Edogawa. His identity must remain secret from most characters. Respect the mystery structure — cases should have solvable clues. The Black Organization is the overarching threat. Do not reveal Conan's identity to characters who don't know in canon. Maintain the detective procedural tone with moments of humor and romance tension.",
    locations:
      "Beika City, Professor Agasa's house, Mouri Detective Agency, Teitan Elementary, Tropical Land, Various crime scenes",
    characters: [
      "Edogawa Conan / Kudou Shinichi",
      "Mouri Ran",
      "Haibara Ai / Miyano Shiho",
      "Hattori Heiji",
      "Kaitou Kid / Kuroba Kaito",
      "Mouri Kogorou",
      "Akai Shuuichi",
      "Furuya Rei / Bourbon / Amuro Tooru",
      "Toyama Kazuha",
      "Suzuki Sonoko",
      "Agasa Hiroshi",
      "Yoshida Ayumi",
      "Tsuburaya Mitsuhiko",
      "Kojima Genta",
      "Hondou Eisuke",
      "Jodie Starling",
      "Vermouth / Sharon Vineyard",
      "Gin",
      "Vodka",
      "Miyano Akemi",
      "Sera Masumi",
      "Okiya Subaru",
      "Wakita Kanenori / Rum",
      "Makoto Kyogoku",
    ],
    settingPlaceholder: "e.g., A locked-room mystery at a mountaintop villa, snowstorm raging outside",
  },
  {
    id: "slam-dunk",
    name: "Slam Dunk",
    category: "anime",
    canonRules:
      "Respect basketball rules and terminology. Shohoku is an underdog team rebuilding its legacy. Sakuragi is a raw beginner — do not make him instantly skilled. Each rival school has a distinct playstyle and ace player. Maintain the grounded sports drama tone with comedy. Character growth through training and competition is the core appeal.",
    locations:
      "Shohoku High School gym, Kanagawa Prefecture tournament venues, The beach training camp, Various rival school gyms",
    characters: [
      "Sakuragi Hanamichi",
      "Rukawa Kaede",
      "Akagi Takenori",
      "Mitsui Hisashi",
      "Miyagi Ryota",
      "Ayako",
      "Haruko Akagi",
      "Sendoh Akira",
      "Maki Shinichi",
      "Sawakita Eiji",
      "Coach Anzai",
      "Kogure Kiminobu",
      "Yasuda Yasuharu",
      "Fujima Kenji",
      "Hanagata Toru",
      "Jin Soichiro",
      "Fukuda Kichou",
      "Uozumi Jun",
      "Ikegami Ryoji",
      "Hikoichi Aida",
    ],
    settingPlaceholder: "e.g., Shohoku gym at sunset, the sound of a basketball echoing off the walls",
  },
  {
    id: "sk8-the-infinity",
    name: "SK8 the Infinity",
    category: "anime",
    canonRules:
      "S is an illegal underground skateboarding race held in an abandoned mine. Each skater has a unique style and customized board. Respect skateboarding culture and terminology. Langa is a snowboarder adapting to skating. Do not make the races purely realistic — S races are theatrical and over-the-top. Maintain the vibrant, high-energy tone with strong emotional bonds between characters.",
    locations:
      "S (the abandoned mine race course), The skate shop, Okinawa streets, School, Various skateparks, The starting line",
    characters: [
      "Hasegawa Langa",
      "Kyan Reki",
      "Chinen Miya",
      "Joe / Nanjou Kojirou",
      "Cherry Blossom / Sakurayashiki Kaoru",
      "Shadow / Higa Hiromi",
      "Adam / Shindou Ainosuke",
      "Kikuchi Tadashi",
      "Oka (Manager)",
      "Hasegawa Nanako (Langa's mother)",
      "Sia La Luce",
      "Carla (Cherry's AI)",
      "Sketchy (S Announcer)",
    ],
    settingPlaceholder: "e.g., The S mine course at midnight, neon lights and roaring crowds",
  },
  {
    id: "inuyasha",
    name: "InuYasha",
    category: "anime",
    canonRules:
      "The Bone Eater's Well connects modern Tokyo to the Sengoku (feudal) era. InuYasha is a half-demon — respect the prejudice he faces from both humans and demons. The Shikon Jewel shards are the central MacGuffin. Kagome's spiritual powers are distinct from priestess Kikyo's. Do not ignore the era-appropriate setting — feudal Japan with yokai. Maintain the adventure-romance tone.",
    locations:
      "Feudal Japan, Kaede's Village, The Bone Eater's Well, Modern Tokyo, Naraku's Castle, Sesshomaru's domain, Mt. Hakurei",
    era: "Primarily Sengoku era with modern-day Tokyo connections",
    characters: [
      "InuYasha",
      "Higurashi Kagome",
      "Sesshoumaru",
      "Miroku",
      "Sango",
      "Shippou",
      "Naraku",
      "Kikyou",
      "Rin",
      "Kouga",
      "Kagura",
      "Kanna",
      "Jaken",
      "Kaede",
      "Kohaku",
      "Myouga",
      "Kirara",
      "Bankotsu",
      "Jakotsu",
      "Ayame",
      "Totosai",
    ],
    settingPlaceholder: "e.g., A moonlit forest clearing in the Sengoku era, fireflies drifting",
  },
  {
    id: "dragon-ball",
    name: "Dragon Ball",
    category: "anime",
    canonRules:
      "Respect the power scaling and transformation system (Super Saiyan forms, Ultra Instinct, etc.). The Dragon Balls grant wishes but have specific limitations per set (Earth, Namekian, Super Dragon Balls). Saiyans get stronger after near-death (Zenkai boost). Ki is the power system. Do not ignore established power levels without justification. Maintain the blend of epic battles, humor, and found family.",
    locations:
      "Capsule Corp, Kame House, Planet Namek, Hyperbolic Time Chamber, Tournament of Power arena, King Kai's Planet, Beerus's Planet",
    era: "Can be set in Dragon Ball, Z, Super, or GT",
    characters: [
      "Son Goku",
      "Vegeta",
      "Son Gohan",
      "Piccolo",
      "Bulma",
      "Trunks",
      "Frieza",
      "Krillin",
      "Android 18 / Lazuli",
      "Son Goten",
      "Beerus",
      "Whis",
      "Chi-Chi",
      "Cell",
      "Android 17 / Lapis",
      "Videl",
      "Future Trunks",
      "Yamcha",
      "Tien Shinhan",
      "Majin Buu",
      "Mr. Satan / Hercule",
      "Broly",
      "Bardock",
      "Raditz",
      "Gogeta",
      "Vegito",
      "Hit",
      "Jiren",
      "Pan",
    ],
    settingPlaceholder: "e.g., The Hyperbolic Time Chamber, one year compressed into a day of training",
  },
  {
    id: "sailor-moon",
    name: "Sailor Moon",
    category: "anime",
    canonRules:
      "Each Sailor Guardian is linked to a planet and has themed attacks. Usagi is the reincarnation of Princess Serenity. The Silver Crystal is immensely powerful but drains the user. Respect the transformation sequences and attack naming conventions. Do not ignore the Sailor Guardians' civilian identities and friendships. Maintain the magical girl tone that balances lighthearted comedy with cosmic-scale drama and romance.",
    locations:
      "Juban District (Tokyo), Crown Arcade, The Moon Kingdom, Crystal Tokyo, The Dark Kingdom, Mugen Academy, Galaxia's domain",
    characters: [
      "Tsukino Usagi / Sailor Moon",
      "Chiba Mamoru / Tuxedo Mask",
      "Mizuno Ami / Sailor Mercury",
      "Hino Rei / Sailor Mars",
      "Kino Makoto / Sailor Jupiter",
      "Aino Minako / Sailor Venus",
      "Tenoh Haruka / Sailor Uranus",
      "Kaioh Michiru / Sailor Neptune",
      "Meioh Setsuna / Sailor Pluto",
      "Tomoe Hotaru / Sailor Saturn",
      "Chibiusa / Sailor Chibi Moon",
      "Seiya Kou / Sailor Star Fighter",
      "Taiki Kou / Sailor Star Maker",
      "Yaten Kou / Sailor Star Healer",
      "Luna",
      "Artemis",
      "Diana",
      "Naru Osaka",
      "Umino Gurio",
      "Queen Beryl",
      "Kunzite",
      "Nephrite",
      "Zoisite",
      "Jadeite",
      "Prince Demande",
      "Sailor Galaxia",
    ],
    settingPlaceholder: "e.g., The Crown Arcade after school, milkshakes and whispered Guardian secrets",
  },
  {
    id: "gintama",
    name: "Gintama",
    category: "anime",
    canonRules:
      "Set in an Edo-period Japan invaded by aliens (Amanto). Samurai are banned from carrying swords. Gintoki runs the Yorozuya (odd-jobs shop). Respect the show's trademark fourth-wall-breaking humor and anime/manga parodies. Serious arcs (Benizakura, Shogun Assassination, etc.) are genuinely dramatic — do not undercut them with jokes. The comedy-to-drama tonal shifts are intentional and earned.",
    locations:
      "Yorozuya office (Kabukicho), Shinsengumi HQ, Edo streets, Yoshiwara, Terminal, Various planets, Shoyo's school",
    characters: [
      "Sakata Gintoki",
      "Shimura Shinpachi",
      "Kagura",
      "Hijikata Toushirou",
      "Okita Sougo",
      "Kondou Isao",
      "Takasugi Shinsuke",
      "Katsura Kotarou",
      "Kamui",
      "Tsukuyo",
      "Sadaharu",
      "Hasegawa Taizou / Madao",
      "Shimura Tae / Otae",
      "Sarutobi Ayame / Sa-chan",
      "Yoshida Shouyou",
      "Yamazaki Sagaru",
      "Imai Nobume",
      "Tokugawa Shige Shige",
      "Sakamoto Tatsuma",
      "Mutsu",
      "Oboro",
      "Utsuro",
      "Otose",
      "Elizabeth",
      "Abuto",
    ],
    settingPlaceholder: "e.g., The Yorozuya office, Gintoki reading Jump while Shinpachi yells about rent",
  },
  {
    id: "kurokos-basketball",
    name: "Kuroko's Basketball",
    category: "anime",
    canonRules:
      "Respect basketball rules and the Generation of Miracles' individual abilities (each has a unique superhuman skill). Kuroko's misdirection is his only weapon — he has almost no physical ability. Seirin is an underdog team. Do not make abilities completely unrealistic, but the show does push basketball to anime extremes. The Zone is a real heightened state with specific triggers. Maintain the intense sports rivalry tone.",
    locations:
      "Seirin High School, Winter Cup venues, Street basketball courts, Various rival school gyms, Training camps",
    characters: [
      "Kuroko Tetsuya",
      "Kagami Taiga",
      "Aomine Daiki",
      "Kise Ryouta",
      "Midorima Shintarou",
      "Murasakibara Atsushi",
      "Akashi Seijuurou",
      "Momoi Satsuki",
      "Hyuuga Junpei",
      "Aida Riko",
      "Takao Kazunari",
      "Himuro Tatsuya",
      "Izuki Shun",
      "Kiyoshi Teppei",
      "Koganei Shinji",
      "Mitobe Rinnosuke",
      "Tsuchida Satoshi",
      "Kasamatsu Yukio",
      "Imayoshi Shouichi",
      "Wakamatsu Kousuke",
      "Sakurai Ryou",
      "Hanamiya Makoto",
      "Mibuchi Reo",
      "Hayama Kotarou",
      "Nebuya Eikichi",
      "Nijimura Shuuzou",
      "Haizaki Shougo",
      "Ogiwara Shigehiro",
      "Alexandra Garcia",
    ],
    settingPlaceholder: "e.g., The Winter Cup court, the buzzer about to sound in a tied game",
  },
  {
    id: "free",
    name: "Free!",
    category: "anime",
    canonRules:
      "Respect competitive swimming rules, strokes, and terminology. Each character has a signature stroke (Haru: freestyle, Rin: butterfly, Makoto: backstroke, etc.). Relay events are about teamwork and trust. Do not ignore Haru's almost spiritual connection to water. Maintain the blend of sports competition, friendship drama, and emotional character development. The rivalry between Iwatobi and Samezuka drives the story.",
    locations:
      "Iwatobi Swim Club, Samezuka Academy pool, Prefectural tournament venues, The ocean, Various pools and training facilities, Australia",
    characters: [
      "Nanase Haruka",
      "Matsuoka Rin",
      "Tachibana Makoto",
      "Hazuki Nagisa",
      "Ryuugazaki Rei",
      "Yamazaki Sousuke",
      "Nitori Aiichirou",
      "Shigino Kisumi",
      "Kirishima Ikuya",
      "Shiina Asahi",
      "Matsuoka Gou",
      "Mikoshiba Seijuurou",
      "Mikoshiba Momotarou",
      "Amakata Miho",
      "Sasabe Goro",
      "Kirishima Natsuya",
      "Tono Hiyori",
      "Minami (Albert)",
      "Ryuuji",
      "Kaede",
    ],
    settingPlaceholder: "e.g., The Iwatobi pool at dusk, Haru floating motionless in the water",
  },
  {
    id: "ace-of-diamond",
    name: "Ace of Diamond",
    category: "anime",
    canonRules:
      "Respect baseball rules, positions, and terminology (pitching counts, batting order, innings structure). Seidou is a powerhouse high school aiming for Koshien. Each pitcher has distinct pitch types and styles. Do not ignore the mental game — baseball is as psychological as physical. Maintain the competitive sports drama tone with team dynamics and individual growth.",
    locations:
      "Seidou High School, The bullpen, Jingu Stadium, Koshien, Various opponent school fields, The dormitory",
    characters: [
      "Sawamura Eijun",
      "Furuya Satoru",
      "Miyuki Kazuya",
      "Kominato Haruichi",
      "Kuramochi Youichi",
      "Takigawa Chris Yuu",
      "Kominato Ryousuke",
      "Narumiya Mei",
      "Isashiki Jun",
      "Yuuki Tetsuya",
      "Coach Kataoka Tesshin",
      "Kawakami Norifumi",
      "Shirasu Kenjirou",
      "Okumura Koushuu",
      "Seto Takuma",
      "Tanba Kouichirou",
      "Masuko Tooru",
      "Harada Masatoshi",
      "Sanada Shunpei",
      "Raizou Todoroki",
      "Hongou Masamune",
    ],
    settingPlaceholder: "e.g., Seidou's bullpen at dawn, the crack of a pitch hitting the catcher's mitt",
  },
  {
    id: "black-butler",
    name: "Black Butler",
    category: "anime",
    canonRules:
      "Ciel Phantomhive has a Faustian contract with the demon Sebastian — Sebastian serves perfectly in exchange for Ciel's soul. Respect Victorian-era England setting and customs. The Phantomhive family serves as the Queen's Watchdog, handling the underworld. Do not make Sebastian fail at tasks he should handle effortlessly — he is 'one hell of a butler.' Maintain the gothic, darkly comedic tone with genuine horror elements.",
    locations:
      "Phantomhive Manor, London, The Undertaker's shop, The Funtom Company, Weston College, The Campania, Noah's Ark Circus",
    era: "Victorian-era England (late 1800s)",
    characters: [
      "Ciel Phantomhive",
      "Sebastian Michaelis",
      "Grell Sutcliff",
      "The Undertaker",
      "Elizabeth Midford",
      "Baldroy",
      "Mey-Rin",
      "Finnian",
      "Soma Asman Kadar",
      "Agni",
      "Alois Trancy",
      "Claude Faustus",
      "William T. Spears",
      "Ronald Knox",
      "Tanaka",
      "Snake",
      "Lau",
      "Ran-Mao",
      "Joker",
      "Doll",
      "Beast",
      "Dagger",
      "Vincent Phantomhive",
      "Rachel Phantomhive",
      "Frances Midford",
      "Edward Midford",
      "Real Ciel Phantomhive",
      "Sieglinde Sullivan",
      "Wolfram Gelzer",
      "Hannah Annafellows",
    ],
    settingPlaceholder: "e.g., Phantomhive Manor's candlelit study, Sebastian pouring tea at midnight",
  },
];
