import type { FandomConfig } from "../../types/fandom.ts";

export const ASIAN_MEDIA_FANDOMS: FandomConfig[] = [
  {
    id: "mdzs",
    name: "Mo Dao Zu Shi / The Untamed",
    category: "asian-media",
    canonRules:
      "Follow the cultivation world rules. Cultivators use spiritual energy channeled through golden cores. Resentful energy (demonic cultivation) is Wei Wuxian's forbidden path — it bypasses the golden core but at great cost. Sects have distinct cultivation methods, hierarchies, and territories. Courtesy names (zi) are used by peers and elders; birth names are intimate. The Yiling Patriarch's reputation is central to the conflict. Respect the Sunshot Campaign timeline, the Siege of the Burial Mounds, and the mystery structure of the present-day arc.",
    locations:
      "Cloud Recesses (Gusu Lan Sect), Lotus Pier (Yunmeng Jiang Sect), Koi Tower (Lanling Jin Sect), The Unclean Realm (Qinghe Nie Sect), The Burial Mounds, Nightless City (Qishan Wen Sect), Yi City, Mo Village",
    era: "Can be set during the Sunshot Campaign, the pre-siege era, or the present-day (post-resurrection) timeline",
    characters: [
      "Wei Wuxian / Wei Ying",
      "Lan Wangji / Lan Zhan",
      "Jiang Cheng / Jiang Wanyin",
      "Lan Xichen / Lan Huan",
      "Nie Huaisang",
      "Nie Mingjue",
      "Jin Guangyao / Meng Yao",
      "Wen Ning / Wen Qionglin",
      "Wen Qing",
      "Jin Zixuan",
      "Jiang Yanli",
      "Jin Ling / Jin Rulan",
      "Lan Sizhui / Lan Yuan",
      "Lan Jingyi",
      "Ouyang Zizhen",
      "Jin Guangshan",
      "Wen Ruohan",
      "Xiao Xingchen",
      "Song Lan / Song Zichen",
      "Xue Yang",
      "A-Qing",
      "Wen Chao",
      "Wang Lingjiao",
      "Madam Yu / Yu Ziyuan",
      "Jiang Fengmian",
      "Lan Qiren",
      "Mo Xuanyu",
      "Jin Zixun",
      "Wen Zhuliu / Core-Melting Hand",
      "Mianmian / Luo Qingyang",
      "Su She / Su Minshan",
    ],
    settingPlaceholder: "e.g., The back mountains of Cloud Recesses, cold spring under moonlight",
  },
  {
    id: "tgcf",
    name: "Heaven Official's Blessing / Tian Guan Ci Fu",
    category: "asian-media",
    canonRules:
      "Follow the heavenly official system. Gods ascend through mortal merit and worship; they can be banished for failures. Xie Lian ascended three times — an unprecedented feat born of suffering. Ghost Kings are supreme ghosts who achieved power through resentment. Hua Cheng (Crimson Rain Sought Flower) is the most powerful Ghost King and has devoted himself to Xie Lian for 800 years. Spiritual power, curses, and arrays follow established rules. Respect the three realms: Heaven, the mortal world, and the Ghost Realm.",
    locations:
      "The Heavenly Court, Puqi Shrine, Ghost City, Paradise Manor, Mount Taicang, Ban Yue Pass, Tonglu Mountain, Xianle (ancient kingdom), the mortal world",
    era: "Can be set during Xie Lian's first ascension, second ascension, exile years, or post-third ascension (present day)",
    characters: [
      "Xie Lian",
      "Hua Cheng / San Lang",
      "Mu Qing",
      "Feng Xin",
      "Shi Qingxuan",
      "He Xuan / Black Water",
      "Pei Ming",
      "Ling Wen",
      "Quan Yizhen",
      "Yin Yu",
      "Banyue",
      "Ke Mo",
      "Jun Wu / White No-Face",
      "Guoshi / National Advisor",
      "Lang Qianqiu",
      "Qi Rong / Night-Touring Green Lantern",
      "Pei Su",
      "Mei Nianqing",
      "Rong Guang",
      "Yushi Huang / Lady Wind Master",
      "E-Ming (Hua Cheng's scimitar)",
      "Ruoye (Xie Lian's silk band)",
      "He Xuan's original form",
      "General Pei Jr. / Pei Xiu",
    ],
    settingPlaceholder: "e.g., Puqi Shrine on a rainy night, a silver butterfly flickering in the dark",
  },
  {
    id: "word-of-honor",
    name: "Word of Honor / Shan He Ling",
    category: "asian-media",
    canonRules:
      "Follow the jianghu (martial world) rules. Zhou Zishu is the former leader of Tian Chuang (Window of Heaven), a royal spy organization, who placed the Seven Nails of Torment in his own body to leave. Wen Kexing is the Ghost Valley Master seeking revenge for the massacre of his parents. The Five Lakes Alliance and the political intrigue of the martial world drive the plot. Respect the wuxia conventions: martial arts sects, internal energy cultivation, poison arts, and codes of honor. The central romance is between Zhou Zishu and Wen Kexing.",
    locations:
      "Ghost Valley, Mount Qingya, Sanbai Manor, The Four Seasons Manor, Mirror Lake, Yueyang Sect, Tai Lake, various jianghu locales",
    characters: [
      "Zhou Zishu",
      "Wen Kexing",
      "Gu Xiang",
      "Cao Weining",
      "Zhang Chengling",
      "Ye Baiyi",
      "Xie'er / Scorpion King",
      "Zhao Jing",
      "Duan Pengju",
      "Prince Jin",
      "Mo Huaiyang",
      "Gao Chong",
      "Han Ying",
      "Beiyuan / Prince Qi",
      "Wu Xi",
      "Long Que",
      "Fan Huai Kong",
      "Tragicomic Ghost",
      "Luo Fumeng",
      "Shen Shen",
      "Lu Taichong",
    ],
    settingPlaceholder: "e.g., A wine shop at the edge of the jianghu, two wanderers sharing a pot of wine",
  },
  {
    id: "omniscient-reader",
    name: "Omniscient Reader's Viewpoint",
    category: "asian-media",
    canonRules:
      "Follow the scenario (apocalypse) rules. Kim Dokja is the sole reader of the web novel 'Three Ways to Survive in a Ruined World,' and when the scenarios from the novel become reality, he uses his knowledge to survive. Constellations sponsor incarnations through the Star Stream. Coins are the currency of the scenarios. Yoo Joonghyuk is the protagonist of the original novel who has regressed through multiple timelines. Respect the distinction between Dokja's meta-knowledge and Joonghyuk's lived experience. The Fourth Wall is both a skill and a thematic element.",
    locations:
      "Seoul (various stations and landmarks), Chungmuro, Dark Castle, the 73rd Demon Realm, the Final Scenario, the Star Stream, various scenario stages",
    characters: [
      "Kim Dokja",
      "Yoo Joonghyuk",
      "Han Sooyoung",
      "Jung Heewon",
      "Lee Hyunsung",
      "Lee Gilyoung",
      "Shin Yoosung",
      "Lee Seolhwa",
      "Bihyung",
      "Uriel",
      "Secretive Plotter",
      "Anna Croft",
      "Aileen Maker",
      "Kim Namwoon",
      "Yoo Sangah",
      "Han Myungoh",
      "Jang Hayoung",
      "Abyssal Black Flame Dragon (Lee Jihye)",
      "Gong Pildu",
      "Duke of Loyalty and Warfare",
      "Demon King of Salvation",
      "Oldest Dream",
      "Sun Wukong (ORV)",
      "Nirvana Moebius / Yoo Joonghyuk (1863rd turn)",
      "Breaking the Sky Master / Lee Sookyung",
      "Prisoner of the Golden Headband",
    ],
    settingPlaceholder: "e.g., A subway station as the first scenario begins, the world ending overhead",
  },
  {
    id: "svsss",
    name: "The Scum Villain's Self-Saving System / SVSSS",
    category: "asian-media",
    canonRules:
      "Shen Yuan transmigrated into the body of Shen Qingqiu, the scum villain of a web novel, and must survive the plot while dealing with the System's point penalties. Luo Binghe is the original novel's protagonist — a half-demon who was destined to be abused by his master. Respect the cultivation sect hierarchy (Cang Qiong Mountain has twelve peaks, each led by a Peak Lord). The System enforces OOC (out of character) penalties. Do not ignore the meta-fictional and comedic tone — Shen Yuan is constantly complaining about the original novel's plot holes.",
    locations:
      "Qing Jing Peak, Cang Qiong Mountain Sect, The Endless Abyss, Huan Hua Palace, Demon Realm, Jinlan City, Maigu Ridge, Dream Realm",
    characters: [
      "Shen Qingqiu / Shen Yuan",
      "Luo Binghe",
      "Liu Qingge",
      "Yue Qingyuan",
      "Ning Yingying",
      "Ming Fan",
      "Sha Hualing",
      "Mobei-Jun",
      "Shang Qinghua",
      "Zhuzhi-Lang",
      "Tianlang-Jun",
      "Gongyi Xiao",
      "Liu Mingyan",
      "Qiu Haitang",
      "Mu Qingfang",
      "Qi Qingqi",
      "Wei Qingwei",
      "The System",
      "Original Shen Qingqiu / Shen Jiu",
      "Su Xiyan",
      "Luo Binghe (original novel version)",
      "Old Palace Master",
      "Qiu Jianluo",
    ],
    settingPlaceholder: "e.g., The bamboo house on Qing Jing Peak, Shen Qingqiu fanning himself dramatically",
  },
  {
    id: "erha",
    name: "Erha / The Husky and His White Cat Shizun",
    category: "asian-media",
    canonRules:
      "Mo Ran (Taxian-jun in his previous life) is reborn to the time before he became a tyrant emperor. Chu Wanning is his strict, righteous shizun (master) at Sisheng Peak. The cultivation world uses spiritual energy and willow-wood weapons. The novel involves two timelines — the original (cruel) timeline and the rebirth timeline. Flower and butterfly motifs are symbolically significant. Respect the complex morality: Mo Ran's redemption, Chu Wanning's hidden tenderness, and the mystery of who truly orchestrated the tragedies. Do not simplify the emotional complexity.",
    locations:
      "Sisheng Peak, Life-Death Peak, Dai City, Rufeng Sect, Taxue Palace, Peach Blossom Springs, The Ghost Realm, Butterfly Town",
    characters: [
      "Mo Ran / Taxian-jun",
      "Chu Wanning",
      "Shi Mei / Shi Mingjing",
      "Xue Meng",
      "Xue Zhengyong",
      "Ye Wangxi",
      "Nangong Si",
      "Song Qiutong",
      "Mei Hanxue",
      "Jiang Xi",
      "Rong Jiu",
      "Chen Bohuan",
      "Madam Wang",
      "Nangong Liu",
      "Xu Shuanglin",
      "Hua Binan",
      "Ye Wangxi's family",
      "Eighteen (Mo Ran's dog)",
    ],
    settingPlaceholder: "e.g., The Red Lotus Pavilion at Sisheng Peak, haitang flowers falling like snow",
  },
];
