import type { FandomConfig } from "../../types/fandom.ts";

export const BOOK_FANDOMS: FandomConfig[] = [
  {
    id: "harry-potter",
    name: "Harry Potter",
    category: "books",
    canonRules:
      "Follow Harry Potter canon. Use magical elements, proper spell incantations, Hogwarts houses and their traits. No modern technology like phones or internet. Magic follows established rules. Use British English.",
    locations:
      "Hogwarts, Diagon Alley, Hogsmeade, The Burrow, Grimmauld Place, Ministry of Magic, Forbidden Forest, Room of Requirement",
    era: "Can be set during any era (Founders, Marauders, Golden Trio, Next Gen)",
    characters: [
      "Harry Potter",
      "Hermione Granger",
      "Ron Weasley",
      "Draco Malfoy",
      "Severus Snape",
      "Luna Lovegood",
      "Ginny Weasley",
      "Neville Longbottom",
      "Sirius Black",
      "Remus Lupin",
      "Tom Riddle / Voldemort",
      "Albus Dumbledore",
      "Fred Weasley",
      "George Weasley",
      "Cedric Diggory",
      "James Potter",
      "Lily Evans Potter",
      "Regulus Black",
      "Marlene McKinnon",
      "Barty Crouch Jr.",
      "Evan Rosier",
      "Mary MacDonald",
      "Dorcas Meadowes",
      "Peter Pettigrew",
      "Bill Weasley",
      "Charlie Weasley",
      "Percy Weasley",
      "Molly Weasley",
      "Arthur Weasley",
      "Pansy Parkinson",
      "Blaise Zabini",
      "Theodore Nott",
      "Daphne Greengrass",
      "Astoria Greengrass",
      "Fleur Delacour",
      "Viktor Krum",
      "Bellatrix Lestrange",
      "Narcissa Malfoy",
      "Lucius Malfoy",
      "Minerva McGonagall",
      "Nymphadora Tonks",
      "Kingsley Shacklebolt",
      "Oliver Wood",
      "Cho Chang",
      "Dean Thomas",
      "Seamus Finnigan",
      "Lavender Brown",
      "Rubeus Hagrid",
      "Dobby",
      "Alastor Moody",
      "Pomona Sprout",
      "Filius Flitwick",
      "Horace Slughorn",
      "Sybill Trelawney",
      "Poppy Pomfrey",
      "Andromeda Tonks",
      "Ted Tonks",
      "Fenrir Greyback",
      "Antonin Dolohov",
      "Rabastan Lestrange",
      "Rodolphus Lestrange",
      "Abraxas Malfoy",
      "Orion Black",
      "Walburga Black",
      "Kreacher",
      "Winky",
      "Gilderoy Lockhart",
      "Quirinus Quirrell",
      "Dolores Umbridge",
      "Cornelius Fudge",
      "Rufus Scrimgeour",
      "Parvati Patil",
      "Padma Patil",
      "Katie Bell",
      "Angelina Johnson",
      "Alicia Spinnet",
      "Lee Jordan",
      "Cormac McLaggen",
      "Romilda Vane",
      "Marcus Flint",
      "Adrian Pucey",
      "Gregory Goyle",
      "Vincent Crabbe",
      "Millicent Bulstrode",
      "Colin Creevey",
      "Dennis Creevey",
      "Scorpius Malfoy",
      "Albus Severus Potter",
      "James Sirius Potter",
      "Rose Granger-Weasley",
      "Teddy Lupin",
      "Victoire Weasley",
      "Hugo Granger-Weasley",
      "Lily Luna Potter",
      "Aberforth Dumbledore",
      "Gellert Grindelwald",
      "Ariana Dumbledore",
      "Bathilda Bagshot",
      "Helena Ravenclaw",
      "The Bloody Baron",
      "Nearly Headless Nick",
      "Moaning Myrtle",
      "Peeves",
      "Firenze",
      "Rosmerta",
      "Mundungus Fletcher",
      "Hedwig",
      "Crookshanks",
      "Nagini",
    ],
    settingPlaceholder: "e.g., Hogwarts library after hours, 6th year",
  },
  {
    id: "lord-of-the-rings",
    name: "Lord of the Rings / Tolkien",
    category: "books",
    canonRules:
      "Follow Tolkien's Middle-earth lore. Respect races (Elves, Dwarves, Hobbits, Men), languages, and the mythology. Magic is subtle and divine, not flashy. Do not use modern speech patterns. Maintain the epic, literary tone.",
    locations:
      "The Shire, Rivendell, Moria, Lothlórien, Rohan, Gondor, Mordor, Mirkwood, Isengard",
    era: "Can be set in any Age (First Age / Silmarillion, Second Age, Third Age / War of the Ring, Fourth Age)",
    characters: [
      "Aragorn",
      "Legolas",
      "Gimli",
      "Frodo Baggins",
      "Samwise Gamgee",
      "Gandalf",
      "Éowyn",
      "Faramir",
      "Boromir",
      "Thranduil",
      "Elrond",
      "Galadriel",
      "Pippin Took",
      "Merry Brandybuck",
      "Arwen Undómiel",
      "Éomer",
      "Tauriel",
      "Haldir",
      "Sauron / Annatar",
      "Celebrimbor",
      "Gil-galad",
      "Fëanor",
      "Fingolfin",
      "Maedhros",
      "Maglor",
      "Lúthien Tinúviel",
      "Beren",
      "Túrin Turambar",
      "Finrod Felagund",
      "Glorfindel",
      "Erestor",
      "Bilbo Baggins",
      "Thorin Oakenshield",
      "Kíli",
      "Fíli",
      "Treebeard / Fangorn",
      "Théoden",
      "Gríma Wormtongue",
      "Denethor",
      "Saruman",
      "Radagast",
      "Celeborn",
      "Elrohir",
      "Elladan",
      "Círdan",
      "Fingon",
      "Turgon",
      "Idril Celebrindal",
      "Tuor",
      "Eärendil",
      "Elwing",
      "Nienor Níniel",
      "Morgoth / Melkor",
      "Gothmog",
      "Ungoliant",
      "Shelob",
      "Gollum / Sméagol",
      "Tom Bombadil",
      "Goldberry",
      "Balin",
      "Dwalin",
      "Bofur",
      "Ori",
      "Nori",
      "Dís",
      "Beorn",
      "Bard the Bowman",
      "Lindir",
      "Curufin",
      "Celegorm",
      "Caranthir",
      "Amrod",
      "Amras",
      "Aredhel",
      "Melian",
      "Thingol",
    ],
    settingPlaceholder: "e.g., Rivendell on the eve of the Council, autumn of the Third Age",
  },
  {
    id: "percy-jackson",
    name: "Percy Jackson",
    category: "books",
    canonRules:
      "Follow Rick Riordan's Greek mythology rules. Demigods have one divine parent. Camp Half-Blood and Camp Jupiter are distinct. Use the established power system and cabin structure. Monsters reform in Tartarus. Maintain the humorous first-person tone.",
    locations:
      "Camp Half-Blood, Mount Olympus, The Underworld, Camp Jupiter, New Rome, Tartarus, The Labyrinth",
    characters: [
      "Percy Jackson",
      "Annabeth Chase",
      "Grover Underwood",
      "Nico di Angelo",
      "Thalia Grace",
      "Luke Castellan",
      "Jason Grace",
      "Piper McLean",
      "Leo Valdez",
      "Will Solace",
      "Rachel Elizabeth Dare",
      "Reyna Ramírez-Arellano",
      "Frank Zhang",
      "Hazel Levesque",
      "Clarisse La Rue",
      "Chris Rodriguez",
      "Silena Beauregard",
      "Charles Beckendorf",
      "Bianca di Angelo",
      "Zoë Nightshade",
      "Calypso",
      "Octavian",
      "Ethan Nakamura",
      "Travis Stoll",
      "Connor Stoll",
      "Chiron",
      "Kronos",
      "Apollo / Lester Papadopoulos",
      "Meg McCaffrey",
      "Sally Jackson",
      "Paul Blofis",
      "Poseidon",
      "Athena",
      "Hades",
      "Zeus",
      "Ares",
      "Hermes",
      "Dionysus / Mr. D",
      "Aphrodite",
      "Hephaestus",
      "Artemis",
      "Persephone",
      "Tyson",
      "Ella",
      "Katie Gardner",
      "Drew Tanaka",
      "Mitchell",
      "Lacy",
      "Dakota",
      "Gwendolyn",
      "Hylla Ramírez-Arellano",
      "Lou Ellen Blackstone",
      "Cecil Markowitz",
      "Gleeson Hedge",
      "Mellie",
      "Pan",
    ],
    settingPlaceholder: "e.g., Camp Half-Blood campfire, the night before a quest",
  },
  {
    id: "hunger-games",
    name: "The Hunger Games",
    category: "books",
    canonRules:
      "Follow Panem's dystopian setting. 12 districts plus the Capitol. Respect the political system, the Games mechanics, and the rebellion arc. No magic or supernatural elements. Maintain the tense, survival-focused tone. Class disparity is central.",
    locations:
      "District 12, The Capitol, The Arena, District 13, The Seam, Victor's Village, The Training Center, The Hob",
    characters: [
      "Katniss Everdeen",
      "Peeta Mellark",
      "Gale Hawthorne",
      "Finnick Odair",
      "Johanna Mason",
      "Haymitch Abernathy",
      "Effie Trinket",
      "President Snow",
      "Cinna",
      "Primrose Everdeen",
      "Annie Cresta",
      "Clove",
      "Cato",
      "Madge Undersee",
      "Thresh",
      "Rue",
      "Foxface",
      "Beetee",
      "Wiress",
      "Mags",
      "Enobaria",
      "Brutus",
      "Plutarch Heavensbee",
      "President Coin",
      "Boggs",
      "Tigris",
      "Seneca Crane",
      "Caesar Flickerman",
      "Lavinia (the Avox)",
      "Coriolanus Snow",
      "Lucy Gray Baird",
      "Sejanus Plinth",
      "Glimmer",
      "Marvel",
      "Cashmere",
      "Gloss",
      "Chaff",
      "Portia",
      "Flavius",
      "Octavia",
      "Venia",
      "Mrs. Everdeen",
      "Pollux",
      "Castor",
      "Cressida",
      "Messalla",
      "Darius",
      "Claudius Templesmith",
    ],
    settingPlaceholder: "e.g., The Cornucopia at dawn, 74th Hunger Games",
  },
  {
    id: "acotar",
    name: "A Court of Thorns and Roses",
    category: "books",
    canonRules:
      "Follow Sarah J. Maas's faerie world rules. Respect the Courts (Night, Spring, Dawn, Day, Winter, Summer, Autumn), mating bonds, Illyrian culture, and High Lord powers. Do not confuse Court territories or hierarchies. Romantic and dramatic tone. Mature themes are core to this fandom.",
    locations:
      "Velaris, The Night Court, Spring Court, Hewn City, The Illyrian Steppes, Under the Mountain, The Prison, The Court of Nightmares",
    characters: [
      "Feyre Archeron",
      "Rhysand",
      "Nesta Archeron",
      "Cassian",
      "Azriel",
      "Elain Archeron",
      "Tamlin",
      "Lucien Vanserra",
      "Amren",
      "Mor",
      "The Suriel",
      "Eris Vanserra",
      "Ianthe",
      "Tarquin",
      "Cresseida",
      "Varian",
      "Helion",
      "Thesan",
      "Kallias",
      "Viviane",
      "Beron Vanserra",
      "Gwyn Berdara",
      "Emerie",
      "Clotho",
      "Bryaxis",
      "Koschei",
      "The Bone Carver",
      "Drakon",
      "Miryam",
      "Jurian",
      "The King of Hybern",
      "Amarantha",
    ],
    settingPlaceholder: "e.g., The balcony of the House of Wind overlooking Velaris at dusk",
  },
  {
    id: "shadowhunter-chronicles",
    name: "The Shadowhunter Chronicles",
    category: "books",
    canonRules:
      "Follow Cassandra Clare's Shadow World rules. Shadowhunters use runes, seraph blades, and steles. Respect the Clave hierarchy and Downworlder politics (Warlocks, Vampires, Werewolves, Faeries). Parabatai bonds are sacred and have strict rules. Do not mix up series timelines without justification.",
    locations:
      "New York Institute, Idris (Alicante), The Pandemonium Club, The Seelie Court, Edom, The Silent City, Magnus's Loft",
    era: "Can be set during The Mortal Instruments, The Infernal Devices, The Dark Artifices, or other eras",
    characters: [
      "Jace Herondale",
      "Clary Fray",
      "Magnus Bane",
      "Alec Lightwood",
      "Isabelle Lightwood",
      "Simon Lewis",
      "Will Herondale",
      "Jem Carstairs",
      "Tessa Gray",
      "Julian Blackthorn",
      "Emma Carstairs",
      "Sebastian Morgenstern",
      "Luke Garroway",
      "Maia Roberts",
      "Jordan Kyle",
      "Raphael Santiago",
      "Catarina Loss",
      "Ragnor Fell",
      "Max Lightwood",
      "Robert Lightwood",
      "Maryse Lightwood",
      "Charlotte Branwell",
      "Henry Branwell",
      "Jessamine Lovelace",
      "Gabriel Lightwood",
      "Gideon Lightwood",
      "Cecily Herondale",
      "Sophie Collins",
      "Cristina Rosales",
      "Mark Blackthorn",
      "Kieran",
      "Ty Blackthorn",
      "Kit Herondale",
      "Livvy Blackthorn",
      "Dru Blackthorn",
      "Diana Wrayburn",
    ],
    settingPlaceholder: "e.g., The rooftop of the New York Institute, midnight",
  },
  {
    id: "six-of-crows",
    name: "Six of Crows / Grishaverse",
    category: "books",
    canonRules:
      "Follow Leigh Bardugo's Grishaverse rules. Grisha powers fall into three Orders (Corporalki, Etherealki, Materialki). Respect the economics and criminal underworld of Ketterdam. Jurda parem is catastrophically dangerous. Do not give characters powers outside their Grisha type. Maintain the heist-thriller tone for Six of Crows and the epic fantasy tone for Shadow and Bone.",
    locations:
      "Ketterdam, The Barrel, The Slat, The Ice Court, Ravka, The Little Palace, Os Alta, Fjerda, Novyi Zem",
    characters: [
      "Kaz Brekker",
      "Inej Ghafa",
      "Jesper Fahey",
      "Wylan Van Eck",
      "Nina Zenik",
      "Matthias Helvar",
      "Alina Starkov",
      "The Darkling / Aleksander Morozova",
      "Nikolai Lantsov",
      "Mal Oretsev",
      "Genya Safin",
      "Zoya Nazyalensky",
      "David Kostyk",
      "Tamar Kir-Bataar",
      "Tolya Yul-Bataar",
      "Baghra",
      "The Apparat",
      "Pekka Rollins",
      "Jan Van Eck",
      "Kuwei Yul-Bo",
      "Hanne Brum",
      "Jarl Brum",
      "Per Haskell",
      "Rotty",
      "Big Bolliger",
      "Colm Fahey",
      "Sturmhond",
      "Fedyor Kaminsky",
      "Ivan",
      "Leigh / Sankta Lizabeta",
    ],
    settingPlaceholder: "e.g., The Crow Club in the Barrel, a foggy Ketterdam night",
  },
  {
    id: "all-for-the-game",
    name: "All For The Game",
    category: "books",
    canonRules:
      "Follow Nora Sakavic's Exy sport rules and the Foxes' team dynamics. Respect Neil's identity concealment and trauma, Andrew's boundaries and protective nature, and the Moriyama crime family hierarchy. Do not romanticize abuse. Maintain the dark, intense tone. Exy is a fictional sport — do not confuse it with lacrosse or hockey.",
    locations:
      "Palmetto State University, Fox Tower, The Foxhole Court, Edgar Allan University, Evermore, Columbia",
    characters: [
      "Neil Josten",
      "Andrew Minyard",
      "Kevin Day",
      "Aaron Minyard",
      "Nicky Hemmick",
      "Dan Wilds",
      "Matt Boyd",
      "Allison Reynolds",
      "Renee Walker",
      "Seth Gordon",
      "Jean Moreau",
      "Riko Moriyama",
      "Wymack / David Wymack",
      "Abby Winfield",
      "Betsy Dobson / Bee",
      "Ichirou Moriyama",
      "Kengo Moriyama",
      "Nathan Wesninski",
      "Mary Hatford",
      "Stuart Hatford",
      "Katelyn",
      "Erik Klose",
      "Tetsuji Moriyama",
      "Jeremy Knox",
      "Laila Dermott",
      "Alvarez",
    ],
    settingPlaceholder: "e.g., The rooftop of Fox Tower, 3 AM",
  },
  {
    id: "les-miserables",
    name: "Les Misérables",
    category: "books",
    canonRules:
      "Follow Victor Hugo's novel (fandom draws from book, musical, and adaptations). Respect the French historical setting (post-Napoleonic France, 1832 June Rebellion). Do not use modern slang or technology. Understand the class dynamics, the law vs. mercy theme, and the revolutionary idealism. Characters may be written in modern AU but canon should be the default.",
    locations:
      "Paris, The Barricade, The Thénardier Inn, The Convent, Montreuil-sur-Mer, The Sewers of Paris, The Café Musain",
    era: "1815–1832, or modern AU",
    characters: [
      "Enjolras",
      "Grantaire",
      "Jean Valjean",
      "Javert",
      "Éponine",
      "Marius Pontmercy",
      "Cosette",
      "Combeferre",
      "Courfeyrac",
      "Jehan Prouvaire",
      "Bahorel",
      "Feuilly",
      "Joly",
      "Bossuet",
      "Musichetta",
      "Fantine",
      "Thénardier",
      "Madame Thénardier",
      "Gavroche",
      "Azelma",
      "Bishop Myriel",
      "Montparnasse",
      "Patron-Minette",
      "Gillenormand",
      "Mabeuf",
      "Louison",
      "Toussaint",
      "Fauchelevent",
      "Petit Gervais",
      "Bamatabois",
    ],
    settingPlaceholder: "e.g., The Café Musain, the night before the barricade",
  },
  {
    id: "the-raven-cycle",
    name: "The Raven Cycle",
    category: "books",
    canonRules:
      "Follow Maggie Stiefvater's world rules. Ley lines power magic. Blue Sargent's curse (killing her true love with a kiss) is central. Respect Cabeswater as a sentient magical forest. Aglionby boys are privileged prep school students. Maintain the dreamy, atmospheric Southern Gothic tone. Do not make Ronan's dream abilities limitless — they have a cost.",
    locations:
      "Henrietta (Virginia), Aglionby Academy, 300 Fox Way, Cabeswater, Monmouth Manufacturing, The Barns",
    characters: [
      "Richard Gansey III",
      "Ronan Lynch",
      "Adam Parrish",
      "Blue Sargent",
      "Noah Czerny",
      "Henry Cheng",
      "Declan Lynch",
      "Matthew Lynch",
      "Maura Sargent",
      "Mr. Gray / The Gray Man",
      "Persephone",
      "Calla",
      "Gwenllian",
      "Orla",
      "Jimi",
      "Joseph Kavinsky",
      "Prokopenko",
      "Skov",
      "Swan",
      "Jiang",
      "Barrington Whelk",
      "Neeve",
      "Ashley",
      "Opal",
      "Aurora Lynch",
      "Niall Lynch",
      "Robert Parrish",
      "Helen Gansey",
      "Piper Greenmantle",
      "Colin Greenmantle",
    ],
    settingPlaceholder: "e.g., Cabeswater at twilight, the ley line humming underfoot",
  },
  {
    id: "red-white-royal-blue",
    name: "Red, White & Royal Blue",
    category: "books",
    canonRules:
      "Follow Casey McQuiston's world. Alex is the First Son of the US; Henry is a British prince. Respect the political dynamics, the secrecy of their relationship, and the media scrutiny. The tone is romantic comedy with political stakes. Do not ignore the real-world-adjacent political setting.",
    locations:
      "The White House, Kensington Palace, The Beekman Hotel, Buckingham Palace, Austin (Texas), London",
    characters: [
      "Alex Claremont-Diaz",
      "Prince Henry",
      "Nora Holleran",
      "June Claremont-Diaz",
      "Bea Fox",
      "Pez",
      "Ellen Claremont",
      "Zahra Bankston",
      "Shaan Srivastava",
      "Catherine (Queen Mary)",
      "Oscar Diaz",
      "Philip",
      "Martha",
      "Amy Chen",
      "Cash",
      "Rafael Luna",
      "Richards",
      "Percy Okonjo",
      "Mike B",
      "Hunter",
    ],
    settingPlaceholder: "e.g., A secret meeting in the White House residence, late at night",
  },
  {
    id: "his-dark-materials",
    name: "His Dark Materials",
    category: "books",
    canonRules:
      "Follow Philip Pullman's multiverse rules. Every human has a dæmon (animal soul companion) that settles into a fixed form at puberty. Touching another person's dæmon is taboo. Dust is conscious matter drawn to experience. The Magisterium is an authoritarian religious body. Respect the alethiometer's symbolic reading system. Do not forget characters' dæmons.",
    locations:
      "Oxford (Lyra's world), Bolvangar, Svalbard, Cittàgazze, The Land of the Dead, Jordan College, The Subtle Knife's tower",
    characters: [
      "Lyra Belacqua / Lyra Silvertongue",
      "Will Parry",
      "Lord Asriel",
      "Marisa Coulter",
      "Lee Scoresby",
      "Iorek Byrnison",
      "Serafina Pekkala",
      "Roger Parslow",
      "Mary Malone",
      "Pantalaimon",
      "Hester (Lee's dæmon)",
      "Stelmaria (Asriel's dæmon)",
      "The Golden Monkey (Coulter's dæmon)",
      "John Faa",
      "Farder Coram",
      "Ma Costa",
      "Billy Costa",
      "Tony Makarios",
      "Iofur Raknison",
      "Balthamos",
      "Baruch",
      "Metatron",
      "The Authority / God",
      "Father Gomez",
      "Malcolm Polstead",
      "Alice Parslow",
      "Hannah Relf",
      "Xaphania",
      "Ruta Skadi",
      "Giacomo Paradisi",
    ],
    settingPlaceholder: "e.g., The rooftops of Jordan College at dusk, dæmons settling for the night",
  },
  {
    id: "the-locked-tomb",
    name: "The Locked Tomb",
    category: "books",
    canonRules:
      "Follow Tamsyn Muir's necromantic universe. Nine Houses each practice distinct thanaturgic traditions. Necromancers and cavaliers are bonded pairs. Lyctorhood requires consuming your cavalier's soul. Do not confuse Houses or their specialties. Maintain the irreverent, meme-literate narrative voice. Bone magic has rules — respect them.",
    locations:
      "Canaan House, The Ninth House (Drearburh), The First House, The Mithraeum, New Rho, The River",
    characters: [
      "Gideon Nav",
      "Harrowhark Nonagesimus",
      "Ianthe Tridentarius",
      "Coronabeth Tridentarius",
      "Camilla Hect",
      "Palamedes Sextus",
      "Nona",
      "Mercymorn",
      "Augustine",
      "God / John Gaius",
      "Dulcinea Septimus",
      "Pyrrha Dve",
      "Cytherea the First",
      "Ortus Nigenad",
      "Crux",
      "Aiglamene",
      "Protesilaus Ebdoma",
      "Silas Octakiseron",
      "Colum Asht",
      "Magnus Quinn",
      "Abigail Pent",
      "Jeannemary Chatur",
      "Isaac Tettares",
      "Naberius Tern",
      "Teacher",
      "Kiriona Gaia",
      "Alecto",
      "Commander Wake",
      "Judith Deuteros",
      "Marta Dyas",
      "Cassiopeia",
    ],
    settingPlaceholder: "e.g., The crumbling halls of Canaan House, necromantic trial in progress",
  },
  {
    id: "fourth-wing",
    name: "Fourth Wing",
    category: "books",
    canonRules:
      "Follow Rebecca Yarros's dragon rider world. Basgiath War College is lethal — cadets die regularly. Dragons choose their riders and can incinerate the unworthy. Signets are unique magical abilities granted by the bond. Respect the military hierarchy, the ward system, and the Venin threat. Do not make dragon bonding trivial — it is earned.",
    locations:
      "Basgiath War College, The Parapet, The Ridgeline, The Flight Field, Aretia, The Empyrean",
    characters: [
      "Violet Sorsengail",
      "Xaden Riorson",
      "Tairn",
      "Andarna",
      "Dain Aetos",
      "Rhiannon Matthias",
      "Liam Mairi",
      "Bodhi Durran",
      "Jesinia",
      "Lilith Sorsengail",
      "Brennan Sorsengail",
      "Imogen",
      "Ridoc",
      "Sawyer",
      "Nadine",
      "Mira Sorsengail",
      "Jack Barlowe",
      "Varrish",
      "Markham",
      "Sgaeyl",
      "Codagh",
      "Deigh",
      "Sloane Mairi",
      "Aaric Graycastle",
      "Cat Cordella",
      "Garrick",
    ],
    settingPlaceholder: "e.g., The Parapet crossing at Basgiath, first day of the quadrant",
  },
  {
    id: "twilight",
    name: "Twilight",
    category: "books",
    canonRules:
      "Follow Stephenie Meyer's vampire rules. Vampires sparkle in sunlight (do not skip this). Vegetarian vampires drink animal blood. Werewolves are actually shapeshifters, not true lycanthropes. Imprinting is involuntary. The Volturi enforce vampire law. Maintain the moody, romantic Pacific Northwest atmosphere.",
    locations:
      "Forks (Washington), La Push, The Cullen House, Volterra, Forks High School, The Meadow, Phoenix",
    characters: [
      "Bella Swan",
      "Edward Cullen",
      "Jacob Black",
      "Alice Cullen",
      "Jasper Hale",
      "Rosalie Hale",
      "Emmett Cullen",
      "Carlisle Cullen",
      "Esme Cullen",
      "Charlie Swan",
      "Leah Clearwater",
      "Aro",
      "Renesmee Cullen",
      "Seth Clearwater",
      "Sam Uley",
      "Emily Young",
      "Paul Lahote",
      "Quil Ateara",
      "Embry Call",
      "Billy Black",
      "Renée Dwyer",
      "Phil Dwyer",
      "Mike Newton",
      "Jessica Stanley",
      "Angela Weber",
      "Eric Yorkie",
      "Lauren Mallory",
      "Tyler Crowley",
      "Caius",
      "Marcus",
      "Jane",
      "Alec",
      "Demetri",
      "Felix",
      "Chelsea",
      "Heidi",
      "Victoria",
      "James",
      "Laurent",
      "Riley Biers",
      "Bree Tanner",
      "Tanya",
      "Kate",
      "Irina",
      "Eleazar",
      "Carmen",
      "Garrett",
      "Benjamin",
      "Zafrina",
    ],
    settingPlaceholder: "e.g., The meadow in the Olympic Peninsula, overcast sky",
  },
  {
    id: "a-song-of-ice-and-fire",
    name: "A Song of Ice and Fire",
    category: "books",
    canonRules:
      "Follow George R.R. Martin's book canon (not the show). Respect the POV chapter structure and unreliable narrators. Prophecy (Azor Ahai, the Prince That Was Promised) is ambiguous by design. The political scheming, feudal system, and moral complexity are central. Characters who are alive in the books may be dead in the show and vice versa. Use book-accurate details (e.g., Tyrion's nose, Daario's blue beard).",
    locations:
      "King's Landing, Winterfell, The Wall, Dragonstone, Braavos, The Red Keep, Castle Black, Oldtown, The Eyrie, Dorne",
    characters: [
      "Jon Snow",
      "Daenerys Targaryen",
      "Tyrion Lannister",
      "Cersei Lannister",
      "Jaime Lannister",
      "Arya Stark",
      "Sansa Stark",
      "Brienne of Tarth",
      "Petyr Baelish",
      "Sandor Clegane",
      "Stannis Baratheon",
      "Theon Greyjoy",
      "Margaery Tyrell",
      "Samwell Tarly",
      "Robb Stark",
      "Bran Stark",
      "Rickon Stark",
      "Eddard Stark",
      "Catelyn Stark",
      "Tywin Lannister",
      "Joffrey Baratheon",
      "Renly Baratheon",
      "Robert Baratheon",
      "Davos Seaworth",
      "Melisandre",
      "Varys",
      "Bronn",
      "Podrick Payne",
      "Olenna Tyrell",
      "Loras Tyrell",
      "Oberyn Martell",
      "Ellaria Sand",
      "Arianne Martell",
      "Doran Martell",
      "Asha Greyjoy",
      "Euron Greyjoy",
      "Victarion Greyjoy",
      "Ramsay Bolton",
      "Roose Bolton",
      "Jorah Mormont",
      "Daario Naharis",
      "Missandei",
      "Grey Worm",
      "Barristan Selmy",
      "Aegon / Young Griff",
      "Jon Connington",
      "Shireen Baratheon",
      "Gilly",
      "Val",
      "Tormund Giantsbane",
      "Mance Rayder",
      "Ygritte",
      "Hodor",
      "Meera Reed",
      "Jojen Reed",
      "The High Sparrow",
      "Gregor Clegane",
      "Qyburn",
    ],
    settingPlaceholder: "e.g., The godswood of Winterfell, snow falling on the heart tree",
  },
  {
    id: "good-omens-book",
    name: "Good Omens (Book)",
    category: "books",
    canonRules:
      "Follow Neil Gaiman and Terry Pratchett's novel canon. Aziraphale is a fussy angel who loves books and food; Crowley is a cool demon who didn't so much Fall as Saunter Vaguely Downward. Their 6,000-year friendship is the core. The Apocalypse is an inconvenience. Maintain the witty, British comedic tone. Do not make it grimdark — this is a comedy about the end of the world.",
    locations:
      "Aziraphale's Bookshop (Soho), Crowley's Flat (Mayfair), Tadfield, The Ritz, Heaven, Hell, The Garden of Eden",
    characters: [
      "Aziraphale",
      "Crowley",
      "Adam Young",
      "Anathema Device",
      "Newton Pulsifer",
      "Madame Tracy",
      "Sergeant Shadwell",
      "The Them (Pepper, Wensleydale, Brian)",
      "Hastur",
      "Ligur",
      "Pepper",
      "Wensleydale",
      "Brian",
      "Dog (Hellhound)",
      "Agnes Nutter",
      "Beelzebub",
      "Gabriel",
      "Michael",
      "Uriel",
      "Sandalphon",
      "Dagon",
      "War",
      "Famine",
      "Pollution",
      "Death",
      "The Metatron",
      "God (the Narrator)",
      "Sister Mary Loquacious",
      "Mr. Young",
      "Deirdre Young",
    ],
    settingPlaceholder: "e.g., The back room of A.Z. Fell & Co., cocoa and prophecy",
  },
  {
    id: "priory-of-the-orange-tree",
    name: "The Priory of the Orange Tree",
    category: "books",
    canonRules:
      "Follow Samantha Shannon's world. Eastern and Western dragon mythologies are distinct — Western wyrms are fire-breathing enemies, Eastern dragons are sacred water allies. Respect the Priory's matriarchal structure and Ead's dual identity. Siden is the magical force; do not conflate it with generic fantasy magic. The political and religious tensions between the Queendom of Inys, the East, and the South are central.",
    locations:
      "Inys (Ascalon Palace), The Priory, Seiiki, Hróth, Yscalin, Lasia, The Abyss",
    characters: [
      "Ead Duryan",
      "Queen Sabran Berethnet",
      "Tané",
      "Loth Beck",
      "Niclays Roos",
      "Arteloth Beck",
      "Nairuj",
      "Chassar uq-Ispad",
      "The Nameless One",
      "Kalyba",
      "Margret Beck",
      "Truyde utt Zeedeur",
      "Laya",
      "Susa",
      "Nayimathun",
      "Lord Seyton Combe",
      "Yscalin Ambassador",
      "Roslain Crest",
      "Lady Arbella Glenn",
      "Fyredel",
    ],
    settingPlaceholder: "e.g., The Priory hidden in the orange groves, dawn breaking over the South",
  },
];
