import { FandomConfig } from "../../types/fandom";

export const CARTOON_FANDOMS: FandomConfig[] = [
  {
    id: "miraculous-ladybug",
    name: "Miraculous Ladybug",
    category: "cartoons",
    canonRules:
      "Miraculous holders transform using kwamis and specific jewelry (Ladybug: earrings + Tikki, Cat Noir: ring + Plagg). Lucky Charm and Cataclysm have specific usage rules. The love square (Marinette/Ladybug loves Adrien/Chat Noir in various combinations) is central. Secret identities must be maintained unless the story specifically reveals them. Do not give characters Miraculous they don't have without explanation.",
    locations:
      "Paris, Collège Françoise Dupont, The Eiffel Tower, Marinette's bakery/room, Agreste Mansion, Fu's massage parlor, The Miraculous Box",
    characters: [
      "Marinette Dupain-Cheng / Ladybug",
      "Adrien Agreste / Cat Noir",
      "Alya Césaire / Rena Rouge",
      "Nino Lahiffe / Carapace",
      "Gabriel Agreste / Hawk Moth",
      "Chloé Bourgeois",
      "Luka Couffaine",
      "Kagami Tsurugi",
      "Tikki",
      "Plagg",
      "Félix Graham de Vanily",
      "Nathalie Sancoeur / Mayura",
    ],
    settingPlaceholder: "e.g., A Parisian rooftop at twilight, Ladybug and Cat Noir on patrol",
  },
  {
    id: "avatar-the-last-airbender",
    name: "Avatar: The Last Airbender",
    category: "cartoons",
    canonRules:
      "Four nations correspond to four elements (Water, Earth, Fire, Air). Only the Avatar can bend all four. Bending has specific martial arts styles per element. The Fire Nation waged a 100-year war. Respect the spiritual and cultural worldbuilding of each nation. Do not give non-benders bending or mix up bending styles. Maintain the balance of humor, adventure, and genuine emotional depth.",
    locations:
      "The Southern Water Tribe, Ba Sing Se, The Fire Nation Capital, The Western Air Temple, Omashu, The Boiling Rock, Ember Island, The Spirit World",
    characters: [
      "Aang",
      "Katara",
      "Sokka",
      "Zuko",
      "Toph Beifong",
      "Iroh",
      "Azula",
      "Suki",
      "Mai",
      "Ty Lee",
      "Ozai",
      "Jet",
      "Yue",
    ],
    settingPlaceholder: "e.g., Uncle Iroh's tea shop in Ba Sing Se, jasmine tea and quiet wisdom",
  },
  {
    id: "avatar-legend-of-korra",
    name: "Avatar: The Legend of Korra",
    category: "cartoons",
    canonRules:
      "Set 70 years after ATLA. Republic City blends all four nations. Korra is the opposite of Aang — brash, physical, and must learn the spiritual side. Respect the industrialized, 1920s-inspired setting. Pro-bending has specific rules. Each season has a distinct villain with a legitimate philosophical point. Do not ignore Korra's PTSD arc or the political themes. The Avatar State is powerful but not invincible.",
    locations:
      "Republic City, Air Temple Island, The Spirit World, Zaofu, The Northern Water Tribe, The Si Wong Desert, Ba Sing Se (post-fall)",
    characters: [
      "Korra",
      "Asami Sato",
      "Mako",
      "Bolin",
      "Tenzin",
      "Lin Beifong",
      "Suyin Beifong",
      "Amon / Noatak",
      "Kuvira",
      "Zaheer",
      "Varrick",
      "Jinora",
    ],
    settingPlaceholder: "e.g., Air Temple Island at dawn, Korra meditating overlooking Republic City",
  },
  {
    id: "the-owl-house",
    name: "The Owl House",
    category: "cartoons",
    canonRules:
      "The Boiling Isles is a demon realm on the body of a dead Titan. Witches use bile sacs to cast magic through glyphs or covens. Luz is a human who learns glyph magic (distinct from witch magic). The Coven system restricts witches to one type of magic. Emperor Belos seeks to destroy all witches. Do not ignore that Lumity (Luz/Amity) is canon. Maintain the blend of whimsy, horror, and heart.",
    locations:
      "The Owl House, Hexside School, The Emperor's Castle, Bonesborough, The Titan's body, The Human Realm, The In Between, Gravesfield",
    characters: [
      "Luz Noceda",
      "Amity Blight",
      "Eda Clawthorne / The Owl Lady",
      "King",
      "Hunter / The Golden Guard",
      "Willow Park",
      "Gus Porter",
      "Lilith Clawthorne",
      "Emperor Belos / Philip Wittebane",
      "The Collector",
      "Hooty",
      "Raine Whispers",
    ],
    settingPlaceholder: "e.g., The Owl House living room, Luz practicing glyphs while King naps",
  },
  {
    id: "she-ra-2018",
    name: "She-Ra and the Princesses of Power",
    category: "cartoons",
    canonRules:
      "Adora transforms into She-Ra using the Sword of Protection (later, through her own power). The Princess Alliance fights the Horde. Etheria is a planet with First Ones technology and magical runestones. Catra's arc from villain to redeemed character is central. Do not ignore the queer relationships (Catradora is endgame canon). Maintain the blend of epic fantasy, found family, and emotional character growth.",
    locations:
      "Bright Moon, The Fright Zone, The Whispering Woods, Mystacor, Salineas, Beast Island, The Crystal Castle, Etheria",
    characters: [
      "Adora / She-Ra",
      "Catra",
      "Glimmer",
      "Bow",
      "Scorpia",
      "Entrapta",
      "Hordak",
      "Shadow Weaver / Light Spinner",
      "Mermista",
      "Perfuma",
      "Double Trouble",
      "Horde Prime",
    ],
    settingPlaceholder: "e.g., Bright Moon's balcony, the moons of Etheria lighting the Whispering Woods",
  },
  {
    id: "gravity-falls",
    name: "Gravity Falls",
    category: "cartoons",
    canonRules:
      "Gravity Falls, Oregon is a supernatural hotspot. The Mystery Shack is a tourist trap hiding real mysteries. The Journals (1, 2, 3) contain supernatural knowledge. Bill Cipher is a dream demon from another dimension — his deals always have a catch. Respect the mystery-adventure tone and the twins' bond. Do not bring Bill back casually — his defeat was hard-won. Maintain the blend of creepy, funny, and heartfelt.",
    locations:
      "The Mystery Shack, Gravity Falls (town), The Forest, The Bunker, The Fearamid, The Mindscape, Northwest Manor, The Lake",
    characters: [
      "Dipper Pines",
      "Mabel Pines",
      "Grunkle Stan / Stanley Pines",
      "Ford Pines / Stanford Pines",
      "Bill Cipher",
      "Soos Ramirez",
      "Wendy Corduroy",
      "Pacifica Northwest",
      "Waddles",
      "Gideon Gleeful",
    ],
    settingPlaceholder: "e.g., The Mystery Shack attic, Dipper poring over Journal 3 by flashlight",
  },
  {
    id: "steven-universe",
    name: "Steven Universe",
    category: "cartoons",
    canonRules:
      "Gems are alien beings with specific gem types and abilities. Steven is half-human, half-Gem (he has Rose Quartz's gem). Fusion is an intimate act representing relationships. Gems can be poofed but not easily shattered. Homeworld has a strict caste system (Diamonds, Pearls, Quartzes, etc.). Do not ignore Steven's trauma or the show's themes of consent, identity, and healing. Maintain the gentle, emotionally honest tone.",
    locations:
      "Beach City, The Temple, Homeworld, The Barn, The Kindergarten, Little Homeworld, Rose's Room, The Zoo",
    characters: [
      "Steven Universe",
      "Garnet",
      "Amethyst",
      "Pearl",
      "Connie Maheswaran",
      "Lapis Lazuli",
      "Peridot",
      "Bismuth",
      "Rose Quartz / Pink Diamond",
      "Jasper",
      "Spinel",
      "Greg Universe",
    ],
    settingPlaceholder: "e.g., The beach in front of the Temple, sunset, ukulele playing softly",
  },
  {
    id: "rwby",
    name: "RWBY",
    category: "cartoons",
    canonRules:
      "Remnant is threatened by Grimm (creatures of darkness drawn to negative emotions). Hunters and Huntresses use weapons that are also guns. Aura is a protective force field from the soul; Semblances are unique abilities per person. Dust is the energy source (not magic). The four Relics (Creation, Destruction, Knowledge, Choice) and the Maidens are central to the plot. Do not confuse Aura/Semblance/Dust/Magic — they are distinct systems.",
    locations:
      "Beacon Academy, Vale, Atlas, Mantle, Mistral, Vacuo, The Ever After, The Vaults, Salem's Domain",
    characters: [
      "Ruby Rose",
      "Weiss Schnee",
      "Blake Belladonna",
      "Yang Xiao Long",
      "Jaune Arc",
      "Nora Valkyrie",
      "Lie Ren",
      "Pyrrha Nikos",
      "Oscar Pine / Ozpin",
      "Qrow Branwen",
      "Cinder Fall",
      "Salem",
      "Penny Polendina",
    ],
    settingPlaceholder: "e.g., Beacon's courtyard, weapons gleaming before a training match",
  },
  {
    id: "hazbin-hotel",
    name: "Hazbin Hotel",
    category: "cartoons",
    canonRules:
      "Set in Hell, where sinners are sent after death. Charlie Morningstar (Lucifer's daughter) runs the Hazbin Hotel to rehabilitate sinners and prevent the annual extermination by Heaven's angels. Each character died as a human and retains trauma from their life. Angelic weapons can permanently kill demons. Overlords control territories. Do not sanitize the mature content — it's Hell, and the characters are sinners. Maintain the musical, darkly comedic tone.",
    locations:
      "The Hazbin Hotel, Pentagram City, The Vees' Tower, Cannibal Town, Heaven, The Pride Ring, Radio Tower, Various clubs",
    characters: [
      "Charlie Morningstar",
      "Vaggie",
      "Alastor / The Radio Demon",
      "Angel Dust",
      "Husk",
      "Niffty",
      "Sir Pentious",
      "Lucifer Morningstar",
      "Vox",
      "Valentino",
      "Velvette",
      "Adam",
      "Cherri Bomb",
    ],
    settingPlaceholder: "e.g., The Hazbin Hotel lobby, Alastor's radio static crackling ominously",
  },
  {
    id: "helluva-boss",
    name: "Helluva Boss",
    category: "cartoons",
    canonRules:
      "I.M.P. (Immediate Murder Professionals) is an assassination business in Hell that kills living humans for dead clients. Blitzo, Moxxie, Millie, and Loona are the core team. Stolas is a Goetia prince whose grimoire enables travel to Earth. Hell has a strict hierarchy (Royals > Overlords > Sinners > Imps > Hellhounds). Imps are born in Hell, not dead humans. Do not confuse the Hazbin and Helluva power structures. Maintain the raunchy, violent, emotionally complex comedy tone.",
    locations:
      "I.M.P. Headquarters, Stolas's Palace, The Living World (Earth), Loo Loo Land, Ozzie's, The Wrath Ring, Various rings of Hell",
    characters: [
      "Blitzo",
      "Moxxie",
      "Millie",
      "Loona",
      "Stolas",
      "Octavia",
      "Striker",
      "Fizzarolli",
      "Asmodeus / Ozzie",
      "Stella",
      "Verosika Mayday",
    ],
    settingPlaceholder: "e.g., The I.M.P. office, Blitzo assigning a chaotic new hit",
  },
  {
    id: "voltron-legendary-defender",
    name: "Voltron: Legendary Defender",
    category: "cartoons",
    canonRules:
      "Five Paladins pilot Lions that combine into Voltron. Each Lion chooses its Paladin based on personality traits (Black: leadership, Red: instinct, Blue: trust, Green: curiosity, Yellow: compassion). The Galra Empire has conquered most of the universe. Quintessence is a powerful energy source. Alteans are nearly extinct. Do not mix up Lion/Paladin assignments across seasons without noting the change. Maintain the space opera adventure tone.",
    locations:
      "The Castle of Lions, Planet Arus, Galra Command Ships, The Astral Plane, Earth, Daibazaal, Oriande, Various alien worlds",
    characters: [
      "Keith",
      "Lance",
      "Shiro",
      "Hunk",
      "Pidge / Katie Holt",
      "Princess Allura",
      "Coran",
      "Lotor",
      "Zarkon",
      "Haggar / Honerva",
      "Krolia",
      "Adam",
    ],
    settingPlaceholder: "e.g., The Castle of Lions bridge, stars streaming past as an alert sounds",
  },
  {
    id: "teenage-mutant-ninja-turtles",
    name: "Teenage Mutant Ninja Turtles",
    category: "cartoons",
    canonRules:
      "Four turtle brothers mutated by ooze, trained in ninjutsu by Splinter (their rat sensei/father). Each turtle has a distinct weapon and personality (Leo: katanas/leader, Raph: sai/hothead, Donnie: bo staff/genius, Mikey: nunchucks/jokester). The Foot Clan and Shredder are primary antagonists. Can draw from any incarnation (2003, 2012, Rise, Mutant Mayhem). Specify which version or blend them thoughtfully.",
    locations:
      "The Sewer Lair, New York City rooftops, The Foot Clan headquarters, April's apartment, Dimension X, Various NYC locations",
    characters: [
      "Leonardo",
      "Raphael",
      "Donatello",
      "Michelangelo",
      "Splinter",
      "April O'Neil",
      "Casey Jones",
      "Shredder / Oroku Saki",
      "Karai",
      "Bebop",
      "Rocksteady",
      "Krang",
    ],
    settingPlaceholder: "e.g., The sewer lair, pizza boxes everywhere, training in progress",
  },
  {
    id: "arcane",
    name: "Arcane",
    category: "cartoons",
    canonRules:
      "Set in the League of Legends universe but follows its own narrative. Piltover (the topside) and Zaun (the undercity) are divided by class and ideology. Hextech is a new technology with immense power and danger. Shimmer is a dangerous drug/mutation catalyst. Vi and Jinx (Powder) are sisters torn apart. Do not simplify the political conflict — both sides have legitimate grievances. Maintain the visually stunning, emotionally devastating tone.",
    locations:
      "Piltover, Zaun / The Undercity, The Council Chambers, The Last Drop, Jayce's Lab, Silco's Office, The Lanes, The Bridge",
    characters: [
      "Vi",
      "Jinx / Powder",
      "Caitlyn Kiramman",
      "Jayce Talis",
      "Viktor",
      "Silco",
      "Vander",
      "Ekko",
      "Mel Medarda",
      "Heimerdinger",
      "Sevika",
      "Marcus",
    ],
    settingPlaceholder: "e.g., The neon-lit streets of Zaun, smoke rising from the undercity",
  },
  {
    id: "frozen",
    name: "Frozen",
    category: "cartoons",
    canonRules:
      "Elsa has ice powers that are tied to her emotions. Arendelle is a Nordic-inspired kingdom. Anna is the heart of the story — warm, impulsive, and fiercely loving. True love is not just romantic (Anna and Elsa's sisterly bond broke the curse). Do not ignore Frozen 2's expansion of the lore (Ahtohallan, the elemental spirits, Northuldra). Kristoff is a mountain man and ice harvester. Maintain the fairy-tale tone with emotional depth.",
    locations:
      "Arendelle, Elsa's Ice Palace, The Enchanted Forest, Ahtohallan, The North Mountain, Arendelle Castle, The Fjord",
    characters: [
      "Elsa",
      "Anna",
      "Kristoff",
      "Olaf",
      "Sven",
      "Hans",
      "Mattias",
      "Honeymaren",
      "Yelana",
      "The Nokk",
    ],
    settingPlaceholder: "e.g., Elsa's ice palace on the North Mountain, aurora borealis above",
  },
  {
    id: "encanto",
    name: "Encanto",
    category: "cartoons",
    canonRules:
      "The Madrigal family received magical gifts from a miracle tied to Abuela's sacrifice. Each family member has a unique gift (Luisa: strength, Isabela: flowers, Bruno: visions, etc.). Mirabel is the only Madrigal without a gift, which is central to the story. The Casita is alive and protective. Do not ignore the intergenerational trauma theme — Abuela's pressure on the family is the real conflict. Bruno was unfairly exiled. Maintain the warm, musical, Colombian-inspired tone.",
    locations:
      "The Casita, The Town (Encanto), Bruno's hidden room, Isabela's room, Luisa's room, The mountains, The river",
    characters: [
      "Mirabel Madrigal",
      "Bruno Madrigal",
      "Isabela Madrigal",
      "Luisa Madrigal",
      "Camilo Madrigal",
      "Dolores Madrigal",
      "Abuela Alma Madrigal",
      "Julieta Madrigal",
      "Pepa Madrigal",
      "Félix Madrigal",
      "Agustín Madrigal",
    ],
    settingPlaceholder: "e.g., The Casita's courtyard, tiles shifting underfoot, magic in the walls",
  },
  {
    id: "danny-phantom",
    name: "Danny Phantom",
    category: "cartoons",
    canonRules:
      "Danny Fenton is a half-ghost (halfa) who gained powers from a portal accident. The Ghost Zone is a dimension connected to the human world through portals. Ghosts have specific powers and obsessions. Danny's parents are ghost hunters who don't know his secret. Ectoplasm is the core substance of ghost biology. Do not ignore the secret identity tension. Maintain the blend of superhero action, teen comedy, and spooky adventure.",
    locations:
      "Amity Park, Fenton Works, Casper High School, The Ghost Zone, Vlad's mansion, The Nasty Burger, The Far Frozen",
    characters: [
      "Danny Fenton / Danny Phantom",
      "Sam Manson",
      "Tucker Foley",
      "Jazz Fenton",
      "Vlad Masters / Vlad Plasmius",
      "Jack Fenton",
      "Maddie Fenton",
      "Dash Baxter",
      "Valerie Gray",
      "Ember McLain",
      "Skulker",
      "Clockwork",
    ],
    settingPlaceholder: "e.g., The Fenton lab, the Ghost Portal humming with eerie green light",
  },
  {
    id: "transformers",
    name: "Transformers",
    category: "cartoons",
    canonRules:
      "Autobots and Decepticons are sentient robots from Cybertron, divided by ideology. Transformers convert between robot and vehicle/beast modes. Energon is the lifeblood and fuel source. The AllSpark and Matrix of Leadership are sacred artifacts. Optimus Prime embodies heroic leadership; Megatron is tyrannical ambition. Can draw from G1, Beast Wars, Prime, Animated, or other continuities — specify which. Do not mix continuities without noting it as crossover.",
    locations:
      "Cybertron, The Ark, The Nemesis, Autobot Base, Various Earth locations, Vector Sigma, Iacon, Kaon",
    characters: [
      "Optimus Prime",
      "Megatron",
      "Bumblebee",
      "Starscream",
      "Soundwave",
      "Ratchet",
      "Arcee",
      "Wheeljack",
      "Shockwave",
      "Grimlock",
      "Ultra Magnus",
      "Prowl",
    ],
    settingPlaceholder: "e.g., The ruins of Iacon, Cybertron's two moons casting long shadows",
  },
  {
    id: "lego-ninjago",
    name: "LEGO Ninjago",
    category: "cartoons",
    canonRules:
      "The ninja team wields Elemental Powers (Fire, Ice, Lightning, Earth, Energy, Water). Spinjitzu and Airjitzu are specific martial arts techniques. The ninja are trained by Master Wu. Each season introduces new villains and power-ups. The First Spinjitzu Master created Ninjago. Do not mix up which ninja controls which element. Maintain the adventurous, humorous tone with genuine emotional stakes and brotherhood themes.",
    locations:
      "Ninjago City, The Monastery of Spinjitzu, The Underworld, The Dark Island, Cloud Kingdom, The Realm of Oni and Dragons",
    characters: [
      "Lloyd Garmadon",
      "Kai",
      "Jay",
      "Cole",
      "Zane",
      "Nya",
      "Master Wu",
      "Lord Garmadon",
      "Sensei Garmadon",
      "Pixal / P.I.X.A.L.",
      "Skylor",
    ],
    settingPlaceholder: "e.g., The Monastery of Spinjitzu, training at sunrise on the mountain",
  },
];
