import { FandomConfig } from "../../types/fandom";

export const FILM_TV_FANDOMS: FandomConfig[] = [
  {
    id: "marvel",
    name: "Marvel (MCU)",
    category: "films-tv",
    canonRules:
      "Follow MCU canon (not comics unless specified). Respect character power levels, relationships, and timeline events. Can be set pre or post-Endgame. Do not give characters abilities they don't have in the films. Maintain the blend of action and character drama.",
    locations:
      "Avengers Tower, Wakanda, Asgard, Sanctum Sanctorum, S.H.I.E.L.D. facilities, The Compound, Kamar-Taj",
    characters: [
      "Tony Stark / Iron Man",
      "Steve Rogers / Captain America",
      "Bucky Barnes / Winter Soldier",
      "Natasha Romanoff / Black Widow",
      "Loki",
      "Thor",
      "Peter Parker / Spider-Man",
      "Wanda Maximoff / Scarlet Witch",
      "Stephen Strange",
      "Sam Wilson / Falcon",
      "Clint Barton / Hawkeye",
      "Bruce Banner / Hulk",
      "Pepper Potts",
      "Wade Wilson / Deadpool",
      "Matt Murdock / Daredevil",
      "Logan / Wolverine",
      "Scott Lang / Ant-Man",
      "T'Challa / Black Panther",
      "Carol Danvers / Captain Marvel",
      "Shuri",
      "Vision",
      "Pietro Maximoff / Quicksilver",
      "Peggy Carter",
      "Darcy Lewis",
      "Nick Fury",
      "Phil Coulson",
      "Gamora",
      "Nebula",
      "Rocket Raccoon",
      "Groot",
      "Maria Hill",
      "Peter Quill / Star-Lord",
      "Drax",
      "Mantis",
      "Valkyrie",
      "Hela",
      "Thanos",
      "Yelena Belova",
      "Kate Bishop",
      "Monica Rambeau",
      "Shang-Chi",
      "Moon Knight / Marc Spector / Steven Grant",
      "Erik Killmonger",
      "Agatha Harkness",
      "Okoye",
      "Nakia",
      "Wong",
      "Brock Rumlow / Crossbones",
      "Wenwu",
      "James Rhodes / War Machine",
      "Hope Van Dyne / Wasp",
      "Jane Foster",
      "Sylvie",
      "Kamala Khan / Ms. Marvel",
      "America Chavez",
    ],
    settingPlaceholder: "e.g., Avengers Tower common room, post-Endgame",
  },
  {
    id: "star-wars",
    name: "Star Wars",
    category: "films-tv",
    canonRules:
      "Follow Star Wars universe rules. Respect the Force (Light/Dark), Jedi/Sith dynamics, galactic politics. Can be set in any era (Old Republic, Clone Wars, Empire, Sequel). Do not mix era-specific technology or characters without justification. Maintain space opera tone.",
    locations:
      "Coruscant, Tatooine, Naboo, Death Star, Mandalore, Dagobah, Ahch-To, Mustafar, Hoth",
    era: "Can be set in any era (Old Republic, Prequel, Clone Wars, Original Trilogy, Sequel, Mandalorian)",
    characters: [
      "Anakin Skywalker / Darth Vader",
      "Obi-Wan Kenobi",
      "Luke Skywalker",
      "Leia Organa",
      "Han Solo",
      "Din Djarin / The Mandalorian",
      "Ahsoka Tano",
      "Padmé Amidala",
      "Kylo Ren / Ben Solo",
      "Rey",
      "Grogu",
      "Emperor Palpatine / Darth Sidious",
      "Finn",
      "Poe Dameron",
      "Chewbacca",
      "Lando Calrissian",
      "Mace Windu",
      "Yoda",
      "Qui-Gon Jinn",
      "Count Dooku / Darth Tyranus",
      "Darth Maul",
      "General Grievous",
      "Captain Rex",
      "Commander Cody",
      "Hux",
      "Bo-Katan Kryze",
      "Cad Bane",
      "Boba Fett",
      "Fennec Shand",
      "Hera Syndulla",
      "Kanan Jarrus",
      "Ezra Bridger",
      "Sabine Wren",
      "Asajj Ventress",
      "Rose Tico",
      "Jyn Erso",
      "Cassian Andor",
      "K-2SO",
      "Grand Admiral Thrawn",
      "Mon Mothma",
      "Saw Gerrera",
      "Chirrut Îmwe",
      "Baze Malbus",
      "Barriss Offee",
      "Luminara Unduli",
      "Plo Koon",
      "Kit Fisto",
      "Aayla Secura",
      "Cere Junda",
      "Cal Kestis",
      "The Armorer",
      "Omega",
      "Hunter (Bad Batch)",
      "Crosshair (Bad Batch)",
    ],
    settingPlaceholder: "e.g., Mos Eisley cantina, during the Clone Wars",
  },
  {
    id: "supernatural",
    name: "Supernatural",
    category: "films-tv",
    canonRules:
      "Follow Supernatural's monster-of-the-week and overarching mythology. Salt, iron, and silver have specific uses against specific creatures. Respect the angel/demon hierarchy, the Men of Letters lore, and the Winchester family trauma. Baby (the '67 Impala) is sacred. Do not kill characters casually — death has complex rules in this universe.",
    locations:
      "The Bunker, Bobby's House, The Impala, Heaven, Hell, Purgatory, Various motels across America",
    characters: [
      "Dean Winchester",
      "Sam Winchester",
      "Castiel",
      "Crowley",
      "Bobby Singer",
      "Jack Kline",
      "Rowena MacLeod",
      "Charlie Bradbury",
      "Gabriel",
      "Lucifer",
      "Mary Winchester",
      "John Winchester",
      "Meg Masters",
      "Ruby",
      "Benny Lafitte",
      "Balthazar",
      "Kevin Tran",
      "Donna Hanscum",
      "Jody Mills",
      "Ellen Harvelle",
      "Jo Harvelle",
      "Ash",
      "Adam Milligan",
      "Amara / The Darkness",
      "Chuck Shurley / God",
      "Death",
      "Michael",
      "Lilith",
      "Azazel / Yellow Eyes",
      "Garth Fitzgerald IV",
    ],
    settingPlaceholder: "e.g., The Bunker's library, late night research session",
  },
  {
    id: "sherlock-bbc",
    name: "Sherlock (BBC)",
    category: "films-tv",
    canonRules:
      "Follow the BBC Sherlock modern-day London setting. Sherlock is a high-functioning sociopath (his words) with extraordinary deductive abilities. Watson is a military veteran and blogger. Respect the character dynamics: Sherlock/John's partnership, Mycroft's government role, Moriarty's chaotic genius. Do not write Sherlock as emotionless — he suppresses emotions, he has them.",
    locations:
      "221B Baker Street, St. Bartholomew's Hospital, Scotland Yard, The Diogenes Club, Speedy's Café, Appledore",
    characters: [
      "Sherlock Holmes",
      "John Watson",
      "Jim Moriarty",
      "Mycroft Holmes",
      "Greg Lestrade",
      "Molly Hooper",
      "Mrs. Hudson",
      "Irene Adler",
      "Mary Morstan",
      "Eurus Holmes",
      "Sally Donovan",
      "Philip Anderson",
      "Sebastian Moran",
      "Anthea",
      "Mike Stamford",
      "Janine Hawkins",
      "Charles Augustus Magnussen",
      "Henry Knight",
      "Kitty Riley",
      "Victor Trevor",
      "Archie",
      "Bill Wiggins",
      "Lady Smallwood",
      "Culverton Smith",
      "Rosie Watson",
    ],
    settingPlaceholder: "e.g., 221B Baker Street, Sherlock composing at 2 AM",
  },
  {
    id: "teen-wolf",
    name: "Teen Wolf",
    category: "films-tv",
    canonRules:
      "Follow Teen Wolf's supernatural rules. Werewolf transformation is tied to the full moon and anchors. Alpha/Beta/Omega pack dynamics matter. Mountain ash blocks supernatural creatures. Respect the Hale family history and the Nemeton's power. Beacon Hills is a supernatural beacon. Do not ignore the anchor concept — it's what keeps wolves human.",
    locations:
      "Beacon Hills, Beacon Hills High School, The Hale House, The Nemeton, Eichen House, The Preserve, The Animal Clinic",
    characters: [
      "Stiles Stilinski",
      "Derek Hale",
      "Scott McCall",
      "Lydia Martin",
      "Allison Argent",
      "Isaac Lahey",
      "Peter Hale",
      "Jackson Whittemore",
      "Malia Tate",
      "Kira Yukimura",
      "Theo Raeken",
      "Liam Dunbar",
      "Danny Mahealani",
      "Erica Reyes",
      "Boyd (Vernon Boyd)",
      "Ethan",
      "Aiden",
      "Chris Argent",
      "Sheriff Stilinski",
      "Melissa McCall",
      "Jordan Parrish",
      "Deucalion",
      "Kate Argent",
      "Gerard Argent",
      "Cora Hale",
      "Mason Hewitt",
      "Corey Bryant",
      "Noshiko Yukimura",
      "Braeden",
      "Jennifer Blake / The Darach",
    ],
    settingPlaceholder: "e.g., The burned-out Hale house, full moon rising",
  },
  {
    id: "game-of-thrones",
    name: "Game of Thrones",
    category: "films-tv",
    canonRules:
      "Follow the HBO show canon for Game of Thrones (not the books, which have a separate entry). Respect house allegiances, the Wall, dragons, and the complex morality of the world. Mature themes (violence, politics, romance) are central. No character is safe. Do not use book-only characters or plotlines without flagging it as AU.",
    locations:
      "King's Landing, Winterfell, The Wall, Dragonstone, Braavos, The Red Keep, Castle Black, Meereen",
    characters: [
      "Jon Snow",
      "Daenerys Targaryen",
      "Tyrion Lannister",
      "Cersei Lannister",
      "Jaime Lannister",
      "Arya Stark",
      "Sansa Stark",
      "Brienne of Tarth",
      "Sandor Clegane / The Hound",
      "Tormund Giantsbane",
      "Margaery Tyrell",
      "Theon Greyjoy",
      "Missandei",
      "Oberyn Martell",
      "Petyr Baelish / Littlefinger",
      "Varys",
      "Robb Stark",
      "Bran Stark",
      "Catelyn Stark",
      "Ned Stark",
      "Jorah Mormont",
      "Grey Worm",
      "Davos Seaworth",
      "Melisandre",
      "Stannis Baratheon",
      "Samwell Tarly",
      "Gilly",
      "Ygritte",
      "Bronn",
      "Olenna Tyrell",
      "Loras Tyrell",
      "Ramsay Bolton",
      "Tywin Lannister",
      "The Night King",
      "Podrick Payne",
      "Jaqen H'ghar",
      "Gregor Clegane / The Mountain",
      "Euron Greyjoy",
    ],
    settingPlaceholder: "e.g., The Red Keep, during the War of the Five Kings",
  },
  {
    id: "stranger-things",
    name: "Stranger Things",
    category: "films-tv",
    canonRules:
      "Set in 1980s Hawkins, Indiana. Respect the Upside Down mythology, Eleven's powers, and the group dynamics. Use 80s cultural references. Do not use modern technology, slang, or internet culture. Maintain the blend of horror, sci-fi, and coming-of-age.",
    locations:
      "Hawkins, The Upside Down, Hawkins Lab, Starcourt Mall, The Wheeler House, The Byers House, Skull Rock",
    characters: [
      "Eleven / Jane Hopper",
      "Mike Wheeler",
      "Dustin Henderson",
      "Lucas Sinclair",
      "Will Byers",
      "Steve Harrington",
      "Robin Buckley",
      "Nancy Wheeler",
      "Jonathan Byers",
      "Max Mayfield",
      "Eddie Munson",
      "Jim Hopper",
      "Billy Hargrove",
      "Joyce Byers",
      "Murray Bauman",
      "Argyle",
      "Erica Sinclair",
      "Karen Wheeler",
      "Bob Newby",
      "Dr. Martin Brenner",
      "Vecna / Henry Creel / One",
      "Suzie Bingham",
      "Dmitri 'Enzo' Antonov",
      "Jason Carver",
      "Chrissy Cunningham",
      "Fred Benson",
      "Scott Clarke",
      "Tommy H.",
      "Barbara Holland",
    ],
    settingPlaceholder: "e.g., Hawkins, summer of 1985",
  },
  {
    id: "good-omens-tv",
    name: "Good Omens (TV)",
    category: "films-tv",
    canonRules:
      "Follow the Amazon Prime adaptation's canon and characterisation. Aziraphale (Michael Sheen) is a fussy, gentle angel; Crowley (David Tennant) is a lanky, dramatic demon. Their 6,000-year relationship is the heart of the story. Respect the show's specific scenes and dynamics (the bookshop, the Bentley, the Ritz). Maintain the warm, witty British comedic tone.",
    locations:
      "Aziraphale's Bookshop (Soho), Crowley's Flat (Mayfair), The Ritz, Tadfield, Heaven, Hell, St. James's Park, Edinburgh",
    characters: [
      "Aziraphale",
      "Crowley",
      "Gabriel",
      "Beelzebub",
      "Maggie",
      "Nina",
      "Muriel",
      "Shax",
      "Metatron",
      "Adam Young",
      "Anathema Device",
      "Jim / Gabriel",
      "Newton Pulsifer",
      "Sergeant Shadwell",
      "Madame Tracy",
      "Saraqael",
      "Furfur",
      "Pepper (Pippin Galadriel Moonchild)",
      "Wensleydale",
      "Brian",
      "Dog",
      "Michael (Archangel)",
      "Uriel",
      "Dagon",
      "Hastur",
      "Ligur",
      "Eric (Disposable Demon)",
    ],
    settingPlaceholder: "e.g., The back room of the bookshop, a bottle of wine between them",
  },
  {
    id: "hannibal",
    name: "Hannibal",
    category: "films-tv",
    canonRules:
      "Follow the NBC Hannibal series canon. Will Graham is an empath who reconstructs crimes — respect his gift and its psychological cost. Hannibal Lecter is a refined cannibal psychiatrist. Their relationship is the core of the show. Use the show's baroque, sensory-rich aesthetic. Food descriptions should be elaborate and unsettling. Do not make the violence gratuitous without purpose — it is always artistic in this world.",
    locations:
      "Hannibal's Office, Will's House (Wolf Trap, Virginia), The FBI Academy (Quantico), Hannibal's Kitchen, The BSHCI, Florence",
    characters: [
      "Hannibal Lecter",
      "Will Graham",
      "Bedelia Du Maurier",
      "Jack Crawford",
      "Alana Bloom",
      "Abigail Hobbs",
      "Margot Verger",
      "Frederick Chilton",
      "Beverly Katz",
      "Francis Dolarhyde",
      "Jimmy Price",
      "Brian Zeller",
      "Mason Verger",
      "Bella Crawford",
      "Chiyoh",
      "Reba McClane",
      "Franklyn Froideveaux",
      "Tobias Budge",
      "Garrett Jacob Hobbs",
      "Matthew Brown",
      "Anthony Dimmond",
      "Rinaldo Pazzi",
      "Molly Graham",
      "Cordell Doemling",
    ],
    settingPlaceholder: "e.g., Hannibal's dining room, an exquisite meal with darker implications",
  },
  {
    id: "wednesday",
    name: "Wednesday",
    category: "films-tv",
    canonRules:
      "Follow the Netflix Wednesday series canon. Wednesday Addams is deadpan, morbid, and brilliant. Nevermore Academy is a school for outcasts with supernatural abilities. Respect the mystery-thriller structure and Wednesday's psychic visions. Do not make Wednesday overly emotional or warm — her growth is subtle. The Addams Family dynamics (especially with Enid) are central.",
    locations:
      "Nevermore Academy, Jericho (town), The Weathervane café, Ophelia Hall, The Poe Cup lake, The Addams Mansion",
    characters: [
      "Wednesday Addams",
      "Enid Sinclair",
      "Tyler Galpin",
      "Bianca Barclay",
      "Xavier Thorpe",
      "Eugene Otinger",
      "Thing",
      "Morticia Addams",
      "Gomez Addams",
      "Principal Weems",
      "Ajax Petropolus",
      "Pugsley Addams",
      "Uncle Fester",
      "Yoko Tanaka",
      "Divina",
      "Kent",
      "Ms. Thornhill / Laurel Gates",
      "Sheriff Galpin",
      "Marilyn Thornhill",
      "Lucas Walker",
      "Lurch",
      "Rowan",
      "Valerie Kinbott",
    ],
    settingPlaceholder: "e.g., Wednesday's dorm room at Nevermore, cello practice at midnight",
  },
  {
    id: "merlin-bbc",
    name: "Merlin (BBC)",
    category: "films-tv",
    canonRules:
      "Follow BBC Merlin's canon. Magic is banned in Camelot under Uther's rule. Merlin must hide his powers. Arthur starts arrogant but grows into a just king. Respect the destiny/prophecy framework (two sides of the same coin). Do not reveal Merlin's magic to Arthur prematurely unless that's the story's premise. The medieval setting should feel lived-in, not sanitized.",
    locations:
      "Camelot, The Castle, Gaius's Chambers, The Isle of the Blessed, The Crystal Cave, Ealdor, The Forest of Balor",
    characters: [
      "Merlin",
      "Arthur Pendragon",
      "Morgana",
      "Gwen / Guinevere",
      "Gaius",
      "Uther Pendragon",
      "Lancelot",
      "Gwaine",
      "Percival",
      "Leon",
      "Mordred",
      "Kilgharrah (The Great Dragon)",
      "Elyan",
      "Morgause",
      "Nimueh",
      "Hunith",
      "Agravaine",
      "Freya",
      "Aithusa",
      "Tristan",
      "Isolde",
      "Cenred",
      "Balinor",
      "Sefa",
      "Daegal",
      "George (Merlin's replacement)",
      "Will (Ealdor)",
      "Mithian",
      "Vivian",
    ],
    settingPlaceholder: "e.g., Arthur's chambers, Merlin polishing armour while hiding a spell",
  },
  {
    id: "umbrella-academy",
    name: "The Umbrella Academy",
    category: "films-tv",
    canonRules:
      "Follow the Netflix series canon. The Hargreeves siblings each have unique powers (except Vanya/Viktor's are suppressed, then unleashed). Respect the dysfunctional family dynamics and timeline disruption consequences. The Commission enforces the timeline. Do not ignore the trauma Reginald inflicted. Each sibling is designated by number.",
    locations:
      "The Umbrella Academy (Hargreeves Mansion), The Commission, Hotel Obsidian, Griddy's Doughnuts, The Sparrow Academy",
    characters: [
      "Five",
      "Klaus Hargreeves",
      "Viktor Hargreeves",
      "Diego Hargreeves",
      "Allison Hargreeves",
      "Luther Hargreeves",
      "Ben Hargreeves",
      "Lila Pitts",
      "The Handler",
      "Reginald Hargreeves",
      "Hazel",
      "Cha-Cha",
      "Grace / Mom",
      "Pogo",
      "Herb",
      "Dot",
      "Sissy Cooper",
      "Raymond Chestnut",
      "Sparrow Ben",
      "Fei Hargreeves",
      "Sloane Hargreeves",
      "Marcus Hargreeves",
      "Jayme Hargreeves",
      "Alphonso Hargreeves",
      "Christopher Hargreeves",
      "Leonard Peabody / Harold Jenkins",
      "Agnes",
    ],
    settingPlaceholder: "e.g., The Academy living room, siblings arguing about the apocalypse",
  },
  {
    id: "bridgerton",
    name: "Bridgerton",
    category: "films-tv",
    canonRules:
      "Follow the Netflix Bridgerton Regency-era setting. Respect the ton's social rules, the marriage market, and the Bridgerton family dynamics. Lady Whistledown's gossip sheet drives social consequences. Do not use modern speech patterns in dialogue (narration can be more relaxed). The show's diverse casting is canon — do not erase it. Romance is the genre — lean into it.",
    locations:
      "Mayfair, The Bridgerton House, Aubrey Hall, Almack's, The Featherington House, The Ton's ballrooms, Hyde Park",
    characters: [
      "Anthony Bridgerton",
      "Kate Sharma",
      "Benedict Bridgerton",
      "Colin Bridgerton",
      "Penelope Featherington",
      "Eloise Bridgerton",
      "Simon Basset (Duke of Hastings)",
      "Daphne Bridgerton",
      "Francesca Bridgerton",
      "Lady Danbury",
      "Queen Charlotte",
      "Lady Whistledown",
      "Gregory Bridgerton",
      "Hyacinth Bridgerton",
      "Violet Bridgerton",
      "Marina Thompson",
      "Portia Featherington",
      "Prudence Featherington",
      "Philippa Featherington",
      "Cressida Cowper",
      "Will Mondrich",
      "Jack (Lord Featherington)",
      "Lady Mary Sheffield",
      "John Stirling (Marquess of Kilmartin)",
      "Michaela Stirling",
      "Lord Debling",
      "Alice Mondrich",
    ],
    settingPlaceholder: "e.g., A candlelit ball at Aubrey Hall, the season's opening night",
  },
  {
    id: "the-100",
    name: "The 100",
    category: "films-tv",
    canonRules:
      "Follow The 100's post-apocalyptic Earth rules. Nuclear apocalypse forced survivors onto the Ark space station. The 100 delinquents were sent to test Earth's survivability. Respect Grounder culture, the Flame / Commander lineage, and the moral dilemmas. 'Jus drein jus daun' — blood must have blood. Do not simplify the moral grey areas — every leader makes terrible choices.",
    locations:
      "The Ark, Camp Jaha / Arkadia, Polis, Mount Weather, TonDC, The Dead Zone, Sanctum, Bardo",
    characters: [
      "Clarke Griffin",
      "Bellamy Blake",
      "Octavia Blake",
      "Lexa",
      "Raven Reyes",
      "Murphy",
      "Jasper Jordan",
      "Monty Green",
      "Lincoln",
      "Abby Griffin",
      "Kane",
      "Indra",
      "Echo",
      "Emori",
      "Harper McIntyre",
      "Niylah",
      "Anya",
      "Thelonious Jaha",
      "Wells Jaha",
      "Luna",
      "Finn Collins",
      "Madi Griffin",
      "Diyoza",
      "Gabriel Santiago",
      "Josephine Lightbourne",
      "Russell Lightbourne",
      "Hope Diyoza",
      "Jordan Green",
      "Miller (Nathan Miller)",
    ],
    settingPlaceholder: "e.g., The dropship camp, first night on the ground",
  },
  {
    id: "our-flag-means-death",
    name: "Our Flag Means Death",
    category: "films-tv",
    canonRules:
      "Follow the HBO Max series canon. Stede Bonnet is a genteel aristocrat playing pirate; Blackbeard (Ed Teach) is legendary but weary of his reputation. Their romance is the heart of the show. Respect the comedic, anachronistic tone — it's historical fantasy, not a documentary. The crew's found family dynamic is essential. Do not make it grimdark — even the violence is played with humor.",
    locations:
      "The Revenge (ship), The Queen Anne's Revenge, The Republic of Pirates, Stede's Estate, The Open Sea, Various ports",
    characters: [
      "Stede Bonnet",
      "Blackbeard / Ed Teach",
      "Izzy Hands",
      "Jim Jimenez",
      "Oluwande Boodhari",
      "Lucius Spriggs",
      "Black Pete",
      "The Swede",
      "Frenchie",
      "Zheng Yi Sao",
      "Roach",
      "Wee John Feeney",
      "Buttons",
      "Archie",
      "Mary Bonnet",
      "Spanish Jackie",
      "Calico Jack",
      "Ivan",
      "Auntie",
      "Ned Low",
      "Chauncey Badminton",
      "Doug",
      "Alma",
      "Ricky",
      "Prince Ricky",
    ],
    settingPlaceholder: "e.g., The captain's quarters of The Revenge, sunset at sea",
  },
  {
    id: "buffy",
    name: "Buffy the Vampire Slayer",
    category: "films-tv",
    canonRules:
      "Follow the Buffyverse rules. The Slayer is one girl in all the world chosen to fight vampires, demons, and the forces of darkness (until the S7 finale). Vampires dust when staked through the heart. Respect the Watcher/Slayer dynamic and the Scooby Gang's teamwork. Sunnydale sits on a Hellmouth. Maintain the signature blend of horror, humor, and heart. Buffy-speak is a specific dialect — 'the big bad,' 'wiggins,' etc.",
    locations:
      "Sunnydale, The Bronze, Sunnydale High Library, Buffy's House, The Magic Box, Spike's Crypt, UC Sunnydale, The Hellmouth",
    characters: [
      "Buffy Summers",
      "Spike",
      "Angel",
      "Willow Rosenberg",
      "Xander Harris",
      "Rupert Giles",
      "Faith Lehane",
      "Anya Jenkins",
      "Oz",
      "Tara Maclay",
      "Dawn Summers",
      "Cordelia Chase",
      "Wesley Wyndam-Pryce",
      "Drusilla",
      "Darla",
      "Andrew Wells",
      "Jonathan Levinson",
      "Warren Mears",
      "Glory / Glorificus",
      "Joyce Summers",
      "Jenny Calendar",
      "Ethan Rayne",
      "Kendra Young",
      "Robin Wood",
      "Kennedy",
      "Riley Finn",
      "Harmony Kendall",
      "Clem",
      "The First Evil",
      "The Master",
    ],
    settingPlaceholder: "e.g., Sunnydale cemetery, patrol night with a quip-ready Slayer",
  },
  {
    id: "doctor-who",
    name: "Doctor Who",
    category: "films-tv",
    canonRules:
      "Follow Doctor Who's established rules. The Doctor is a Time Lord from Gallifrey who regenerates into new forms. The TARDIS is bigger on the inside and is semi-sentient. Fixed points in time cannot be changed. Respect whichever Doctor's era you're writing. Companions are the emotional heart. Do not make the sonic screwdriver a magic wand for everything — it doesn't work on wood.",
    locations:
      "The TARDIS, Gallifrey, Earth (various eras), Skaro, New Earth, Trenzalore, The Time Vortex",
    era: "Can be set in any Doctor's era (Classic or New Who)",
    characters: [
      "The Doctor (specify incarnation)",
      "Rose Tyler",
      "Martha Jones",
      "Donna Noble",
      "Amy Pond",
      "Rory Williams",
      "Clara Oswald",
      "River Song",
      "Captain Jack Harkness",
      "The Master / Missy",
      "Sarah Jane Smith",
      "Bill Potts",
      "Yaz / Yasmin Khan",
      "Dan Lewis",
      "Graham O'Brien",
      "Ryan Sinclair",
      "Nardole",
      "The Thirteenth Doctor",
      "The Tenth Doctor",
      "The Eleventh Doctor",
      "The Twelfth Doctor",
      "The Ninth Doctor",
      "The Fourteenth Doctor",
      "The Fifteenth Doctor",
      "Mickey Smith",
      "Jackie Tyler",
      "Wilfred Mott",
      "The Rani",
      "Davros",
      "Kate Stewart",
      "Ace McShane",
      "Tegan Jovanka",
      "Ruby Sunday",
    ],
    settingPlaceholder: "e.g., The TARDIS console room, mid-flight to an unknown planet",
  },
  {
    id: "lucifer",
    name: "Lucifer",
    category: "films-tv",
    canonRules:
      "Follow the Netflix/Fox Lucifer series canon. Lucifer Morningstar left Hell to run a nightclub in LA. He is charming, hedonistic, and uses 'desire mojo' (not mind control). Chloe makes him vulnerable (literally). Respect the celestial family dynamics and the police procedural format. Do not make Lucifer evil — he punishes evil, he doesn't cause it.",
    locations:
      "Lux (nightclub), The LAPD Precinct, Lucifer's Penthouse, Hell, The Silver City, Linda's Office, Chloe's Apartment",
    characters: [
      "Lucifer Morningstar",
      "Chloe Decker",
      "Mazikeen / Maze",
      "Amenadiel",
      "Dan Espinoza",
      "Ella Lopez",
      "Linda Martin",
      "Trixie Espinoza",
      "Eve",
      "Michael",
      "God (Dennis Haysbert version)",
      "Charlotte Richards",
      "Goddess / Charlotte",
      "Cain / Marcus Pierce",
      "Azrael",
      "Remiel",
      "Rory (Aurora Morningstar)",
      "Malcolm Graham",
      "Ella's Ghost (Rae-Rae / Azrael)",
      "Le Mec / Vincent Le Mec",
    ],
    settingPlaceholder: "e.g., The balcony of Lux, Lucifer with a glass of whiskey at dawn",
  },
  {
    id: "schitts-creek",
    name: "Schitt's Creek",
    category: "films-tv",
    canonRules:
      "Follow the CBC/Pop TV series canon. The Rose family lost their fortune and now live in a small town. Respect each character's growth arc — David's vulnerability beneath the sarcasm, Alexis's journey to independence, Johnny's quiet dignity, Moira's theatrical grandeur. Do not undo their character development. The town is accepting — queer relationships are never questioned.",
    locations:
      "The Rosebud Motel, Rose Apothecary, Café Tropical, Town Hall, Bob's Garage, The Wobbly Elm, The Hospice Thrift Store",
    characters: [
      "David Rose",
      "Patrick Brewer",
      "Alexis Rose",
      "Moira Rose",
      "Johnny Rose",
      "Stevie Budd",
      "Ted Mullens",
      "Roland Schitt",
      "Twyla Sands",
      "Ronnie Lee",
      "Bob Currie",
      "Ray Butani",
      "Jocelyn Schitt",
      "Mutt Schitt",
      "Jake",
      "Ken",
    ],
    settingPlaceholder: "e.g., Rose Apothecary after closing, David rearranging products",
  },
  {
    id: "ted-lasso",
    name: "Ted Lasso",
    category: "films-tv",
    canonRules:
      "Follow the Apple TV+ series canon. Ted Lasso is an American football coach managing an English Premier League team. His relentless optimism is genuine, not naive. Respect the football (soccer) setting and terminology. Richmond FC matters to its fans. Do not reduce Ted to a caricature — he deals with real anxiety and panic attacks. The ensemble cast is a strength.",
    locations:
      "Nelson Road (Richmond FC stadium), The Coaching Office, The Crown & Anchor pub, The Locker Room, Ted's Apartment, Rebecca's Office",
    characters: [
      "Ted Lasso",
      "Rebecca Welton",
      "Roy Kent",
      "Keeley Jones",
      "Jamie Tartt",
      "Sam Obisanya",
      "Coach Beard",
      "Nate Shelley",
      "Higgins",
      "Trent Crimm",
      "Dani Rojas",
      "Isaac McAdoo",
      "Jan Maas",
      "Colin Hughes",
      "Richard Montlaur",
      "Zava",
      "Phoebe",
      "Sassy Collins",
      "Rupert Mannion",
      "Bex",
      "Jack",
      "Dr. Sharon Fieldstone",
    ],
    settingPlaceholder: "e.g., The coaching office, Ted making biscuits before a big match",
  },
  {
    id: "top-gun",
    name: "Top Gun",
    category: "films-tv",
    canonRules:
      "Follow the Top Gun film canon (original and Maverick). Respect Navy aviation terminology, call signs, and the competitive fighter pilot culture. Maverick is the best pilot but a rule-breaker. Rooster carries his father's legacy. Do not ignore the danger — people die in these jets. Maintain the high-octane, emotionally charged tone. The volleyball/beach football scene energy is part of the fandom.",
    locations:
      "TOPGUN (Naval Fighter Weapons School), The Hard Deck bar, The Aircraft Carrier, The Flight Line, Maverick's Hangar",
    characters: [
      "Pete 'Maverick' Mitchell",
      "Bradley 'Rooster' Bradshaw",
      "Jake 'Hangman' Seresin",
      "Tom 'Iceman' Kazansky",
      "Penny Benjamin",
      "Bob Floyd",
      "Phoenix (Natasha Trace)",
      "Nick 'Goose' Bradshaw",
      "Charlie Blackwood",
      "Admiral Beau 'Cyclone' Simpson",
      "Fanboy (Mickey Garcia)",
      "Payback (Reuben Fitch)",
      "Coyote (Javy Machado)",
      "Hondo",
      "Amelia Benjamin",
      "Viper (Tom Jardian)",
      "Merlin",
      "Wolfman",
      "Slider",
      "Jester",
      "Carole Bradshaw",
    ],
    settingPlaceholder: "e.g., The Hard Deck bar, flight suits and pool table rivalries",
  },
  {
    id: "criminal-minds",
    name: "Criminal Minds",
    category: "films-tv",
    canonRules:
      "Follow the CBS Criminal Minds series canon. The BAU (Behavioral Analysis Unit) profiles serial criminals. Respect the profiling methodology — it's psychology-based, not psychic. Each team member has a specialty. Reid's genius and social awkwardness are specific traits. Do not turn the unsubs into cartoonish villains — the show's strength is understanding criminal psychology. Use the 'wheels up' structure.",
    locations:
      "BAU Headquarters (Quantico), The BAU Jet, Various crime scenes across America, Garcia's Tech Lair, Local police stations",
    characters: [
      "Spencer Reid",
      "Derek Morgan",
      "Aaron Hotchner",
      "Penelope Garcia",
      "Emily Prentiss",
      "Jennifer 'JJ' Jareau",
      "David Rossi",
      "Elle Greenaway",
      "Jason Gideon",
      "Luke Alvez",
      "Matt Simmons",
      "Tara Lewis",
      "Kate Callahan",
      "Ashley Seaver",
      "Alex Blake",
      "Jordan Todd",
      "Stephen Walker",
      "Max Ryan",
      "Haley Hotchner",
      "Jack Hotchner",
      "Savannah Hayes",
      "Will LaMontagne",
      "Henry LaMontagne",
      "Kevin Lynch",
      "Erin Strauss",
      "The Replicator",
      "George Foyet / The Reaper",
      "Tobias Hankel",
      "Diana Reid",
    ],
    settingPlaceholder: "e.g., The BAU bullpen, case files spread across Reid's desk",
  },
  {
    id: "glee",
    name: "Glee",
    category: "films-tv",
    canonRules:
      "Follow the Fox Glee series canon. New Directions is a high school glee club at McKinley High in Lima, Ohio. Respect the musical performance format — characters express emotions through song. The social hierarchy (jocks, cheerleaders, glee kids) drives conflict. Do not ignore the show's themes of acceptance, identity, and found family. Ships are extremely important in this fandom.",
    locations:
      "McKinley High School, The Choir Room, The Auditorium, Lima (Ohio), Breadstix, Dalton Academy, NYADA, New York",
    characters: [
      "Kurt Hummel",
      "Blaine Anderson",
      "Rachel Berry",
      "Finn Hudson",
      "Santana Lopez",
      "Brittany Pierce",
      "Quinn Fabray",
      "Mercedes Jones",
      "Sam Evans",
      "Puck (Noah Puckerman)",
      "Mr. Schuester",
      "Sue Sylvester",
      "Tina Cohen-Chang",
      "Mike Chang",
      "Artie Abrams",
      "Jessie St. James",
      "Sebastian Smythe",
      "Elliott 'Starchild' Gilbert",
      "Marley Rose",
      "Jake Puckerman",
      "Kitty Wilde",
      "Ryder Lynn",
      "Unique Adams",
      "Emma Pillsbury",
      "Shannon Beiste",
      "Sugar Motta",
      "Burt Hummel",
      "Carole Hudson",
      "Lauren Zizes",
    ],
    settingPlaceholder: "e.g., The McKinley choir room, rehearsals for Sectionals",
  },
  {
    id: "vampire-diaries",
    name: "The Vampire Diaries",
    category: "films-tv",
    canonRules:
      "Follow The Vampire Diaries TV show canon. Vampires are created by dying with vampire blood in their system; they must complete the transition by feeding. Vervain protects against compulsion. Respect the Originals hierarchy (they cannot be killed by normal means). The sire bond and doppelgänger mythology are complex — get them right. Mystic Falls has a founding family legacy.",
    locations:
      "Mystic Falls, The Salvatore Boarding House, Mystic Falls High, The Mystic Grill, Whitmore College, The Other Side, New Orleans",
    characters: [
      "Damon Salvatore",
      "Stefan Salvatore",
      "Elena Gilbert",
      "Caroline Forbes",
      "Klaus Mikaelson",
      "Bonnie Bennett",
      "Elijah Mikaelson",
      "Rebekah Mikaelson",
      "Katherine Pierce",
      "Matt Donovan",
      "Tyler Lockwood",
      "Alaric Saltzman",
      "Enzo St. John",
      "Kai Parker",
      "Jeremy Gilbert",
      "Jenna Sommers",
      "Lexi Branson",
      "Kol Mikaelson",
      "Freya Mikaelson",
      "Hayley Marshall",
      "Marcel Gerard",
      "Liv Parker",
      "Luke Parker",
      "Jo Laughlin",
      "Nora Hildegard",
      "Mary Louise",
      "Valerie Tulle",
      "Anna Zhu",
      "Liz Forbes",
    ],
    settingPlaceholder: "e.g., The Salvatore Boarding House parlour, bourbon and brooding",
  },
  {
    id: "the-walking-dead",
    name: "The Walking Dead",
    category: "films-tv",
    canonRules:
      "Follow The Walking Dead TV series canon. Walkers are drawn to sound and can only be killed by destroying the brain. Everyone is already infected — death by any cause means reanimation. Respect the community-building arcs (Alexandria, Hilltop, The Kingdom). The real threat is always other humans. Do not make surviving the apocalypse easy — resources are scarce, trust is earned.",
    locations:
      "Alexandria, The Prison, Hilltop, The Kingdom, Woodbury, Terminus, The Sanctuary, The Commonwealth",
    characters: [
      "Rick Grimes",
      "Daryl Dixon",
      "Michonne",
      "Negan",
      "Carol Peletier",
      "Glenn Rhee",
      "Maggie Greene",
      "Carl Grimes",
      "The Governor",
      "Abraham Ford",
      "Rosita Espinosa",
      "Eugene Porter",
      "Sasha Williams",
      "Beth Greene",
      "Hershel Greene",
      "Shane Walsh",
      "Morgan Jones",
      "Enid",
      "Jesus (Paul Rovia)",
      "Ezekiel",
      "Dwight",
      "Alpha",
      "Beta",
      "Lydia",
      "Tara Chambler",
      "Aaron",
      "Judith Grimes",
      "Lance Hornsby",
      "Princess (Juanita Sanchez)",
    ],
    settingPlaceholder: "e.g., The Alexandria walls at dusk, a herd on the horizon",
  },
  {
    id: "shameless-us",
    name: "Shameless (US)",
    category: "films-tv",
    canonRules:
      "Follow the Showtime Shameless (US) series canon. The Gallaghers are a dysfunctional South Side Chicago family surviving poverty. Frank is an alcoholic deadbeat father. Fiona raised the kids. Respect the class dynamics and the 'poor but resilient' tone. Do not romanticize poverty or addiction — the show is honest about both. Ian and Mickey's relationship is central to the fandom. Use South Side Chicago culture authentically.",
    locations:
      "The Gallagher House, The Alibi Room, South Side Chicago, Kev and V's House, The Milkovich House, Patsy's Pies",
    characters: [
      "Ian Gallagher",
      "Mickey Milkovich",
      "Fiona Gallagher",
      "Lip Gallagher",
      "Carl Gallagher",
      "Debbie Gallagher",
      "Frank Gallagher",
      "Kevin Ball",
      "Veronica Fisher",
      "Liam Gallagher",
      "Mandy Milkovich",
      "Svetlana",
      "Sheila Jackson",
      "Karen Jackson",
      "Jimmie / Steve Lishman",
      "Tami Tamietti",
      "Sandy Milkovich",
      "Terry Milkovich",
      "Kermit",
      "Tommy",
      "Bianca",
      "Brad",
      "Caleb",
      "Trevor",
      "Sean Pierce",
    ],
    settingPlaceholder: "e.g., The Gallagher kitchen, morning chaos before school",
  },
  {
    id: "house-of-the-dragon",
    name: "House of the Dragon",
    category: "films-tv",
    canonRules:
      "Follow the HBO House of the Dragon series canon. Set roughly 200 years before Game of Thrones during the Targaryen civil war (the Dance of the Dragons). All dragonriders are of Valyrian blood. Respect the Greens vs. Blacks factional divide. Dragon bonding is permanent and one rider per dragon. Targaryen names are similar — do not confuse Aegon, Aemond, Daemon, etc. Incestuous relationships are normalized in Targaryen culture.",
    locations:
      "King's Landing, The Red Keep, Dragonstone, Driftmark, Harrenhal, The Dragonpit, Storm's End, The Stepstones",
    characters: [
      "Rhaenyra Targaryen",
      "Daemon Targaryen",
      "Alicent Hightower",
      "Aemond Targaryen",
      "Aegon II Targaryen",
      "Otto Hightower",
      "Corlys Velaryon",
      "Rhaenys Targaryen",
      "Criston Cole",
      "Jacaerys Velaryon",
      "Helaena Targaryen",
      "Larys Strong",
      "Mysaria",
      "Viserys I Targaryen",
      "Baela Targaryen",
      "Rhaena Targaryen",
      "Lucerys Velaryon",
      "Daeron Targaryen",
      "Hugh Hammer",
      "Ulf White",
      "Addam of Hull",
      "Simon Strong",
      "Ser Arryk Cargyll",
      "Ser Erryk Cargyll",
      "Alys Rivers",
    ],
    settingPlaceholder: "e.g., The Dragonpit, a tense council between Greens and Blacks",
  },
  {
    id: "dc-batman",
    name: "DC Universe / Batman",
    category: "films-tv",
    canonRules:
      "Follow DC Comics canon (can draw from comics, DCAU, films, or specify continuity). The Bat Family is a complex, dysfunctional found family centered on Bruce Wayne's trauma and mission. Each Robin has a distinct personality and relationship with Bruce. Gotham is dark and corrupt; Metropolis is bright and hopeful. Respect power levels — Batman is human with prep time, Superman is near-godlike. The DC multiverse means many versions of characters coexist. Do not flatten villain motivations — Gotham's rogues are often tragic figures.",
    locations:
      "Gotham City, The Batcave, Wayne Manor, Arkham Asylum, Metropolis, The Watchtower, Titans Tower, Themyscira, The Fortress of Solitude, Blüdhaven, Star City",
    characters: [
      "Bruce Wayne / Batman",
      "Clark Kent / Superman",
      "Diana Prince / Wonder Woman",
      "Dick Grayson / Nightwing",
      "Jason Todd / Red Hood",
      "Tim Drake / Red Robin",
      "Damian Wayne / Robin",
      "Barbara Gordon / Batgirl",
      "Selina Kyle / Catwoman",
      "Harley Quinn",
      "The Joker",
      "Alfred Pennyworth",
      "Commissioner Gordon",
      "Poison Ivy",
      "Stephanie Brown / Spoiler",
      "Cassandra Cain / Batgirl",
      "Kate Kane / Batwoman",
      "Kara Zor-El / Supergirl",
      "Barry Allen / The Flash",
      "Hal Jordan / Green Lantern",
      "John Constantine",
      "Oliver Queen / Green Arrow",
      "Wally West / Kid Flash",
      "Raven",
      "Starfire",
      "Beast Boy",
      "Conner Kent / Superboy",
      "Roy Harper / Arsenal",
    ],
    settingPlaceholder: "e.g., The Batcave at 3 AM, case files glowing on the monitor array",
  },
  {
    id: "spider-man",
    name: "Spider-Man",
    category: "films-tv",
    canonRules:
      "Follow Spider-Man canon (can draw from MCU, Raimi films, Spider-Verse, comics, or specify continuity). Peter Parker is defined by responsibility, guilt, and humor under pressure. Spider-Sense is an early warning system, not omniscience. Web-shooters may be mechanical (comics/MCU) or organic (Raimi) depending on continuity. Miles Morales has additional powers (venom strike, invisibility). The Spider-Verse establishes that anyone can wear the mask. Respect the financial struggles — Peter is perpetually broke. Do not ignore Uncle Ben's legacy or the 'great power, great responsibility' ethos.",
    locations:
      "Queens (New York), Manhattan, Daily Bugle, Oscorp, Midtown School of Science and Technology, Aunt May's apartment, Avengers Tower (MCU), Brooklyn (Miles), various New York rooftops",
    characters: [
      "Peter Parker / Spider-Man",
      "Miles Morales / Spider-Man",
      "Gwen Stacy / Spider-Gwen",
      "MJ / Mary Jane Watson",
      "Ned Leeds",
      "Tony Stark (MCU crossover)",
      "May Parker",
      "Harry Osborn",
      "Norman Osborn / Green Goblin",
      "Otto Octavius / Doc Ock",
      "Eddie Brock / Venom",
      "Wade Wilson / Deadpool",
      "Matt Murdock / Daredevil",
      "Felicia Hardy / Black Cat",
      "Flash Thompson",
      "Ganke Lee",
      "Miguel O'Hara / Spider-Man 2099",
      "Peter B. Parker",
      "Peni Parker",
      "Spider-Noir",
    ],
    settingPlaceholder: "e.g., A Queens rooftop at sunset, mask pulled up to eat a bodega sandwich",
  },
];
