import { FandomConfig } from "../../types/fandom";

export const GAME_FANDOMS: FandomConfig[] = [
  {
    id: "genshin-impact",
    name: "Genshin Impact",
    category: "games",
    canonRules:
      "Respect the Vision system — each character wields a specific element (Anemo, Geo, Electro, Dendro, Hydro, Pyro, Cryo) granted by an Archon. Each nation corresponds to an element and real-world culture. Do not confuse character backstories or give them the wrong Vision. The Traveler is from another world and searching for their sibling. Maintain the adventure-exploration tone with deeper lore beneath the surface.",
    locations:
      "Mondstadt, Liyue Harbor, Inazuma, Sumeru, Fontaine, Natlan, Snezhnaya, The Abyss, Teyvat overworld",
    characters: [
      "Aether / Lumine (Traveler)",
      "Paimon",
      "Zhongli",
      "Tartaglia / Childe",
      "Xiao",
      "Venti",
      "Raiden Shogun / Ei",
      "Hu Tao",
      "Ganyu",
      "Kamisato Ayaka",
      "Kamisato Ayato",
      "Albedo",
      "Diluc",
      "Jean",
      "Furina",
    ],
    settingPlaceholder: "e.g., Liyue Harbor at the Lantern Rite, paper lanterns rising into the sky",
  },
  {
    id: "dragon-age",
    name: "Dragon Age",
    category: "games",
    canonRules:
      "Respect Thedas lore. Mages face oppression from Templars and are kept in Circles. Blood magic is forbidden but tempting — it draws power from life force. Magic comes from the Fade, and spirits/demons blur the line. Use appropriate terminology (Chantry, Blight, Darkspawn, Veil, Tranquil). Romance is a major part of this franchise. Do not confuse game-specific companions across titles.",
    locations:
      "Ferelden, Kirkwall, Orlais, Skyhold, The Fade, Tevinter Imperium, Deep Roads, Denerim, Val Royeaux, Haven",
    era: "Can be set during Origins, DA2, Inquisition, or Veilguard eras",
    characters: [
      "The Warden (player character)",
      "Alistair",
      "Morrigan",
      "Leliana",
      "Hawke (player character)",
      "Fenris",
      "Anders",
      "Isabela",
      "The Inquisitor (player character)",
      "Solas",
      "Dorian Pavus",
      "Cullen Rutherford",
      "Iron Bull",
      "Cassandra Pentaghast",
      "Varric Tethras",
    ],
    settingPlaceholder: "e.g., Skyhold's battlements at sunset, the Breach glowing on the horizon",
  },
  {
    id: "baldurs-gate",
    name: "Baldur's Gate 3",
    category: "games",
    canonRules:
      "Follow D&D 5e rules and Forgotten Realms lore. The tadpole/Illithid infection is the central threat — it grants powers at a terrible cost. Companions have deep personal quests and approval systems. Respect class/race abilities and limitations. Mature romance and moral complexity are central to this fandom. Do not ignore the consequences of embracing vs. resisting the tadpole.",
    locations:
      "The Nautiloid, Emerald Grove, Goblin Camp, Moonrise Towers, Baldur's Gate city, The Underdark, Shadow-Cursed Lands, The Astral Prism, Camp",
    characters: [
      "Astarion",
      "Shadowheart",
      "Gale",
      "Lae'zel",
      "Karlach",
      "Wyll",
      "Halsin",
      "Minthara",
      "The Dark Urge",
      "Tav (player character)",
      "Raphael",
      "Orin",
      "Cazador",
      "Jaheira",
      "Minsc",
    ],
    settingPlaceholder: "e.g., Camp by the fire, companions sharing stories under the stars",
  },
  {
    id: "mass-effect",
    name: "Mass Effect",
    category: "games",
    canonRules:
      "Follow Mass Effect universe rules. Respect alien species (Turian, Asari, Krogan, Quarian, Salarian, Drell, etc.) and their unique cultures and biology. Biotics are powered by element zero exposure. Mass Relays enable FTL travel. The Reapers are an existential threat. The Normandy is home. Do not confuse game-specific romances or squad compositions across titles.",
    locations:
      "The Normandy, Citadel, Omega, Thessia, Tuchanka, Rannoch, Illium, Virmire, The Collector Base, Earth (ME3)",
    era: "Can be set during ME1, ME2, ME3, or Andromeda",
    characters: [
      "Commander Shepard",
      "Garrus Vakarian",
      "Tali'Zorah",
      "Liara T'Soni",
      "Thane Krios",
      "Jack / Subject Zero",
      "Miranda Lawson",
      "Kaidan Alenko",
      "Ashley Williams",
      "Mordin Solus",
      "Wrex",
      "Legion",
      "Joker / Jeff Moreau",
      "EDI",
    ],
    settingPlaceholder: "e.g., The Normandy's observation deck, the glow of a nebula through the window",
  },
  {
    id: "honkai-star-rail",
    name: "Honkai: Star Rail",
    category: "games",
    canonRules:
      "Respect the Path system (Destruction, Hunt, Erudition, Harmony, Nihility, Preservation, Abundance). The Trailblazer carries a Stellaron. Each world has distinct culture and conflicts (Herta Space Station, Jarilo-VI, The Xianzhou Luofu, Penacony). Aeons are cosmic beings that embody Paths. Do not confuse characters across HoYoverse titles. Maintain the blend of sci-fi adventure and character-driven drama.",
    locations:
      "The Astral Express, Herta Space Station, Belobog, The Xianzhou Luofu, Penacony, Amphoreus",
    characters: [
      "Trailblazer (Stelle / Caelus)",
      "March 7th",
      "Dan Heng / Dan Heng Imbibitor Lunae",
      "Kafka",
      "Blade",
      "Jing Yuan",
      "Silver Wolf",
      "Seele",
      "Bronya",
      "Himeko",
      "Welt",
      "Fu Xuan",
      "Firefly / SAM",
      "Robin",
    ],
    settingPlaceholder: "e.g., The Astral Express lounge car, stars streaming past the windows",
  },
  {
    id: "the-witcher",
    name: "The Witcher",
    category: "games",
    canonRules:
      "Witchers are mutated monster hunters — they are not emotionless, just muted in feeling. Respect the alchemy, Signs (Aard, Igni, Yrden, Quen, Axii), and bestiary. The Continent has complex politics between Northern Kingdoms, Nilfgaard, and nonhumans. Do not ignore the moral ambiguity — choices have consequences and the 'lesser evil' is a core theme. Can draw from games, books, or show.",
    locations:
      "Kaer Morhen, Novigrad, Oxenfurt, Skellige, Toussaint, Vizima, Velen (No Man's Land), Cintra",
    characters: [
      "Geralt of Rivia",
      "Yennefer of Vengerberg",
      "Triss Merigold",
      "Ciri / Cirilla",
      "Jaskier / Dandelion",
      "Vesemir",
      "Lambert",
      "Eskel",
      "Regis",
      "Dijkstra",
      "Philippa Eilhart",
      "Eredin",
    ],
    settingPlaceholder: "e.g., Kaer Morhen's great hall, a fire crackling while snow buries the pass",
  },
  {
    id: "persona-5",
    name: "Persona 5",
    category: "games",
    canonRules:
      "The Metaverse is a cognitive world shaped by people's distorted desires. Palaces belong to corrupt individuals, and Mementos is the collective unconscious. Personas are summoned by ripping off your mask — each Phantom Thief has a specific Persona and code name. Changing hearts means stealing Treasure. Do not ignore the social sim elements — Confidants and daily life are half the game. Maintain the stylish, rebellious tone.",
    locations:
      "Shujin Academy, Café Leblanc, The Metaverse, Mementos, Various Palaces, Shibuya, Yongen-Jaya, The Velvet Room",
    characters: [
      "Joker / Ren Amamiya",
      "Morgana",
      "Ann Takamaki",
      "Ryuji Sakamoto",
      "Yusuke Kitagawa",
      "Makoto Niijima",
      "Futaba Sakura",
      "Haru Okumura",
      "Goro Akechi",
      "Sojiro Sakura",
      "Kasumi Yoshizawa / Sumire",
      "Takuto Maruki",
    ],
    settingPlaceholder: "e.g., Café Leblanc after hours, the scent of coffee and the rustle of a calling card",
  },
  {
    id: "undertale",
    name: "Undertale",
    category: "games",
    canonRules:
      "The route system matters — Pacifist, Neutral, and Genocide runs have dramatically different tones and outcomes. SAVE, LOAD, and RESET are in-universe mechanics, not just gameplay. Monsters are made of magic and compassion. DETERMINATION is a specific substance with specific effects. Do not mix route tones without intention. Respect the fourth-wall-breaking elements. Maintain the tone appropriate to the route you're writing.",
    locations:
      "The Underground, The Ruins, Snowdin, Waterfall, Hotland, New Home, The Core, The Surface, The Judgment Hall",
    characters: [
      "Frisk",
      "Sans",
      "Papyrus",
      "Toriel",
      "Asgore",
      "Undyne",
      "Alphys",
      "Mettaton",
      "Flowey / Asriel Dreemurr",
      "Chara",
      "Napstablook",
      "W.D. Gaster",
    ],
    settingPlaceholder: "e.g., Snowdin town, snow falling gently as Sans waits by his sentry station",
  },
  {
    id: "fire-emblem-three-houses",
    name: "Fire Emblem: Three Houses",
    category: "games",
    canonRules:
      "Fódlan is divided into three nations (Adrestian Empire, Holy Kingdom of Faerghus, Leicester Alliance), each with a house at Garreg Mach. The route you choose (Black Eagles, Blue Lions, Golden Deer, or Church) determines allegiances. Crests are inherited powers tied to bloodlines and the Elites. Byleth is the professor. Do not mix pre- and post-timeskip character states without reason. Romance and support conversations are core to the fandom.",
    locations:
      "Garreg Mach Monastery, Enbarr, Fhirdiad, Derdriu, Abyss, Zanado (Red Canyon), Gronder Field, Shambhala",
    characters: [
      "Byleth",
      "Edelgard von Hresvelg",
      "Dimitri Alexandre Blaiddyd",
      "Claude von Riegan",
      "Hubert von Vestra",
      "Dorothea Arnault",
      "Felix Hugo Fraldarius",
      "Sylvain Jose Gautier",
      "Mercedes von Martritz",
      "Bernadetta von Varley",
      "Linhardt von Hevring",
      "Lysithea von Ordelia",
      "Rhea / Seiros",
    ],
    settingPlaceholder: "e.g., The Goddess Tower at Garreg Mach, the night of the ball",
  },
  {
    id: "final-fantasy-vii",
    name: "Final Fantasy VII",
    category: "games",
    canonRules:
      "Shinra is a megacorporation draining the Planet's Lifestream for energy. Materia channels the Planet's power. SOLDIER members are enhanced with Mako. The Promised Land is central to the plot. Respect the Midgar class divide (plates and slums). Sephiroth's relationship with Cloud is complex — do not simplify it. Can draw from the original, Remake, or Rebirth. Maintain the blend of cyberpunk, fantasy, and eco-thriller.",
    locations:
      "Midgar, Sector 7 Slums, Shinra HQ, Aerith's Church, The Gold Saucer, Nibelheim, The Forgotten Capital, Costa del Sol",
    characters: [
      "Cloud Strife",
      "Tifa Lockhart",
      "Aerith Gainsborough",
      "Sephiroth",
      "Barret Wallace",
      "Zack Fair",
      "Red XIII / Nanaki",
      "Yuffie Kisaragi",
      "Vincent Valentine",
      "Cid Highwind",
      "Reno",
      "Rufus Shinra",
    ],
    settingPlaceholder: "e.g., Aerith's church in the Sector 5 slums, flowers growing in the ruin",
  },
  {
    id: "final-fantasy-xiv",
    name: "Final Fantasy XIV",
    category: "games",
    canonRules:
      "The Warrior of Light is a specific character in the story, not just a player avatar. Respect the world of Hydaelyn/Etheirys and its expansions (A Realm Reborn through Dawntrail). Each expansion has distinct lore and stakes. The Ascians seek to rejoin the shards. Do not mix expansion storylines carelessly. Eorzean geography, city-states, and beast tribes matter. Maintain the epic, emotionally resonant tone the game is known for.",
    locations:
      "Eorzea, Ul'dah, Limsa Lominsa, Gridania, Ishgard, The First / Norvrandt, Elpis, Old Sharlayan, Garlemald, The Source",
    characters: [
      "Warrior of Light (WoL)",
      "Alphinaud Leveilleur",
      "Alisaie Leveilleur",
      "G'raha Tia / Crystal Exarch",
      "Emet-Selch / Hades",
      "Y'shtola Rhul",
      "Thancred Waters",
      "Haurchefant Greystone",
      "Estinien Varlineau",
      "Zenos yae Galvus",
      "Aymeric de Borel",
      "Elidibus",
    ],
    settingPlaceholder: "e.g., The Rising Stones, the Scions gathered around the planning table",
  },
  {
    id: "final-fantasy-xv",
    name: "Final Fantasy XV",
    category: "games",
    canonRules:
      "Noctis and his three friends are on a road trip that becomes a world-saving journey. The Regalia is their car and should be treated with respect. Noctis is the Chosen King — the prophecy demands sacrifice. Respect the bond between the four party members above all. Do not separate the bros without narrative weight. Maintain the 'road trip with friends' intimacy alongside the epic fantasy stakes.",
    locations:
      "Insomnia, Hammerhead, Galdin Quay, Lestallum, Altissia, Tenebrae, The Regalia, Zegnautus Keep, Pitioss Ruins",
    characters: [
      "Noctis Lucis Caelum",
      "Ignis Scientia",
      "Gladiolus Amicitia",
      "Prompto Argentum",
      "Lunafreya Nox Fleuret",
      "Ardyn Izunia",
      "Cor Leonis",
      "Iris Amicitia",
      "Aranea Highwind",
      "Cindy Aurum",
      "Ravus Nox Fleuret",
    ],
    settingPlaceholder: "e.g., Camping under the stars, the Regalia parked nearby, Ignis cooking dinner",
  },
  {
    id: "overwatch",
    name: "Overwatch",
    category: "games",
    canonRules:
      "Overwatch was a heroic international task force that was disbanded after a scandal. Each hero has specific abilities, nationalities, and backstories — do not mix them up. Talon is the antagonist organization. Omnics are sentient robots, and human-Omnic relations are a central tension. Respect each character's established personality and speech patterns. Maintain the hopeful, diverse, team-based tone.",
    locations:
      "Watchpoint: Gibraltar, King's Row, Numbani, Hanamura, Dorado, Route 66, Eichenwalde, Overwatch HQ (Swiss)",
    characters: [
      "Tracer / Lena Oxton",
      "Genji Shimada",
      "Hanzo Shimada",
      "Mercy / Angela Ziegler",
      "Soldier: 76 / Jack Morrison",
      "Reaper / Gabriel Reyes",
      "Ana Amari",
      "Pharah / Fareeha Amari",
      "Widowmaker / Amélie Lacroix",
      "D.Va / Hana Song",
      "McCree / Cole Cassidy",
      "Reinhardt Wilhelm",
      "Sombra",
      "Junkrat / Jamison Fawkes",
    ],
    settingPlaceholder: "e.g., Watchpoint: Gibraltar, the recall signal flickering to life",
  },
  {
    id: "detroit-become-human",
    name: "Detroit: Become Human",
    category: "games",
    canonRules:
      "Androids are gaining sentience (deviancy) and demanding rights. The three playable characters (Connor, Kara, Markus) have distinct storylines that intersect. Choices have permanent consequences — characters can die. CyberLife manufactures androids. rA9 is a messianic figure. LED temple rings indicate android status (blue calm, yellow processing, red stress). Do not ignore the civil rights allegory. Maintain the choice-driven narrative tension.",
    locations:
      "Detroit 2038, CyberLife Tower, Jericho, The DPD Precinct, Zlatko's Mansion, Pirate's Cove, Rose's Farm, Stratford Tower",
    characters: [
      "Connor",
      "Hank Anderson",
      "Kara",
      "Alice",
      "Luther",
      "Markus",
      "North",
      "Simon",
      "Josh",
      "Amanda",
      "Chloe",
      "Elijah Kamski",
      "Captain Fowler",
    ],
    settingPlaceholder: "e.g., The DPD bullpen, Connor analyzing evidence while Hank watches grudgingly",
  },
  {
    id: "stardew-valley",
    name: "Stardew Valley",
    category: "games",
    canonRules:
      "The player character left corporate life to run their grandfather's farm. Pelican Town is a small community where everyone knows each other. Respect each character's heart event progression and personal struggles. JojaMart vs. the Community Center is the central conflict. The mines have monsters but the tone stays cozy. Do not make it grimdark — Stardew Valley is a comfort game with depth beneath the surface.",
    locations:
      "The Farm, Pelican Town, Pierre's General Store, The Stardrop Saloon, The Mines, The Beach, Ginger Island, JojaMart, The Community Center",
    characters: [
      "The Farmer (player character)",
      "Sebastian",
      "Shane",
      "Abigail",
      "Emily",
      "Haley",
      "Sam",
      "Penny",
      "Elliott",
      "Harvey",
      "Leah",
      "Alex",
      "Krobus",
    ],
    settingPlaceholder: "e.g., The farm at sunrise, dew on the crops, the cat asleep on the porch",
  },
  {
    id: "elder-scrolls-skyrim",
    name: "Elder Scrolls: Skyrim",
    category: "games",
    canonRules:
      "The Dragonborn can absorb dragon souls and use the Thu'um (Shouts). Skyrim is in civil war between the Imperial Legion and the Stormcloaks. The nine (or eight) Divines and the Daedric Princes are real forces. Respect the Elder Scrolls lore — Khajiit, Argonians, Elves, and other races have distinct cultures. Do not simplify the political situation. Maintain the epic Nordic fantasy tone.",
    locations:
      "Whiterun, Solitude, Windhelm, Riften, Markarth, High Hrothgar, The Throat of the World, Sovngarde, Blackreach, College of Winterhold",
    characters: [
      "The Dragonborn (player character)",
      "Serana",
      "Lydia",
      "Paarthurnax",
      "Ulfric Stormcloak",
      "General Tullius",
      "Alduin",
      "Cicero",
      "Astrid",
      "Delphine",
      "Aela the Huntress",
      "Brynjolf",
    ],
    settingPlaceholder: "e.g., High Hrothgar's courtyard, learning a Shout as the wind howls",
  },
  {
    id: "fallout-4",
    name: "Fallout 4",
    category: "games",
    canonRules:
      "Set in post-nuclear Boston (The Commonwealth) in 2287. The Sole Survivor emerged from Vault 111 after 210 years of cryogenic sleep. Factions (Minutemen, Brotherhood of Steel, Railroad, Institute) have conflicting goals. Synths are synthetic humans and the central moral question. Power Armor requires Fusion Cores. Bottle caps are currency. Do not ignore radiation and its effects. Maintain the retro-futuristic 1950s aesthetic in a ruined world.",
    locations:
      "Diamond City, The Institute, Vault 111, Sanctuary Hills, Goodneighbor, The Prydwen, The Railroad HQ, The Castle, The Glowing Sea",
    characters: [
      "The Sole Survivor",
      "Nick Valentine",
      "Piper Wright",
      "Paladin Danse",
      "Deacon",
      "Preston Garvey",
      "Hancock",
      "Cait",
      "MacCready",
      "Curie",
      "Strong",
      "Dogmeat",
      "Father / Shaun",
    ],
    settingPlaceholder: "e.g., Diamond City market at dusk, neon signs flickering in the old stadium",
  },
  {
    id: "legend-of-zelda-botw-totk",
    name: "Legend of Zelda: Breath of the Wild / Tears of the Kingdom",
    category: "games",
    canonRules:
      "Link is the chosen hero who wields the Master Sword. Hyrule is an open world with Sheikah technology (BotW) and Zonai devices (TotK). The Champions/Sages each represent a Divine Beast/temple and a race (Zora, Goron, Rito, Gerudo). Zelda is a scholar-princess, not a damsel. Do not ignore the post-Calamity setting and its consequences. Maintain the sense of wonder, exploration, and quiet emotional storytelling.",
    locations:
      "Hyrule Castle, Hateno Village, Zora's Domain, Goron City, Rito Village, Gerudo Town, The Great Sky Islands, The Depths, Lurelin Village",
    characters: [
      "Link",
      "Princess Zelda",
      "Sidon",
      "Mipha",
      "Revali",
      "Urbosa",
      "Daruk",
      "Purah",
      "Riju",
      "Tulin",
      "Yunobo",
      "Rauru",
      "Ganondorf",
    ],
    settingPlaceholder: "e.g., A campfire on a Hyrule hillside, the Blood Moon rising in the distance",
  },
  {
    id: "red-dead-redemption",
    name: "Red Dead Redemption",
    category: "games",
    canonRules:
      "Set in the dying days of the American Wild West (1899 for RDR2, 1911 for RDR1). The Van der Linde gang is falling apart under pressure from civilization closing in. Arthur Morgan has his own moral journey separate from Dutch's ideals. Do not use modern speech or technology. Tuberculosis is a real, fatal disease in this era. Honor system choices define character. Maintain the elegiac, melancholic tone of a world ending.",
    locations:
      "Camp (various locations), Valentine, Saint Denis, Blackwater, Strawberry, Rhodes, Annesburg, Van Horn, Guarma, Beecher's Hope",
    characters: [
      "Arthur Morgan",
      "John Marston",
      "Dutch van der Linde",
      "Sadie Adler",
      "Charles Smith",
      "Hosea Matthews",
      "Micah Bell",
      "Abigail Roberts",
      "Lenny Summers",
      "Javier Escuella",
      "Tilly Jackson",
      "Mary Linton",
    ],
    settingPlaceholder: "e.g., Camp at Horseshoe Overlook, guitars and stories around the fire",
  },
  {
    id: "resident-evil",
    name: "Resident Evil",
    category: "games",
    canonRules:
      "Bioweapons (T-Virus, G-Virus, Las Plagas, Mold, etc.) create specific types of monsters — do not mix viruses carelessly. Umbrella Corporation is the original villain, but bioterrorism is now global. Survival horror means limited resources and genuine danger. Respect each game's specific setting and virus. Do not make characters superhuman beyond what the games show. Maintain the horror-action tone.",
    locations:
      "Raccoon City, Spencer Mansion, RPD Station, The Village, Baker Estate, BSAA HQ, The Island, Tall Oaks",
    characters: [
      "Leon S. Kennedy",
      "Claire Redfield",
      "Chris Redfield",
      "Jill Valentine",
      "Ada Wong",
      "Albert Wesker",
      "Ethan Winters",
      "Lady Dimitrescu",
      "Carlos Oliveira",
      "Sherry Birkin",
      "Ashley Graham",
    ],
    settingPlaceholder: "e.g., The RPD main hall, something scratching at the boarded-up windows",
  },
  {
    id: "ace-attorney",
    name: "Ace Attorney",
    category: "games",
    canonRules:
      "Court trials follow the game's unique system — attorneys cross-examine witnesses and present evidence to find contradictions. 'OBJECTION!' and 'HOLD IT!' are signature mechanics. The legal system is fictional (guilty until proven innocent, 3-day trials). Do not make the law realistic — it follows Ace Attorney rules. Maintain the dramatic, comedic tone with serious undertones. Every case has twists.",
    locations:
      "The Courtroom, Wright Anything Agency, Detention Center, Prosecutor's Office, Various crime scenes, Kurain Village, Khura'in",
    characters: [
      "Phoenix Wright",
      "Miles Edgeworth",
      "Maya Fey",
      "Apollo Justice",
      "Trucy Wright",
      "Athena Cykes",
      "Franziska von Karma",
      "Godot / Diego Armando",
      "Mia Fey",
      "Larry Butz",
      "Klavier Gavin",
      "Simon Blackquill",
    ],
    settingPlaceholder: "e.g., Courtroom No. 4, the witness sweating as Phoenix slams the desk",
  },
  {
    id: "kingdom-hearts",
    name: "Kingdom Hearts",
    category: "games",
    canonRules:
      "Hearts, Heartless, Nobodies, and Keyblades follow specific rules — hearts are the core of a person's being. The Keyblade chooses its wielder. Worlds must not know about each other (world order). Disney worlds follow their film plots but with Heartless interference. Organization XIII members are Nobodies seeking hearts. The lore is complex — respect the timeline even when it's convoluted. Light vs. Darkness is the central theme.",
    locations:
      "Destiny Islands, Traverse Town, Hollow Bastion / Radiant Garden, The World That Never Was, Twilight Town, Castle Oblivion, Scala ad Caelum, Various Disney worlds",
    characters: [
      "Sora",
      "Riku",
      "Kairi",
      "Axel / Lea",
      "Roxas",
      "Xion",
      "Ventus",
      "Aqua",
      "Terra",
      "Naminé",
      "Xehanort",
      "Donald Duck",
      "Goofy",
    ],
    settingPlaceholder: "e.g., The Destiny Islands shore at sunset, waves lapping the paopu tree",
  },
  {
    id: "the-last-of-us",
    name: "The Last of Us",
    category: "games",
    canonRules:
      "The Cordyceps fungal infection has collapsed civilization. Infected have stages (Runners, Stalkers, Clickers, Bloaters, Shamblers, Rat King). Spores are infectious. FEDRA controls quarantine zones; the Fireflies seek a cure. Joel's bond with Ellie is the emotional core. Do not sanitize the violence or the moral complexity — survival demands terrible choices. Maintain the bleak, emotionally devastating tone.",
    locations:
      "Boston QZ, The Capitol Building, Jackson (Wyoming), Seattle, Salt Lake City, Santa Barbara, Pittsburgh, Bill's Town",
    characters: [
      "Joel Miller",
      "Ellie Williams",
      "Abby Anderson",
      "Tess",
      "Tommy Miller",
      "Dina",
      "Jesse",
      "Bill",
      "Riley Abel",
      "Marlene",
      "Owen Moore",
      "Lev",
    ],
    settingPlaceholder: "e.g., An overgrown highway, nature reclaiming the ruins, silence except for birdsong",
  },
  {
    id: "team-fortress-2",
    name: "Team Fortress 2",
    category: "games",
    canonRules:
      "RED and BLU are rival mercenary teams hired by the Mann brothers. Each class has a specific role, personality, and nationality. The universe runs on absurd 1960s-70s spy-fi logic. Respawn is canonical. The Administrator controls everything. Do not make it too serious — TF2 is a comedy. Maintain the over-the-top, cartoon violence aesthetic. The comics expand the lore significantly.",
    locations:
      "2Fort, Dustbowl, Badlands, Mann Co. HQ, Teufort, Various mercenary bases, The Gravel Pit",
    characters: [
      "Scout",
      "Soldier",
      "Pyro",
      "Demoman",
      "Heavy",
      "Engineer",
      "Medic",
      "Sniper",
      "Spy",
      "Miss Pauling",
      "The Administrator / Helen",
      "Saxton Hale",
    ],
    settingPlaceholder: "e.g., The 2Fort intel room, an unlikely ceasefire over sandviches",
  },
  {
    id: "world-of-warcraft",
    name: "World of Warcraft",
    category: "games",
    canonRules:
      "Azeroth is a world of Alliance (Humans, Night Elves, Dwarves, Draenei, etc.) vs. Horde (Orcs, Trolls, Tauren, Blood Elves, Forsaken, etc.). Respect race-specific cultures, classes, and the long history of faction conflict. Magic follows established schools (Arcane, Fel, Holy, Shadow, Nature). Major lore events (Arthas, the Cataclysm, the Burning Legion) shape the world. Do not ignore faction tensions or simplify the lore.",
    locations:
      "Stormwind, Orgrimmar, Dalaran, Silvermoon City, Lordaeron, The Undercity, Darnassus, Thunder Bluff, Pandaria, The Dragon Isles",
    era: "Can be set in any expansion era",
    characters: [
      "Thrall",
      "Jaina Proudmoore",
      "Sylvanas Windrunner",
      "Anduin Wrynn",
      "Illidan Stormrage",
      "Arthas Menethil / The Lich King",
      "Tyrande Whisperwind",
      "Vol'jin",
      "Khadgar",
      "Wrathion",
      "Alexstrasza",
      "Lor'themar Theron",
    ],
    settingPlaceholder: "e.g., The tavern in Dalaran, factions sharing an uneasy drink",
  },
  {
    id: "splatoon",
    name: "Splatoon",
    category: "games",
    canonRules:
      "Set in a post-human world where Inklings and Octolings evolved from sea creatures. Turf War is the primary sport/culture. Inklings can shift between kid and squid form. Ink colors matter — you swim in your own color and are damaged by the enemy's. The Splatlands, Inkopolis, and the various idols drive the culture. Do not ignore that this is a post-apocalyptic world hidden under colorful aesthetics.",
    locations:
      "Inkopolis, Splatsville, Inkopolis Square, Octo Canyon, Alterna, Grizzco Industries, The Splatlands, Octo Expansion test facilities",
    characters: [
      "Agent 3",
      "Agent 4",
      "Agent 8",
      "Callie",
      "Marie",
      "Pearl",
      "Marina",
      "Shiver",
      "Frye",
      "Big Man",
      "Captain Cuttlefish",
      "DJ Octavio",
    ],
    settingPlaceholder: "e.g., Inkopolis Square before a Splatfest, music pumping and ink flying",
  },
];
