import type { FandomConfig } from "../../types/fandom.ts";

export const KPOP_FANDOMS: FandomConfig[] = [
  {
    id: "bts",
    name: "BTS",
    category: "kpop",
    canonRules:
      "This is Real Person Fiction (RPF). Use stage names by default, real names for intimate moments. Respect that these are fictionalized versions of real people. Common AU settings are welcome. Group dynamics and idol life details should feel authentic — dorm life, schedules, comebacks, fansigns, V Lives. BTS debuted under Big Hit Entertainment (now HYBE) in 2013. Respect the hyung line / maknae line dynamic and each member's established personality and role in the group.",
    locations:
      "Dorm, practice room, backstage, recording studio, concert venue, airport, variety show set, fan meeting venue, HYBE building, Hannam-dong",
    characters: [
      "RM / Kim Namjoon",
      "Jin / Kim Seokjin",
      "Suga / Min Yoongi",
      "J-Hope / Jung Hoseok",
      "Jimin / Park Jimin",
      "V / Kim Taehyung",
      "Jungkook / Jeon Jungkook",
      "Bang Si-hyuk",
      "Son Sungdeuk (Choreographer)",
      "Pdogg (Producer)",
      "TXT members (hoobaes)",
      "Halsey (collaborator)",
    ],
    settingPlaceholder: "e.g., The dorm living room after a late-night practice, exhausted but wired",
  },
  {
    id: "stray-kids",
    name: "Stray Kids",
    category: "kpop",
    canonRules:
      "This is Real Person Fiction (RPF). Use stage names by default, real names for intimate moments. Respect that these are fictionalized versions of real people. Common AU settings are welcome. Group dynamics and idol life details should feel authentic — dorm life, schedules, comebacks, fansigns, V Lives. Stray Kids debuted under JYP Entertainment in 2018. 3RACHA (Bang Chan, Changbin, Han) are the producing unit. Respect the self-produced identity of the group.",
    locations:
      "Dorm, practice room, backstage, recording studio, concert venue, airport, variety show set, fan meeting venue, JYP Entertainment building",
    characters: [
      "Bang Chan / Chris",
      "Lee Know / Lee Minho",
      "Changbin / Seo Changbin",
      "Hyunjin / Hwang Hyunjin",
      "Han / Han Jisung",
      "Felix / Lee Felix",
      "Seungmin / Kim Seungmin",
      "I.N / Yang Jeongin",
      "Woojin / Kim Woojin (former member)",
      "J.Y. Park (JYP)",
      "Berry (Bang Chan's dog)",
      "Kkami (Hyunjin's dog)",
      "Leebit (Lee Know's cat)",
    ],
    settingPlaceholder: "e.g., The recording studio at 3 AM, 3RACHA working on a new track",
  },
  {
    id: "exo",
    name: "EXO",
    category: "kpop",
    canonRules:
      "This is Real Person Fiction (RPF). Use stage names by default, real names for intimate moments. Respect that these are fictionalized versions of real people. Common AU settings are welcome. Group dynamics and idol life details should feel authentic — dorm life, schedules, comebacks, fansigns, V Lives. EXO debuted under SM Entertainment in 2012 with the concept of members having supernatural powers (a popular fic element). EXO-K and EXO-M were original subunits. Respect the complex history with former members.",
    locations:
      "Dorm, practice room, backstage, recording studio, concert venue, airport, variety show set, fan meeting venue, SM Entertainment building, Seoul, Beijing",
    characters: [
      "Baekhyun / Byun Baekhyun",
      "Chanyeol / Park Chanyeol",
      "D.O. / Do Kyungsoo",
      "Kai / Kim Jongin",
      "Sehun / Oh Sehun",
      "Suho / Kim Junmyeon",
      "Xiumin / Kim Minseok",
      "Chen / Kim Jongdae",
      "Lay / Zhang Yixing",
      "Kris / Wu Yifan (former member)",
      "Luhan / Lu Han (former member)",
      "Tao / Huang Zitao (former member)",
    ],
    settingPlaceholder: "e.g., The SM practice room, preparing choreography for a comeback stage",
  },
  {
    id: "ateez",
    name: "ATEEZ",
    category: "kpop",
    canonRules:
      "This is Real Person Fiction (RPF). Use stage names by default, real names for intimate moments. Respect that these are fictionalized versions of real people. Common AU settings are welcome. Group dynamics and idol life details should feel authentic — dorm life, schedules, comebacks, fansigns, V Lives. ATEEZ debuted under KQ Entertainment in 2018. Their HALATEEZ pirate concept and storyline lore is a popular fic element. Known for powerful performances and intense stage presence.",
    locations:
      "Dorm, practice room, backstage, recording studio, concert venue, airport, variety show set, fan meeting venue, KQ Entertainment building",
    characters: [
      "Hongjoong / Kim Hongjoong",
      "Seonghwa / Park Seonghwa",
      "Yunho / Jeong Yunho",
      "Yeosang / Kang Yeosang",
      "San / Choi San",
      "Mingi / Song Mingi",
      "Wooyoung / Jung Wooyoung",
      "Jongho / Choi Jongho",
      "Eden (Producer)",
      "HALATEEZ (mirror versions)",
    ],
    settingPlaceholder: "e.g., Backstage before a comeback stage, ATEEZ hyping each other up",
  },
  {
    id: "nct",
    name: "NCT",
    category: "kpop",
    canonRules:
      "This is Real Person Fiction (RPF). Use stage names by default, real names for intimate moments. Respect that these are fictionalized versions of real people. Common AU settings are welcome. Group dynamics and idol life details should feel authentic — dorm life, schedules, comebacks, fansigns, V Lives. NCT is an SM Entertainment group with a rotational concept across units: NCT 127 (Seoul-based), NCT Dream (originally age-graduated), and WayV (China-based). Respect which members belong to which unit(s) and the dual-member dynamics.",
    locations:
      "Dorm, practice room, backstage, recording studio, concert venue, airport, variety show set, fan meeting venue, SM Entertainment building, Seoul, Shanghai",
    characters: [
      "Taeyong / Lee Taeyong",
      "Mark / Mark Lee",
      "Jaehyun / Jung Jaehyun",
      "Doyoung / Kim Doyoung",
      "Johnny / Suh Youngho",
      "Yuta / Nakamoto Yuta",
      "Haechan / Lee Donghyuck",
      "Jungwoo / Kim Jungwoo",
      "Jaemin / Na Jaemin",
      "Jeno / Lee Jeno",
      "Renjun / Huang Renjun",
      "Chenle / Zhong Chenle",
      "Jisung / Park Jisung",
      "Ten / Chittaphon Leechaiyapornkul",
      "Lucas / Wong Yukhei",
      "Kun / Qian Kun",
      "Winwin / Dong Sicheng",
      "Xiaojun / Xiao Dejun",
      "Hendery / Wong Kunhang",
      "Yangyang / Liu Yangyang",
      "Shotaro / Osaki Shotaro",
      "Sungchan / Jung Sungchan",
    ],
    settingPlaceholder: "e.g., The NCT Dream dorm, a chaotic movie night with too many snacks",
  },
  {
    id: "txt",
    name: "TXT (Tomorrow X Together)",
    category: "kpop",
    canonRules:
      "This is Real Person Fiction (RPF). Use stage names by default, real names for intimate moments. Respect that these are fictionalized versions of real people. Common AU settings are welcome. Group dynamics and idol life details should feel authentic — dorm life, schedules, comebacks, fansigns, V Lives. TXT debuted under Big Hit / HYBE in 2019. Known for their storyline concept (the TU - TXT Universe) and youthful, experimental sound. They are BTS's juniors at HYBE.",
    locations:
      "Dorm, practice room, backstage, recording studio, concert venue, airport, variety show set, fan meeting venue, HYBE building",
    characters: [
      "Soobin / Choi Soobin",
      "Yeonjun / Choi Yeonjun",
      "Beomgyu / Choi Beomgyu",
      "Taehyun / Kang Taehyun",
      "Hueningkai / Kai Kamal Huening",
      "Bang Si-hyuk",
      "BTS members (sunbaenims)",
      "ENHYPEN members (friends)",
    ],
    settingPlaceholder: "e.g., The HYBE cafeteria, TXT debating what to eat after practice",
  },
  {
    id: "seventeen",
    name: "Seventeen",
    category: "kpop",
    canonRules:
      "This is Real Person Fiction (RPF). Use stage names by default, real names for intimate moments. Respect that these are fictionalized versions of real people. Common AU settings are welcome. Group dynamics and idol life details should feel authentic — dorm life, schedules, comebacks, fansigns, V Lives. Seventeen debuted under Pledis Entertainment (now under HYBE) in 2015 with 13 members in three units: Hip-Hop Unit, Vocal Unit, and Performance Unit. They are known as the self-producing idol group. Respect the unit system and each member's role.",
    locations:
      "Dorm, practice room, backstage, recording studio, concert venue, airport, variety show set, fan meeting venue, Pledis Entertainment building",
    characters: [
      "S.Coups / Choi Seungcheol",
      "Jeonghan / Yoon Jeonghan",
      "Joshua / Hong Jisoo",
      "Jun / Wen Junhui",
      "Hoshi / Kwon Soonyoung",
      "Wonwoo / Jeon Wonwoo",
      "Woozi / Lee Jihoon",
      "DK / Lee Seokmin",
      "Mingyu / Kim Mingyu",
      "The8 / Xu Minghao",
      "Seungkwan / Boo Seungkwan",
      "Vernon / Chwe Hansol",
      "Dino / Lee Chan",
      "Bumzu (Producer)",
    ],
    settingPlaceholder: "e.g., The practice room at midnight, Woozi fine-tuning the comeback choreo",
  },
  {
    id: "enhypen",
    name: "ENHYPEN",
    category: "kpop",
    canonRules:
      "This is Real Person Fiction (RPF). Use stage names by default, real names for intimate moments. Respect that these are fictionalized versions of real people. Common AU settings are welcome. Group dynamics and idol life details should feel authentic — dorm life, schedules, comebacks, fansigns, V Lives. ENHYPEN debuted under BELIFT LAB (HYBE x CJ ENM) in 2020 after the survival show I-LAND. Their concept involves vampire and coming-of-age lore. Respect the I-LAND origin story and the connections to other HYBE groups.",
    locations:
      "Dorm, practice room, backstage, recording studio, concert venue, airport, variety show set, fan meeting venue, HYBE building",
    characters: [
      "Jungwon / Yang Jungwon",
      "Heeseung / Lee Heeseung",
      "Jay / Park Jongseong",
      "Jake / Sim Jaeyun",
      "Sunghoon / Park Sunghoon",
      "Sunoo / Kim Sunoo",
      "Ni-ki / Nishimura Riki",
      "BTS members (sunbaenims)",
      "TXT members (sunbaenims)",
    ],
    settingPlaceholder: "e.g., The dorm late at night, a quiet moment between schedules",
  },
  {
    id: "blackpink",
    name: "BLACKPINK",
    category: "kpop",
    canonRules:
      "This is Real Person Fiction (RPF). Use stage names by default, real names for intimate moments. Respect that these are fictionalized versions of real people. Common AU settings are welcome. Group dynamics and idol life details should feel authentic — dorm life, schedules, comebacks, fansigns, V Lives. BLACKPINK debuted under YG Entertainment in 2016. They are one of the biggest K-pop girl groups globally. Each member has a strong solo career alongside group activities. Respect the YG training system and each member's distinct public persona.",
    locations:
      "Dorm, practice room, backstage, recording studio, concert venue, airport, variety show set, fan meeting venue, YG Entertainment building, Paris, various fashion week locations",
    characters: [
      "Jisoo / Kim Jisoo",
      "Jennie / Jennie Kim",
      "Rosé / Park Chaeyoung / Roseanne Park",
      "Lisa / Lalisa Manobal / Pranpriya Manobal",
      "Teddy Park (Producer)",
      "YG / Yang Hyun-suk",
    ],
    settingPlaceholder: "e.g., Backstage at Coachella, the energy electric before going on",
  },
  {
    id: "aespa",
    name: "aespa",
    category: "kpop",
    canonRules:
      "This is Real Person Fiction (RPF). Use stage names by default, real names for intimate moments. Respect that these are fictionalized versions of real people. Common AU settings are welcome. Group dynamics and idol life details should feel authentic — dorm life, schedules, comebacks, fansigns, V Lives. aespa debuted under SM Entertainment in 2020 with a unique AI/metaverse concept — each member has a virtual avatar counterpart (æ). The KWANGYA universe and Black Mamba storyline are central to their lore. Respect the SM æ-universe worldbuilding.",
    locations:
      "Dorm, practice room, backstage, recording studio, concert venue, airport, variety show set, fan meeting venue, SM Entertainment building, KWANGYA, the æ world",
    characters: [
      "Karina / Yu Jimin",
      "Giselle / Aeri Uchinaga",
      "Winter / Kim Minjeong",
      "Ningning / Ning Yizhuo",
      "æ-Karina",
      "æ-Giselle",
      "æ-Winter",
      "æ-Ningning",
      "nævis",
      "Black Mamba",
    ],
    settingPlaceholder: "e.g., The SM practice room, preparing for a KWANGYA-themed comeback",
  },
];
