import type { TropeCategory } from "../../types/fandom.ts";

export const TROPE_CATEGORIES: TropeCategory[] = [
  {
    id: "romance",
    label: "Romance",
    tropes: [
      "Enemies to Lovers",
      "Friends to Lovers",
      "Fake Dating / Fake Marriage",
      "Mutual Pining",
      "Forbidden Love",
      "Only One Bed",
      "Second Chance Romance",
      "Unrequited Love",
      "Idiots in Love",
      "Arranged Marriage",
      "Love Confessions",
      "Getting Together",
      "First Kiss",
      "Secret Relationship",
      "Oblivious / Pining",
    ],
  },
  {
    id: "au",
    label: "AU",
    tropes: [
      "Canon Divergence",
      "Modern AU",
      "Coffee Shop AU",
      "Royalty AU",
      "College / High School AU",
      "Soulmate AU",
      "Omegaverse (A/B/O)",
      "No Powers AU",
      "Vampire AU",
      "Pirate AU",
      "Mafia / Crime AU",
      "Hanahaki Disease",
    ],
  },
  {
    id: "plot",
    label: "Plot",
    tropes: [
      "Fix-It Fic",
      "Found Family",
      "Time Travel",
      "Amnesia",
      "Body Swap",
      "Groundhog Day / Time Loop",
      "Secret Identity",
      "Identity Reveal",
      "Kidnapping / Rescue",
      "Reincarnation",
      "Post-Canon",
      "Pre-Canon / Prequel",
      "During Canon",
      "Accidental Baby Acquisition",
      "Mistaken Identity",
    ],
  },
  {
    id: "dynamics",
    label: "Dynamics",
    tropes: [
      "Hurt No Comfort",
      "Touch Starved",
      "Protective Behavior",
      "Possessive Behavior",
      "Jealousy",
      "BAMF Character",
      "Caretaking",
      "Power Dynamics",
      "Rivals to Lovers",
      "Emotional Manipulation",
      "Redemption Arc",
      "Villian POV",
      "Morally Grey Character",
      "Bed Sharing",
    ],
  },
  {
    id: "smut-kink",
    label: "Smut / Kink",
    tropes: [
      "First Time",
      "Praise Kink",
      "Competence Kink",
      "Size Difference",
      "Marking / Biting",
      "Dominance / Submission",
      "Orgasm Denial",
      "Hair Pulling",
      "Rough Sex",
      "Virginity / Inexperience",
      "Morning After",
      "Friends With Benefits",
      "Sexual Tension",
      "Mating Cycles / Heat",
    ],
  },
];

// Flat array of all tropes for validation
export const ALL_TROPES = TROPE_CATEGORIES.flatMap((cat) => cat.tropes);
