import { FandomConfig } from "../../types/fandom";

export const WEB_OTHER_FANDOMS: FandomConfig[] = [
  {
    id: "homestuck",
    name: "Homestuck",
    category: "web-other",
    canonRules:
      "SBURB is a reality-altering game that creates universes. Trolls have a hemospectrum (blood color hierarchy) that determines social status. God Tier requires dying on a Quest Bed. Trolls have quadrants for romance (Matespritship, Moirallegiance, Kismesissitude, Auspisticism). Paradox Space has complex time mechanics — stable time loops, doomed timelines, etc. Do not simplify the trolls' romance system. Maintain the metafictional, webcomic-specific narrative voice.",
    locations:
      "Skaia, The Medium, Prospit, Derse, Land of Wind and Shade, Various Lands, The Green Sun, The Furthest Ring, Earth (A and B)",
    characters: [
      "John Egbert",
      "Dave Strider",
      "Rose Lalonde",
      "Jade Harley",
      "Karkat Vantas",
      "Terezi Pyrope",
      "Vriska Serket",
      "Kanaya Maryam",
      "Gamzee Makara",
      "Sollux Captor",
      "Eridan Ampora",
      "Dirk Strider",
      "Roxy Lalonde",
      "Calliope",
      "Jane Crocker",
      "Jake English",
      "Aradia Megido",
      "Tavros Nitram",
      "Nepeta Leijon",
      "Equius Zahhak",
      "Feferi Peixes",
      "Caliborn",
      "The Condesce / Her Imperious Condescension",
      "The Handmaid",
      "The Signless / The Sufferer",
      "The Disciple",
      "The Dolorosa",
      "The Psiioniic",
      "Doc Scratch",
      "Lord English",
    ],
    settingPlaceholder: "e.g., A meteor hurtling through the Furthest Ring, trolls and humans cohabiting",
  },
  {
    id: "danganronpa",
    name: "Danganronpa",
    category: "web-other",
    canonRules:
      "Students are trapped in a killing game orchestrated by Monokuma. To escape, a student must murder another and not get caught during the Class Trial. Evidence gathering and debate (Non-Stop Debate, Hangman's Gambit) drive the trials. Ultimate talents define each character. Despair vs. Hope is the central theme. Do not reveal murderers casually — the mystery is sacred. Maintain the blend of dark murder mystery and absurdist humor.",
    locations:
      "Hope's Peak Academy, The Class Trial room, Various school floors, The killing game setting, Jabberwock Island, The Neo World Program",
    characters: [
      "Makoto Naegi",
      "Nagito Komaeda",
      "Kokichi Oma",
      "Shuichi Saihara",
      "Hajime Hinata / Izuru Kamukura",
      "Chiaki Nanami",
      "Kyoko Kirigiri",
      "Byakuya Togami",
      "Junko Enoshima",
      "Kaede Akamatsu",
      "Maki Harukawa",
      "Monokuma",
      "K1-B0 / Keebo",
    ],
    settingPlaceholder: "e.g., The Class Trial room, spotlights glaring, a new murder to solve",
  },
  {
    id: "critical-role",
    name: "Critical Role",
    category: "web-other",
    canonRules:
      "Critical Role is actual-play D&D — the characters were created and roleplayed by the cast. Respect the specific campaign you're writing (Campaign 1: Vox Machina, Campaign 2: Mighty Nein, Campaign 3: Bells Hells). D&D mechanics (spell slots, ability checks, hit points) are part of the world but should feel narrative, not mechanical. Each character has distinct mannerisms from their player. Do not confuse characters across campaigns.",
    locations:
      "Tal'Dorei, Whitestone, Emon, Wildemount, Xhorhas, The Menagerie Coast, Marquet, Jrusar, Ruidus",
    era: "Specify campaign (C1, C2, or C3)",
    characters: [
      "Vex'ahlia",
      "Vax'ildan",
      "Percy de Rolo",
      "Keyleth",
      "Grog Strongjaw",
      "Scanlan Shorthalt",
      "Pike Trickfoot",
      "Jester Lavorre",
      "Caleb Widogast",
      "Beauregard Lionett",
      "Fjord",
      "Mollymauk / Kingsley",
      "Essek Thelyss",
      "Laudna",
      "Imogen Temult",
      "Yasha Nydoorin",
      "Caduceus Clay",
      "Nott / Veth Brenatto",
      "Gilmore",
      "Allura Vysoren",
      "Ashton Greymoore",
      "Fearne Calloway",
      "Orym",
      "Fresh Cut Grass / FCG",
      "Chetney Pock O'Pea",
      "Dorian Storm",
      "The Matron of Ravens",
      "Delilah Briarwood",
      "Sylas Briarwood",
      "Lord Sylas Briarwood",
    ],
    settingPlaceholder: "e.g., A tavern in Whitestone, Vox Machina reunited over ale and old stories",
  },
  {
    id: "the-magnus-archives",
    name: "The Magnus Archives",
    category: "web-other",
    canonRules:
      "The Magnus Institute houses statements about supernatural encounters, organized by the Archivist. The Fears are cosmic horror entities categorized into 14 Entities (The Eye, The Stranger, The Spiral, etc.). Each Entity feeds on a specific type of fear. Avatars serve Entities and gain related powers. Statement-giving is a compulsion tied to The Eye. Do not mix up which Entity causes which fear. Maintain the atmospheric, slow-building horror podcast tone.",
    locations:
      "The Magnus Institute (London), The Archives, The Tunnels beneath the Institute, The Panopticon, Various statement locations, The Domains (post-Change)",
    characters: [
      "Jonathan Sims / The Archivist",
      "Martin Blackwood",
      "Sasha James",
      "Tim Stoker",
      "Elias Bouchard / Jonah Magnus",
      "Basira Hussain",
      "Daisy Tonner",
      "Melanie King",
      "Georgie Barker",
      "Peter Lukas",
      "Gertrude Robinson",
      "Helen / The Distortion",
      "Michael Shelley / The Distortion",
      "Annabelle Cane",
      "Oliver Banks",
      "Jude Perry",
      "Mike Crew",
      "Gerard Keay",
      "Mary Keay",
      "Agnes Montague",
      "Nikola Orsinov",
      "Simon Fairchild",
      "Adelard Dekker",
      "The Admiral (cat)",
      "Not-Sasha / The Not-Them",
      "Jared Hopworth",
    ],
    settingPlaceholder: "e.g., The Archives, tape recorder clicking on, a new statement beginning",
  },
  {
    id: "sanders-sides",
    name: "Sanders Sides",
    category: "web-other",
    canonRules:
      "Thomas Sanders' personality is represented by anthropomorphized Sides: Patton (Morality), Logan (Logic), Roman (Creativity), Virgil (Anxiety), and others including Janus (Deceit) and Remus (Intrusive Thoughts / Dark Creativity). The Sides inhabit Thomas's mind and manifest to help (or hinder) him. Each Side has a core function and distinct personality. Do not flatten their complexity — even 'dark' Sides have valid roles. Maintain the theatrical, YouTube-creator tone.",
    locations:
      "Thomas's living room, The Mind Palace, The Light Side areas, The Dark Side (Subconscious), The Imagination, Various mindscape locations",
    characters: [
      "Thomas Sanders",
      "Patton (Morality)",
      "Logan (Logic)",
      "Roman (Creativity)",
      "Virgil (Anxiety)",
      "Janus (Deceit)",
      "Remus (Intrusive Thoughts / Dark Creativity)",
      "The Orange Side",
      "Joan (Thomas's friend)",
      "Talyn (Thomas's friend)",
      "Emile Picani (therapist character)",
      "Remy (Sleep)",
      "Dr. Emile Picani",
    ],
    settingPlaceholder: "e.g., Thomas's living room, the Sides materializing for a heated debate",
  },
  {
    id: "hermitcraft",
    name: "Hermitcraft",
    category: "web-other",
    canonRules:
      "Hermitcraft is a Minecraft SMP (survival multiplayer) server with content creators who build lore and storylines within the game. Each Hermit has a persona (Grian the gremlin builder, Scar the magical mayor, Mumbo the redstone genius, etc.). Seasons reset the world. The shopping district, minigames, and collaborative/competitive builds are central. Do not confuse real-person boundaries — write the personas, not the real people. Maintain the lighthearted, creative, community-driven tone.",
    locations:
      "The Hermitcraft server, The Shopping District, Various Hermit bases, Boatem, Scarland, The Nether, The End, Various community builds",
    characters: [
      "Grian",
      "Scar / GoodTimesWithScar",
      "Mumbo Jumbo",
      "Bdubs",
      "Etho",
      "Doc / Docm77",
      "Impulse",
      "Tango",
      "Pearl / PearlescentMoon",
      "Gem / GeminiTay",
      "Iskall85",
      "Xisuma",
      "Rendog",
      "False / FalseSymmetry",
      "Stress / StressMonster",
      "Cleo / ZombieCleo",
      "Joe Hills",
      "Keralis",
      "Cub / Cubfan135",
      "Beef / VintageBeef",
      "Hypno / Hypnotizd",
      "Jevin / iJevin",
      "Welsknight",
      "TFC / TinFoilChef",
      "Zedaph",
      "Skizz / SkizzlemanTV",
      "Joel / SmallishBeans",
    ],
    settingPlaceholder: "e.g., The shopping district at sunset, a new prank war brewing",
  },
  {
    id: "omori",
    name: "OMORI",
    category: "web-other",
    canonRules:
      "Headspace is a dream world created by Sunny/Omori to escape trauma. White Space is where Omori retreats to. The real world (Faraway Town) and Headspace mirror each other with darker truths. The game's central secret involves a tragedy that Sunny has repressed. Do not reveal the truth about Mari casually — it is the emotional core. Something is the manifestation of guilt. Maintain the contrast between Headspace's colorful whimsy and the real world's melancholic weight.",
    locations:
      "Headspace, White Space, Faraway Town, Vast Forest, Otherworld, Deep Well, Last Resort, Sunny's House, The Treehouse, Black Space",
    characters: [
      "Sunny / Omori",
      "Aubrey",
      "Kel",
      "Hero",
      "Basil",
      "Mari",
      "Something",
      "Abbi",
      "Sweetheart",
      "Captain Spaceboy",
      "Humphrey",
    ],
    settingPlaceholder: "e.g., White Space, nothing but a single lightbulb and a laptop",
  },
  {
    id: "five-nights-at-freddys",
    name: "Five Nights at Freddy's",
    category: "web-other",
    canonRules:
      "The animatronics at Freddy Fazbear's Pizza are haunted by the spirits of murdered children. William Afton is the Purple Guy / Springtrap — the murderer. The lore spans decades of restaurants and incidents. Remnant is the supernatural substance binding souls to metal. Do not simplify the timeline — it is intentionally complex. Security cameras, doors, and limited power are survival mechanics. Maintain the creepy-corporate-mascot horror tone.",
    locations:
      "Freddy Fazbear's Pizza, The Security Office, Parts and Service, The Pizzaplex, Fazbear's Fright, The FNAF 4 bedroom, The Afton household, The Scooping Room",
    characters: [
      "Michael Afton",
      "William Afton / Springtrap / Purple Guy",
      "Freddy Fazbear",
      "Foxy",
      "Chica",
      "Bonnie",
      "Circus Baby / Elizabeth Afton",
      "The Puppet / Charlotte Emily",
      "Glamrock Freddy",
      "Vanessa / Vanny",
      "Gregory",
      "Cassidy / Golden Freddy",
    ],
    settingPlaceholder: "e.g., The security office at 3 AM, power at 15%, something moving in the hallway",
  },
  {
    id: "dungeons-and-dragons",
    name: "Dungeons & Dragons",
    category: "web-other",
    canonRules:
      "D&D is a tabletop RPG system — stories can use any official setting (Forgotten Realms, Eberron, Greyhawk, etc.) or homebrew worlds. Respect class/race abilities and spell slot limitations. The party dynamic (tank, healer, DPS, utility) drives adventure structure. Alignments (Lawful Good to Chaotic Evil) are guidelines, not prisons. Do not make all characters combat-focused — social encounters and exploration are pillars too. Maintain the collaborative storytelling spirit.",
    locations:
      "Waterdeep, Baldur's Gate, Neverwinter, The Underdark, Avernus, Ravenloft, Sigil, The Feywild, The Astral Sea, A random tavern",
    characters: [
      "Custom player characters (specify race/class)",
      "Drizzt Do'Urden",
      "Strahd von Zarovich",
      "Elminster",
      "Tasha / Iggwilv",
      "Vecna",
      "Jarlaxle",
      "Minsc and Boo",
      "Mordenkainen",
      "Acererak",
    ],
    settingPlaceholder: "e.g., A dimly lit tavern, a stranger with a map and a proposition",
  },
  {
    id: "lego-monkie-kid",
    name: "LEGO Monkie Kid",
    category: "web-other",
    canonRules:
      "Based on Journey to the West mythology but in a modern-day setting. MK (Monkie Kid) inherited the Monkey King's staff and powers. The Demon Bull King and his family are recurring antagonists. Celestial magic and ancient mythology coexist with noodle shops and city life. Respect the Journey to the West references — Sun Wukong, Pigsy, Sandy, Tang are reimagined but rooted in legend. Do not ignore the chosen-one burden MK carries. Maintain the vibrant, action-comedy tone.",
    locations:
      "Megapolis, Pigsy's Noodle Shop, Flower Fruit Mountain, The Flaming Mountains, The Celestial Realm, MK's apartment, The Bone Demon's lair",
    characters: [
      "MK / Monkie Kid",
      "Mei / Dragon Girl",
      "Monkey King / Sun Wukong",
      "Pigsy",
      "Tang",
      "Sandy",
      "Red Son",
      "Princess Iron Fan",
      "Demon Bull King",
      "Macaque",
      "Lady Bone Demon",
    ],
    settingPlaceholder: "e.g., Pigsy's Noodle Shop, a normal day interrupted by demon activity",
  },
  {
    id: "the-adventure-zone",
    name: "The Adventure Zone",
    category: "web-other",
    canonRules:
      "The Adventure Zone is an actual-play D&D podcast by the McElroy family. Balance is the most popular campaign — three reclaimers (Taako, Magnus, Merle) work for the Bureau of Balance to recover Grand Relics. The Stolen Century and finale recontextualize everything. Other campaigns (Amnesty, Ethersea, Graduation) exist separately. Do not confuse campaigns. The humor is irreverent but the emotional beats hit hard. Maintain the goofball-comedy-to-tears pipeline.",
    locations:
      "The Bureau of Balance moonbase, Phandalin, The Felicity Wilds, Refuge, The Astral Plane, Wonderland, The Hunger's void",
    era: "Specify campaign (Balance, Amnesty, Ethersea, etc.)",
    characters: [
      "Taako",
      "Magnus Burnsides",
      "Merle Highchurch",
      "Lucretia / The Director",
      "Lup",
      "Barry Bluejeans",
      "Angus McDonald",
      "Kravitz",
      "Davenport",
      "The Hunger / John",
      "Carey Fangbattle",
    ],
    settingPlaceholder: "e.g., The Bureau of Balance moonbase, Fantasy Costco open for business",
  },
  {
    id: "check-please",
    name: "Check Please!",
    category: "web-other",
    canonRules:
      "Bitty (Eric Bittle) is a former figure skater turned college hockey player at Samwell University. The story is told through his vlog/social media posts. Hockey terminology and college culture are central. Bitty bakes pies as a coping mechanism. The Samwell Men's Hockey team (SMH) is found family. Jack Zimmermann has anxiety and the pressure of being an NHL legacy. Do not ignore the queer romance (Zimbits is the central ship). Maintain the warm, vlog-style intimate tone.",
    locations:
      "The Haus (Samwell hockey house), Faber Ice Rink, Samwell University campus, Annie's Coffee, Providence (Jack's apartment), Madison (Georgia), The NHL",
    characters: [
      "Eric 'Bitty' Bittle",
      "Jack Zimmermann",
      "Shitty Knight",
      "Ransom / Justin Oluransi",
      "Holster / Adam Birkholtz",
      "Lardo / Larissa Duan",
      "Nursey / Derek Nurse",
      "Dex / William Poindexter",
      "Chowder / Chris Chow",
      "Kent 'Parse' Parson",
      "Tater / Alexei Mashkov",
    ],
    settingPlaceholder: "e.g., The Haus kitchen, Bitty stress-baking pies before a big game",
  },
];
